smartdevicelink/sdl_java_suite

sdl_android_lib/CONTRIBUTING.md

This is necessary to show people who wish to create a pull request information that they need to know. It will also contain information regarding the CLA when that's ready.
Anticipated merge date is Jan 27, 2015

Add a CONTRIBUTING file

---

sdl_android_lib/src/com/smartdevicelink/proxy/rpc/PutFile.java

This was PR #49, but I messed up the branches on my fork, so I'm re-submitting this change.

Fix for how PutFile handles bulk data

---

sdl_android_lib/src/com/smartdevicelink/proxy/rpc/DisplayCapabilities.java

See issue #52 and previously fixed issue #1.

Fix merge issue with DisplayCapabilities

---

sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyALM.java
sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/DisplayCapabilities.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/PutFile.java
sdl_android_lib/src/com/smartdevicelink/transport/BTTransport.java

Merging the changes from last week into master branch as release 3.2.0.  All changes have already been reviewed, but due to API changes, this will be considered a "minor" version under semantic versioning, hence the pull request for review as well.
Here are the issues that are addressed in this version:
* Fixed bluetooth exception handling (#72)
* Added getter for AudioPassThruCapabilities in SdlProxy (#73)
* Catch a rare exception when SDL is disconnected and tries to send a broadcast intent (#76)
* Fix issue with PutFile data (#54)
* Fix typo in DisplayCapabilities (#55)

Release 3.2.0

---

README.md
sdl_android_lib/src/com/smartdevicelink/transport/SiphonServer.java

Fixed #60 with commit 58ce58587709c7edee79ccfafc6e784c015e85ac

Changes for proper enabling and disabling of Siphon Server

---

sdl_android_lib/src/com/smartdevicelink/proxy/rpc/GPSData.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/GetVehicleDataResponse.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/OnVehicleData.java
sdl_android_lib/src/com/smartdevicelink/util/SdlDataTypeConverter.java

Regarding issue #57 
Commit 5e386668060d54dc907a664eaa9c63c82abc8b0f

Changes for checking type on Vehicle Data

---

sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java

Fixes #53. Modified layout capabilities when display layout is successfully changed.
Signed-off-by: Mike Burke mike@livioconnect.com

Modified layout capabilities when display layout is successfully changed.

---

sdl_android_lib/src/com/smartdevicelink/proxy/rpc/OnSdlChoiceChosen.java

Made SdlChoice constructor public

---

sdl_android_lib/src/com/smartdevicelink/proxy/RPCStruct.java

Fix for setBulkData ignoring null input

---

sdl_android_lib/src/com/smartdevicelink/proxy/constants/Jingles.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/enums/Jingle.java

Deprecated Jingles class and added Jingle enum

---

sdl_android_lib/src/com/smartdevicelink/Dispatcher/IDispatchingStrategy.java
sdl_android_lib/src/com/smartdevicelink/Dispatcher/ProxyMessageDispatcher.java

Fixes #140.
As a hotfix, this PR should be merged into both master and develop.

Modified generics to follow Java convention

---

sdl_android_lib/src/com/smartdevicelink/protocol/WiProProtocol.java
sdl_android_lib/src/com/smartdevicelink/protocol/enums/SessionType.java
sdl_android_lib/src/com/smartdevicelink/trace/SdlTrace.java

Updated to correct session types and correct java syntax for static finals.

Fixes #183

---

sdl_android_lib/src/com/smartdevicelink/Dispatcher/IDispatchingStrategy.java
sdl_android_lib/src/com/smartdevicelink/Dispatcher/ProxyMessageDispatcher.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/SendLocation.java

Fixes issue #181 by adjusting Float casting.

---

sdl_android_lib/src/com/smartdevicelink/Dispatcher/IDispatchingStrategy.java
sdl_android_lib/src/com/smartdevicelink/Dispatcher/ProxyMessageDispatcher.java
sdl_android_lib/src/com/smartdevicelink/protocol/WiProProtocol.java

Fixes a stack overflow bug.
Regarding issue: #157 
Commit ID: f14bba1cc3a7016586e03f98b0356ef21b60f637

Made changes to remove recursion from HandleReceivedBytes

---

sdl_android_lib/src/com/smartdevicelink/Dispatcher/IDispatchingStrategy.java
sdl_android_lib/src/com/smartdevicelink/Dispatcher/ProxyMessageDispatcher.java
sdl_android_lib/src/com/smartdevicelink/util/ByteEnumer.java

Fixes Issue #191 by adding try/catch block.

---

sdl_android_lib/src/com/smartdevicelink/Dispatcher/IDispatchingStrategy.java
sdl_android_lib/src/com/smartdevicelink/Dispatcher/ProxyMessageDispatcher.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/GetVehicleData.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/GetVehicleDataResponse.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/OnVehicleData.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/SubscribeVehicleData.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/SubscribeVehicleDataResponse.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/UnsubscribeVehicleData.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/UnsubscribeVehicleDataResponse.java

Fixes #132 by directing deprecated methods to replacement methods.

---

sdl_android_lib/src/com/smartdevicelink/Dispatcher/IDispatchingStrategy.java
sdl_android_lib/src/com/smartdevicelink/Dispatcher/ProxyMessageDispatcher.java
sdl_android_lib/src/com/smartdevicelink/protocol/enums/FrameData.java
sdl_android_lib/src/com/smartdevicelink/protocol/enums/FrameDataControlFrameType.java
sdl_android_lib/src/com/smartdevicelink/protocol/enums/FrameType.java
sdl_android_lib/src/com/smartdevicelink/protocol/enums/SessionType.java

Fixes #168 by modifying the toArray call.

---

sdl_android_lib/src/com/smartdevicelink/Dispatcher/IDispatchingStrategy.java
sdl_android_lib/src/com/smartdevicelink/Dispatcher/ProxyMessageDispatcher.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/UpdateTurnList.java

Fixes #169 by changing the key used for data retrieval.

---

sdl_android_lib/src/com/smartdevicelink/streaming/AbstractPacketizer.java
sdl_android_lib/src/com/smartdevicelink/trace/Mime.java
sdl_android_lib/src/com/smartdevicelink/trace/SdlTrace.java

Unused Method Cleanup

---

sdl_android_lib/src/com/smartdevicelink/SdlConnection/SdlConnection.java
sdl_android_lib/src/com/smartdevicelink/SdlConnection/SdlSession.java
sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyALM.java
sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android_lib/src/com/smartdevicelink/transport/BTTransport.java
sdl_android_lib/src/com/smartdevicelink/transport/BTTransportConfig.java
sdl_android_lib/src/com/smartdevicelink/transport/BaseTransportConfig.java
sdl_android_lib/src/com/smartdevicelink/transport/SdlTransport.java
sdl_android_lib/src/com/smartdevicelink/transport/TCPTransport.java
sdl_android_lib/src/com/smartdevicelink/transport/TCPTransportConfig.java
sdl_android_lib/src/com/smartdevicelink/transport/USBTransport.java
sdl_android_lib/src/com/smartdevicelink/transport/USBTransportConfig.java
sdl_android_lib/src/com/smartdevicelink/transport/enums/TransportType.java

transport.enums package

---

sdl_android_lib/src/com/smartdevicelink/proxy/RPCRequestFactory.java

RPCRequestFactory Updates

---

sdl_android_lib/src/com/smartdevicelink/util/SdlDataTypeConverter.java

Just cleaned up value names, documentation, and other small stuff in the SdlDataTypeConverter class.

Converter cleanup

---

sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java

Code was accidentally merged in that broke putfile streaming. This PR should fix it.

Fixes #226

---

sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android_lib/src/com/smartdevicelink/proxy/interfaces/IProxyListenerBase.java

Implement turn by turn interfaces and callbacks

---

sdl_android_lib/src/com/smartdevicelink/protocol/WiProProtocol.java

Regarding #233 , #234
See iOS discussion for more details: https://github.com/smartdevicelink/sdl_ios/issues/256#issuecomment-128373591

Feature 128k MTU Size for v3 / v4 protocols

---

sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java

Removed logging originally used for policies troubleshooting.

---

sdl_android_lib/src/com/smartdevicelink/proxy/RPCRequestFactory.java
sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyALM.java
sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/DeviceInfo.java

Ready For Merge
Regarding issue #235

Feature/deviceinfo populate deviceinfo automatically and include in RAI request

---

CHANGELOG.md

Just need the sign off to say this looks good and I will merge into develop, tag, and then release.

Add change log for v4

---

sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android_lib/src/com/smartdevicelink/streaming/StreamRPCPacketizer.java

Removed minor compilation warnings

---

sdl_android_lib/src/com/smartdevicelink/proxy/RPCMessage.java
sdl_android_lib/src/com/smartdevicelink/proxy/RPCRequest.java
sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/PutFile.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/listeners/OnPutFileUpdateListener.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/listeners/OnRPCNotificationListener.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/listeners/OnRPCResponseListener.java
sdl_android_lib/src/com/smartdevicelink/streaming/StreamRPCPacketizer.java

Refactored RPCUpdateListener to RPCUpdateListener. Added OnNotificationListener. Made changes to SdlProxyBase to reflect these changes.
First pass through updating rpc listeners. Looking for feedback.

Improved RPC Callbacks.

---

sdl_android_lib/src/com/smartdevicelink/util/CorrelationIdGenerator.java

Added a correlation id generator to avoid having to keep track of such a thing.
It will also roll over.

Correlation ID Generator

---

sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java

Fix proxy to not discard hybrid or bulk data service packets

---

sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/OnSystemRequest.java

The proxy previously couldn't handle the HTTP policy request strategy. This pull request will correct the incorrect implementation.

Handle http on system requests

---

sdl_android_lib/src/com/smartdevicelink/SdlConnection/ISdlConnectionListener.java
sdl_android_lib/src/com/smartdevicelink/SdlConnection/SdlConnection.java
sdl_android_lib/src/com/smartdevicelink/SdlConnection/SdlSession.java
sdl_android_lib/src/com/smartdevicelink/protocol/AbstractProtocol.java
sdl_android_lib/src/com/smartdevicelink/protocol/IProtocolListener.java
sdl_android_lib/src/com/smartdevicelink/protocol/ProtocolFrameHeaderFactory.java
sdl_android_lib/src/com/smartdevicelink/protocol/WiProProtocol.java
sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/enums/SdlDisconnectedReason.java

On Session Ended, send hashID to end RPC service

---

sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java

Fix proxy getter for app resumption with persistent data

---

sdl_android_lib/src/com/smartdevicelink/SdlConnection/SdlConnection.java
sdl_android_lib/src/com/smartdevicelink/transport/MultiplexBluetoothTransport.java
sdl_android_lib/src/com/smartdevicelink/transport/MultiplexTransport.java
sdl_android_lib/src/com/smartdevicelink/transport/RouterServiceValidator.java
sdl_android_lib/src/com/smartdevicelink/transport/SdlBroadcastReceiver.java
sdl_android_lib/src/com/smartdevicelink/transport/SdlPsm.java
sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterService.java
sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterStatusProvider.java
sdl_android_lib/src/com/smartdevicelink/transport/TransportBroker.java
sdl_android_lib/src/com/smartdevicelink/transport/TransportConstants.java
sdl_android_lib/src/com/smartdevicelink/util/DebugTool.java

This PR will involve several commits that will clean up some of the multiplexing integration.

Multiplexing cleanup

---

sdl_android_lib/src/com/smartdevicelink/protocol/WiProProtocol.java

Please see link below for details:
https://github.com/smartdevicelink/sdl_android/issues/333

Fixes for github issue #333.

---

sdl_android_lib/src/com/smartdevicelink/proxy/rpc/enums/DisplayType.java

Add SDL_GENERIC to DisplayType enum

---

sdl_android_lib/src/com/smartdevicelink/protocol/enums/FunctionID.java
sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android_lib/src/com/smartdevicelink/proxy/interfaces/IProxyListenerBase.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/Coordinate.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/GetWayPoints.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/GetWayPointsResponse.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/LocationDetails.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/OasisAddress.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/OnWayPointChange.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/SubscribeWayPoints.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/SubscribeWayPointsResponse.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/UnsubscribeWayPoints.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/UnsubscribeWayPointsResponse.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/enums/WayPointType.java
sdl_android_lib/src/com/smartdevicelink/util/SdlDataTypeConverter.java

Please see issue #344 for details.

API's associated with Last Mile Navigation evolution task

---

sdl_android_lib/src/com/smartdevicelink/proxy/rpc/DateTime.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/OasisAddress.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/SendLocation.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/enums/DeliveryMode.java

Please see issue #343 for details.

API's associated with SendLocation Updates evolution task

---

sdl_android_lib/src/com/smartdevicelink/transport/MultiplexBluetoothTransport.java

Keep server socket alive until transport shutdown

---

sdl_android_lib/src/com/smartdevicelink/transport/TransportBroker.java

Added a return statement after null check in TransportBroker
Fixes #363

Fix NPE crash in TransportBroker

---

sdl_android_tests/AndroidManifest.xml

Change the package name for the unit tests

---

sdl_android_lib/src/com/smartdevicelink/transport/USBTransport.java
sdl_android_lib/src/com/smartdevicelink/transport/USBTransportConfig.java

Fix continuous proxy cycle after AOA usb disconnect occurs

---

sdl_android_tests/AndroidManifest.xml

This is becoming an increasing issue  in terms of severity. Once pulled in, I will create a hotfix release.

Pull in PR #367 as hotfix into master

---

sdl_android_lib/src/com/smartdevicelink/SdlConnection/SdlConnection.java
sdl_android_tests/src/com/smartdevicelink/SdlConnection/SdlConnectionTest.java

-add condition to if statement so it shorts if it is null
-refers to #383

Fixing case where config.getService() returns null

---

sdl_android_lib/src/com/smartdevicelink/util/HttpRequestTask.java

Catch NPE in case the Servers are down

---

sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterService.java

Catch NPE and return false if caught. Only meant to catch NPE in isEnabled() call.

Surround body of bluetoothAvailable() with try/catch

---

sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java

-For issue #386 
-Ran on Gen 3 TDK with sample app

Checking that rpcListeners are not null before clearing them

---

sdl_android_lib/src/com/smartdevicelink/transport/SdlBroadcastReceiver.java

- Issue #381 
- Iterating through list indices instead of range-based for loop

Replace range based for loop with index-based

---

sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterService.java
sdl_android_tests/src/com/smartdevicelink/test/utl/AndroidToolsTests.java
sdl_android_tests/src/com/smartdevicelink/transport/LocalRouterServiceTests.java

Added try/catches when building LocalRouterService from parcel

---

sdl_android_lib/src/com/smartdevicelink/SdlConnection/SdlSession.java
sdl_android_lib/src/com/smartdevicelink/protocol/AbstractProtocol.java
sdl_android_lib/src/com/smartdevicelink/protocol/WiProProtocol.java
sdl_android_lib/src/com/smartdevicelink/streaming/AbstractPacketizer.java
sdl_android_lib/src/com/smartdevicelink/streaming/StreamPacketizer.java
sdl_android_lib/src/com/smartdevicelink/streaming/StreamRPCPacketizer.java

Fix the packet streaming classes to use the current MTU

---

sdl_android_lib/src/com/smartdevicelink/protocol/WiProProtocol.java
sdl_android_tests/src/com/smartdevicelink/protocol/WiProProtocolTests.java

-make sure that null accumulator is not used
-issue #389

Catch OOM when allocating for accumulator

---

sdl_android_lib/src/com/smartdevicelink/transport/BTTransport.java
sdl_android_lib/src/com/smartdevicelink/transport/MultiplexBluetoothTransport.java
sdl_android_lib/src/com/smartdevicelink/transport/TCPTransport.java

Removed 2 incredibly verbose logs from TCP transport and modified TCP and BT transports to read using a buffer rather than byte-by-byte.
Corresponding issue: #394

Fix performance issues with TCP, BT and MultiplexBT transports

---

sdl_android_lib/src/com/smartdevicelink/SdlConnection/SdlConnection.java
sdl_android_lib/src/com/smartdevicelink/transport/MultiplexTransportConfig.java
sdl_android_lib/src/com/smartdevicelink/transport/RouterServiceValidator.java
sdl_android_tests/src/com/smartdevicelink/test/transport/MultiplexTransportConfigTests.java
sdl_android_tests/src/com/smartdevicelink/transport/RSVTestCase.java

Rsvp tiered security levels

---

sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterService.java
sdl_android_lib/src/com/smartdevicelink/transport/TransportBroker.java
sdl_android_lib/src/com/smartdevicelink/transport/TransportConstants.java
sdl_android_lib/src/com/smartdevicelink/transport/utl/ByteArrayMessageSpliter.java

Change AppId from Long to String for multiplexing

---

sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterService.java

Fixes #437 
Cleaned up some code around version checking and better logic flow.

Clean up code around version checking start up.

---

sdl_android/src/main/java/com/smartdevicelink/security/SdlSecurityBase.java

Fix a NPE when calling handleInitResult

---

CHANGELOG.md

Branch should be tested fully.
Once merged into develop, full release will be made for 4.3.0

4.3.0 Release Candidate

---

sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/SdlMsgVersionTest.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/SdlMsgVersion.java

Added patch version to SdlMsgVersion.java

---

sdl_android/src/main/java/com/smartdevicelink/protocol/BinaryFrameHeader.java

Add catch for ArrayIndexOutOfBoundsException

---

.travis.yml

Fix TravisCI failures

---

sdl_android/bintray.gradle
sdl_android/bintray.properties
sdl_android/build.gradle

Fill out user and api_key fields. Change version.Name to the correct version. Use `./gradlew bintrayUpload` to upload

Working gradle script that deploys to Bintray

---

sdl_android/src/main/java/com/smartdevicelink/protocol/WiProProtocol.java
sdl_android/src/main/java/com/smartdevicelink/streaming/StreamPacketizer.java

Update buffer read size for encrypted payloads to match TLS record standard

---

sdl_android/src/main/java/com/smartdevicelink/transport/RouterServiceValidator.java
sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

Fix issue [#462](https://github.com/smartdevicelink/sdl_android/issues/462)

#462 Consolidated all intent action “sdl.router.startservice” 

---

sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexBluetoothTransport.java

Bugfix/issue 427 - Clearing static instance on error state

---

sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/AppHmiTypeTests.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/AppHMIType.java

Fixes #433 
Added new enum to existing unit test and executed test successfully
Added enum `PROJECTION` to:
- `AppHmiTypeTests.java`
- `AppHMIType.java`

adding HMI type projections

---

sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/LanguageTests.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/Language.java

Feature/issue 514 - Adding two Language enums

---

sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/LanguageTests.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/Language.java

Fixes #561
Added new languages to existing unit test class and tested successfully
Edited:
- `Language.java`
- `LanguageTests.java`
- Also added languages already implemented into core as stated in: https://github.com/smartdevicelink/sdl_core/pull/171

Implement SDL 0076 additional languages

---

sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/PutFile.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/SetAppIcon.java

Fixes #640 
No testing, as it only changes documentation
Added note in documentation about max file name length in appropriate classes

add filename max length documentation

---

sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/TouchType.java

Add enum to OnTouchEvent for cancellation gesture

---

sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/TouchTypeTests.java

Forgot to include a unit test for gesture cancellation.

Fixed a failing test

---

sdl_android/src/androidTest/assets/json/GetSystemCapability.json
sdl_android/src/androidTest/java/com/smartdevicelink/test/Test.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/proxy/SdlProxyBaseTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/HMICapabilitiesTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/SystemCapabilityTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/requests/GetSystemCapabilityTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/responses/GetSystemCapabilityResponseTests.java
sdl_android/src/main/java/com/smartdevicelink/protocol/enums/FunctionID.java
sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android/src/main/java/com/smartdevicelink/proxy/interfaces/IProxyListenerBase.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/GetSystemCapability.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/GetSystemCapabilityResponse.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/HMICapabilities.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/NavigationCapability.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/PhoneCapability.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/SystemCapability.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/SystemCapabilityType.java

-Edited HMICapabilities to include video&audio streaming params
-Added GetSystemCapability Request & Response classes
-Added SystemCapability struct
-Added SystemCapabilityType enum
Issue #486

Feature/issue 486 - System Capabilities Query

---

sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

Handles #556 
Also fixes #550 
Changed implicit broadcast to explicit and added a tag for receiver to operate in foreground.

556 Android O Changes - Phase 1

---

sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java

Fixes [issue 582](https://github.com/smartdevicelink/sdl_android/issues/582)
This PR makes **NO** API changes.

#582 Remove unused intent extra and ambiguous validation call

---

.travis.yml
sdl_android/src/androidTest/java/com/smartdevicelink/test/SdlConnection/SdlSessionTests.java
sdl_android/src/main/java/com/smartdevicelink/SdlConnection/SdlSession.java
sdl_android/src/main/java/com/smartdevicelink/protocol/WiProProtocol.java
sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android/src/main/java/com/smartdevicelink/proxy/interfaces/ISdlServiceListener.java
sdl_android/src/main/java/com/smartdevicelink/streaming/VideoStreamingParams.java

535 Add video streaming capabilities - BSON

---

sdl_android/src/androidTest/java/com/smartdevicelink/test/util/DeviceUtil.java

Fixes #597. 
Added more checks that seem to have been changed in the Android v22 emulator.

Fixes #597 isEmulator

---

sdl_android/src/androidTest/java/com/smartdevicelink/test/Test.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/Validator.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/proxy/SystemCapabilityManagerTests.java
sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyALM.java
sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android/src/main/java/com/smartdevicelink/proxy/SystemCapabilityManager.java
sdl_android/src/main/java/com/smartdevicelink/proxy/interfaces/OnSystemCapabilityListener.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/SystemCapability.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/SystemCapabilityType.java

Adding System Capability Manager per #566

566 System Capability Manager

---

sdl_android/src/main/java/com/smartdevicelink/protocol/WiProProtocol.java

Fixes #621 - Correct EndService  Payloads

---

sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java

Fix incorrect if condition

---

sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/RadioControlData.java

Fixes #633 
n/a
Fix a documentation comment based on SDL Evolution [#285](https://github.com/smartdevicelink/sdl_evolution/pull/285).
* Fix some documentation

update documentation per Evo Pro

---

sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java

Set accepted video params for protocol versions less than 5

---

sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java

bugfix / issue 652

---

sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

Fixes #674 
Unit tests were ran. Also ran smoke tests
The router service code contained a lot of warnings that needed to be addressed. Code logic was simplified were possible. Spelling errors were fixed when not relating to public methods.

Clean up of router service code. Fixes #674

---

sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

Fixes #689 
I just fixed an array boundary issue by subtracting one from the loop counter in function deployNextRouterService in SdlRouterService class
* fixes issue #689

Fix array boundary issue in deployNextRouterService

---

sdl_android/src/main/java/com/smartdevicelink/util/AndroidTools.java

Fix issue #691

---

sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java

Tested against Ford TDK
- Add in a private method checking whether the BT state is connected or not, instead of just launching the Router Service blindly.
- Removed Unused Imports

Add Bluetooth connection check to SDLBR

---

sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java

Removed pre-O logic for waking up the router service. Logic is now the same for all versions of the OS.

Remove pre-O behavior for starting up RS

---

sdl_android/build.gradle
sdl_android/src/androidTest/java/com/smartdevicelink/protocol/SdlPacketTests.java

Run the unit tests included in the PR!
Tests encoding and decoding of BSON objects via SdlPacket.
- [ X ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

Adding BSONEncoder unit tests

---

README.md

NA
Adding Proguard section in README

Adding Proguard section to README

---

sdl_android/src/androidTest/java/com/smartdevicelink/test/Test.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/SingleTireStatusTest.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/TPMSTests.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/SingleTireStatus.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/TPMS.java

Fixes #613 
- Unit tests added to library
- Smoke testing with core team
Implement Evolution proposal 0097 to spec

Implement SDL 0097 Tire pressure additions

---

sdl_android/src/androidTest/assets/json/SystemRequest.json
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/RequestTypeTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/notifications/OnSystemRequestTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/requests/SystemRequestTests.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/OnSystemRequest.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/SystemRequest.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/RequestType.java

Fixes #594  
* Updated the current unit tests and added new ones to test SystemRequest, OnSystemRequest, RequestType.
This PR implements an expandable design for proprietary data exchange as described in the proposal.

Feature/issue 594 - Expandable Design for Proprietary Data Exchange

---

sdl_android/src/androidTest/assets/json/AddSubMenu.json
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/requests/AddSubmenuTests.java
sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/AddSubMenu.java

Fixes #603 
* Updated the current unit tests to work with the new icon field in `AddSubMenu`.
This PR adds a new `menuIcon` parameter`to AddSubMenu` RPC as described in the proposal.

Feature/issue 603 - SubMenu icon

---

sdl_android/build.gradle

This hotfix changes the `versionName` from `RC_4.6.0` to `4.6.1`
* Change `versionName` from `RC_4.6.0` to `4.6.1`
* Update `versionCode`

Fix versionName

---

sdl_android/src/androidTest/java/com/smartdevicelink/api/SdlManagerTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/Test.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/api/SdlManagerTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/proxy/LockScreenManagerTest.java
sdl_android/src/main/java/com/smartdevicelink/api/SdlManager.java

These are the tests for the SDL Manager. They focus on areas that are not tested in other areas of the library

SDL Manager Tests

---

sdl_android/src/androidTest/java/com/smartdevicelink/test/Test.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/Validator.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/MassageCushionFirmnessTest.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/MassageModeDataTest.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/ModuleDataTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/RemoteControlCapabilitiesTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/SeatControlCapabilitiesTest.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/SeatControlDataTest.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/SeatMemoryActionTest.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/MassageCushionTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/MassageModeTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/MassageZoneTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/MetadataTypeTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/SeatMemoryActionTypeTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/SupportedSeatTests.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/MassageCushionFirmness.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/MassageModeData.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/ModuleData.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/RemoteControlCapabilities.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/SeatControlCapabilities.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/SeatControlData.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/SeatMemoryAction.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/MassageCushion.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/MassageMode.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/MassageZone.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/ModuleType.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/SeatMemoryActionType.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/SupportedSeat.java

Fixes #651 
Added new unit tests and expanded existing ones
Added RPC's, structs, enums as defined in the Remote Control - Seat proposal.

Feature/issue 651- Remote Control - Seat

---

sdl_android/src/main/java/com/smartdevicelink/api/BaseSubManager.java
sdl_android/src/main/java/com/smartdevicelink/api/InitializationListener.java
sdl_android/src/main/java/com/smartdevicelink/api/ProxyBridge.java
sdl_android/src/main/java/com/smartdevicelink/api/SdlManager.java

Fixes 2 issues:
1. Allows developer to know when sdlmanager is ready to send requests
2. doesnt start submanagers until active proxy connection

WIP: Feature/manager ready callback

---

sdl_android/build.gradle
sdl_android/src/androidTest/java/com/smartdevicelink/PermissionManagerTests.java
sdl_android/src/main/java/com/smartdevicelink/api/PermissionManager/OnPermissionChangeListener.java
sdl_android/src/main/java/com/smartdevicelink/api/PermissionManager/PermissionElement.java
sdl_android/src/main/java/com/smartdevicelink/api/PermissionManager/PermissionFilter.java
sdl_android/src/main/java/com/smartdevicelink/api/PermissionManager/PermissionManager.java
sdl_android/src/main/java/com/smartdevicelink/api/PermissionManager/PermissionStatus.java
sdl_android/src/main/java/com/smartdevicelink/api/SdlManager.java
sdl_android/src/main/java/com/smartdevicelink/protocol/enums/FunctionID.java

Fixes #782 
* Added new Mockito tests to make sure that the listeners work as expected.
This PR implements the `PermissionManager` as described in the proposal.

Feature/issue 782 Android Manager APIs - PermissionManager

---

sdl_android/build.gradle
sdl_android/src/androidTest/java/com/smartdevicelink/api/SdlManagerTests.java
sdl_android/src/main/java/com/smartdevicelink/api/SdlManager.java

This PR enhances the `SdlManager` by adding more tests and giving developers more informative error messages when they don't use the submanagers correctly. 
- Throw exceptions when developers try to use a sub-manager before its status is set to `READY` to give them more information about the right way to use the sub-managers
- Add Mockito tests to `SdlManagerTests.java` to test the asynchronous public methods in `SdlManager`

Feature/SdlManager Mockito Testing

---

.travis.yml
sdl_android/build.gradle
sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java
sdl_android/src/main/res/values/sdl.xml

Fixes #843
- Added synchronization around notification methods
- Refactored notification builder and channel creation
- Added try/catch statements around `startForegroundService` calls to prevent ANR for end users
* #843

Hotfix/ Fix invalid channel issue for foreground service

---

sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/PredefinedLayoutTests.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/PredefinedLayout.java

Fixes #850 
Added unit tests in accordance with other enum classes
Add PredefinedLayout Enum matching iOS API

add enum predefinedlayout

---

sdl_android/src/main/java/com/smartdevicelink/api/SdlManager.java
sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java

This PR adds `SystemCapabilityManager ` to `SdlManager` to let developers query system capabilities.

Add 	SystemCapabilityManager to SdlManager

---

sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/responses/DeleteFileResponseTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/responses/ListFilesResponseTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/responses/PutFileResponseTest.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/DeleteFileResponse.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/ListFilesResponse.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/PutFileResponse.java

Fixes #860 
Reviewed unit tests. It's not easy to test this per say as `format` is called just before the RPC is sent.

Issue 860 - space available non mandatory

---

sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/RadioControlCapabilitiesTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/RadioControlDataTests.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/RadioControlCapabilities.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/RadioControlData.java

Fixes #741 
Added new unit tests and expanded existing ones
Added RPC's, structs, enums as defined in the Remote Control Radio Parameter Update proposal.

Feature/issue 741 - Remote Control Radio Parameter Update

---

sdl_android/src/main/java/com/smartdevicelink/api/SdlManager.java

This PR adds a new method `setAppIcon()` to `SdlManager` to make it easier for the developer to set the icon.

Feature/issue 782 - Add setAppIcon() to SdlManager

---

sdl_android/src/androidTest/java/com/smartdevicelink/api/screen/ScreenManagerTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/api/screen/SoftButtonManagerTests.java
sdl_android/src/main/java/com/smartdevicelink/api/screen/ScreenManager.java
sdl_android/src/main/java/com/smartdevicelink/api/screen/SoftButtonManager.java
sdl_android/src/main/java/com/smartdevicelink/api/screen/SoftButtonObject.java
sdl_android/src/main/java/com/smartdevicelink/api/screen/SoftButtonState.java

Fixes to the SoftButton & ScreenManager per review comments

Feature/issue 782 ScreenManager & SoftButtonManager fixes

---

sdl_android/src/androidTest/java/com/smartdevicelink/managers/video/VideoStreamingManagerTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/protocol/SdlProtocolTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/proxy/SystemCapabilityManagerTests.java
sdl_android/src/main/AndroidManifest.xml
sdl_android/src/main/java/com/smartdevicelink/SdlConnection/SdlSession.java
sdl_android/src/main/java/com/smartdevicelink/SdlConnection/SdlSession2.java
sdl_android/src/main/java/com/smartdevicelink/managers/SdlManager.java
sdl_android/src/main/java/com/smartdevicelink/managers/video/VideoStreamingManager.java
sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android/src/main/java/com/smartdevicelink/proxy/interfaces/ISdl.java

- Reverted changes back to WiProProtocol and used actual Version type
- Removed min SDK manifest declaration
- Used mock in testing SdlProtocol

Minor cleanup to managers

---

sdl_android/src/androidTest/java/com/smartdevicelink/managers/SdlManagerTests.java
sdl_android/src/main/java/com/smartdevicelink/managers/BaseSubManager.java
sdl_android/src/main/java/com/smartdevicelink/managers/SdlManager.java
sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/LockScreenManager.java
sdl_android/src/main/java/com/smartdevicelink/managers/permission/PermissionManager.java
sdl_android/src/main/java/com/smartdevicelink/managers/screen/ScreenManager.java
sdl_android/src/main/java/com/smartdevicelink/managers/screen/SoftButtonManager.java
sdl_android/src/main/java/com/smartdevicelink/managers/video/VideoStreamingManager.java

This PR redefines states changes  for:
- SdlManager
- ScreenManager
- LockScreenManager
- FileManager
- PermissionManager

Improve manager states - Screen & Permission & File & Lockscreen & Sdl

---

sdl_android/src/main/java/com/smartdevicelink/SdlConnection/SdlSession.java

Set Protocol version Earlier in `SdlSession` so it can be used.

set protocol version earlier in onProtocolSessionStarted

---

sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

This PR makes **no ** API changes.
Perform simultaneous transport tests
Refactor the `ROUTER_REQUEST_SECONDARY_TRANSPORT_CONNECTION` section to not automatically overwrite TCP connections when a new request was received.

Fix logic for TCP connection requests

---

sdl_android/src/androidTest/assets/xml/MOBILE_API.xml
sdl_android/src/androidTest/java/com/smartdevicelink/test/Test.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/RPCConstructorsTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/notifications/OnRCStatusTests.java

Run `RPCConstructorsTests` and make sure all tests pass
This PR updates the `MOBILE_API.xml` file in unit tests to reflect the changes in RPC specs 5.0. This will allow `RPCConstructorsTests` to make sure that all RPCs have constructors with all mandatory params.

Update rpc specs file

---

sdl_android/src/main/java/com/smartdevicelink/transport/TransportManager.java

Fixes #932 
This was tested against a sync TDK 
This PR fixes two cases where the `SdlService` would not get an `onDestroy` notification in a case where older versions of SDL were also connected. 
- This now correctly handles the transport disconnect event when a legacy connection was connected and is then destroyed
- Legacy bluetooth connection will now listen for an `ACL_DISCONNECT` intent to be sent to close itself in the event it was listening and the BT device disconnected.

Fix legacy BT disconnect issues

---

README.md
android/README.md
base/README.md
base/src/main/java/android/os/AsyncTask.java
base/src/main/java/android/os/Parcel.java
base/src/main/java/android/os/Parcelable.java
base/src/main/java/android/util/Log.java
baseAndroid/README.md
javaEE/README.md
javaSE/README.md
third_party.md

Adds Licensing and breaks up readme's for new project structure

add licenses and break up readme's

---

android/sdl_android/src/main/java/com/smartdevicelink/managers/SdlManager.java
javaSE/src/main/java/com/smartdevicelink/managers/SdlManager.java

This PR adds RPC notification listeners to SdlManager's Builder in Android and JavaSE

Add RPC notification listeners to SdlManager's Builder 

---

base/src/main/java/com/smartdevicelink/protocol/SdlProtocolBase.java

Fix potential NPEs in SdlProtocolBase

Fix potential NPEs in SdlProtocolBase

---

android/sdl_android/build.gradle
base/src/main/java/com/smartdevicelink/transport/TransportManager.java
javaEE/build.gradle
javaEE/src/main/java/hello_sdl_ee/Main.java
javaSE/build.gradle
javaSE/src/main/java/com/smartdevicelink/managers/lifecycle/LifecycleManager.java
javaSE/src/main/java/hello_sdl/Main.java

Change sourceCompatibility to java 1.7

Change sourceCompatibility to java 1.7

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/proxy/SystemCapabilityManagerTests.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/SdlManager.java
android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java
base/src/main/java/com/smartdevicelink/proxy/interfaces/ISdl.java
javaSE/src/main/java/com/smartdevicelink/managers/SdlManager.java
javaSE/src/main/java/com/smartdevicelink/managers/lifecycle/LifecycleManager.java

- Changed API calls to ISDL instead of LCM
- Added request listener calls to ISDL
- Create instance of ISdlConnecitonListener instead of LCM implementing to further reduce public methods

Reduce public methods in LCM

---

base/src/main/java/com/smartdevicelink/proxy/rpc/WeatherData.java

explicitly define min/max values on some `WeatherData` parameters

update weather data docs

---

javaSE/src/main/java/com/smartdevicelink/managers/lifecycle/LifecycleManager.java

Set RPC Type in LCM Send method

set RPC type in LCM

---

android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java

Fixes #1007 
Tested w/ core team
when sending a button press on 5.0+, it will now not send twice.

only send button press once

---

android/sdl_android/src/main/java/com/smartdevicelink/managers/SdlManager.java
android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
base/src/main/java/com/smartdevicelink/managers/BaseSdlManager.java
hello_sdl_java/src/main/java/SdlService.java
javaSE/src/main/java/com/smartdevicelink/managers/SdlManager.java

- Moved logic into base manager class
- Moved member vars into base manager
- Included notification queue logic into android SDL Manager

Refactor BaseSdlManager to ensure parity

---

base/src/main/java/com/smartdevicelink/managers/audio/BaseAudioStreamManager.java
base/src/main/java/com/smartdevicelink/managers/file/BaseFileManager.java
base/src/main/java/com/smartdevicelink/managers/permission/BasePermissionManager.java
base/src/main/java/com/smartdevicelink/managers/screen/BaseScreenManager.java
base/src/main/java/com/smartdevicelink/managers/video/BaseVideoStreamManager.java

Remove unneeded public modifiers from base managers constructors

Remove unneeded public modifiers from base managers constructors

---

base/src/main/java/com/smartdevicelink/managers/permission/BasePermissionManager.java

Fix potential NPE in PermissionManager

Fix potential NPE in PermissionManager

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/video/VideoStreamManagerTests.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/video/VideoStreamManager.java
android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java

- Made the VPM start the video service before attempting to create the encoder from SdlSession

Fix issue with VPM and  multi transports

---

.travis.yml

Update .travis.yml to test hello sdl apps

Update .travis.yml to test hello sdl apps

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/Test.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/proxy/SystemCapabilityManagerTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/AppServiceCapabilityTest.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/AppServicesCapabilitiesTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/utl/AppServiceFactory.java
base/src/main/java/com/smartdevicelink/proxy/SystemCapabilityManager.java
base/src/main/java/com/smartdevicelink/proxy/rpc/AppServiceCapability.java
base/src/main/java/com/smartdevicelink/proxy/rpc/AppServiceManifest.java
base/src/main/java/com/smartdevicelink/proxy/rpc/AppServicesCapabilities.java
base/src/main/java/com/smartdevicelink/proxy/rpc/SdlMsgVersion.java
base/src/main/java/com/smartdevicelink/proxy/rpc/SystemCapability.java

- Unit tests coverage mostly
- Create a consumer app that subscribes to SystemCapabilities for app services
- Publish an app Service
- Observe the consumer receives the update through the `SystemCapbilityManager`
- Set the SCM to listen for `OnSystemCapbilityUpdated` notifications
- Created convineces methods to deal with comparing and updating lists as the items are stored in List objects requiring manual compares iterating through lists.

SCM listen for sc updates

---

android/hello_sdl_android/src/main/java/com/sdl/hellosdlandroid/SdlService.java

This PR enables DebugTool in hello sdl app when it is in debug mode
- [ x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

Enable DebugTool in HelloSdl

---

android/sdl_android/build.gradle

This PR updates build.gradle file to use the new BSON library that has the latest fixes and improvements

Update build.gradle to use the new BSON library

---

.travis.yml
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties

This PR updates gradle plugin version and updates Travis file to be compatible with the new gradle.

Update gradle plugin

---

hello_sdl_java_ee/src/main/java/com/smartdevicelink/SdlService.java

Added sample `ChoiceSetManager` code to hello_sdl_java_ee

Add choice set sample to hello sdl javaEE

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/TransportManager.java

Fixes #1082
* Will no longer crash when transport record is null during disconnect

Add null check to transport record on disconnect

---

android/sdl_android/src/androidTest/assets/json/UnpublishAppService.json
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/requests/UnpublishAppServiceTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/responses/UnpublishAppServiceResponseTests.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/ProxyBridge.java
android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
base/src/main/java/com/smartdevicelink/protocol/enums/FunctionID.java
base/src/main/java/com/smartdevicelink/proxy/interfaces/IProxyListenerBase.java
base/src/main/java/com/smartdevicelink/proxy/rpc/PublishAppService.java
base/src/main/java/com/smartdevicelink/proxy/rpc/UnpublishAppService.java
base/src/main/java/com/smartdevicelink/proxy/rpc/UnpublishAppServiceResponse.java

Fixes #1060
- unit tests
- smoke tests
Add in `UnpublishAppService`

Implement SDL-0225 Update published app services

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/ButtonNameTests.java
android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/ButtonName.java

Fixes #1068 
Unit tests for `ButtonName` have been updated.
This PR adds the new nav button to the `ButtonName` enum as described in the proposal

[SDL 0224] Navigation Subscription Buttons

---

android/sdl_android/src/main/java/com/smartdevicelink/proxy/LockScreenManager.java
android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyALM.java
android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBuilder.java
android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyConfigurationResources.java
base/src/main/java/com/smartdevicelink/proxy/interfaces/IProxyListenerALM.java
base/src/main/java/com/smartdevicelink/proxy/interfaces/IProxyListenerBase.java

Fixes #1148 
This PR deprecates old proxy classes that should have been deprecated when the new managers were instructed

Deprecate old proxy classes

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/ScreenManagerTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/menu/MenuManagerTests.java
base/src/main/java/com/smartdevicelink/managers/screen/BaseScreenManager.java
base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseMenuManager.java
base/src/main/java/com/smartdevicelink/managers/screen/menu/MenuConfiguration.java

Fixes #1076 
Unit tests and smoke tests
Remove the `@NonNull` requirements for `MenuConfiguration`. Additionally, don't set Menu Config if values are `null`. Added extra checks to `AddSubMenu` method in `BaseMenuManager`

SDL 0231 Menu Tile Revision

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/choiceset/PresentChoiceSetOperationTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/choiceset/PresentKeyboardOperationTests.java
base/src/main/java/com/smartdevicelink/managers/screen/choiceset/AsynchronousOperation.java

Fixes test cases for #1155 
This PR repairs the test cases
Fixes the cancel interaction test cases for blocking operations
* Repairs broken test cases

Fix blocking operations test cases

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/GridTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/ModuleInfoTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/requests/GetInteriorVehicleDataConsentTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/requests/ReleaseInteriorVehicleDataModuleTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/responses/GetInteriorVehicleDataConsentResponseTests.java
base/src/main/java/com/smartdevicelink/proxy/rpc/GetInteriorVehicleDataConsent.java
base/src/main/java/com/smartdevicelink/proxy/rpc/GetInteriorVehicleDataConsentResponse.java
base/src/main/java/com/smartdevicelink/proxy/rpc/Grid.java
base/src/main/java/com/smartdevicelink/proxy/rpc/ModuleInfo.java
base/src/main/java/com/smartdevicelink/proxy/rpc/ReleaseInteriorVehicleDataModule.java

Fixes #1070 
unit tests
Adds in mandatory param constructors

Add Mandatory constructors for multiple modules

---

base/src/main/java/com/smartdevicelink/proxy/rpc/DiagnosticMessageResponse.java
base/src/main/java/com/smartdevicelink/proxy/rpc/GetDTCsResponse.java
base/src/main/java/com/smartdevicelink/proxy/rpc/GetInteriorVehicleDataResponse.java
base/src/main/java/com/smartdevicelink/proxy/rpc/GetSystemCapabilityResponse.java
base/src/main/java/com/smartdevicelink/proxy/rpc/SetInteriorVehicleDataResponse.java

Fixes #1180 
Ran unit tests, changes were additive
removed parameters that are no longer required per 1180

update rpc params

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/ScreenManagerTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/TextAndGraphicManagerTests.java
base/src/main/java/com/smartdevicelink/managers/screen/BaseScreenManager.java
base/src/main/java/com/smartdevicelink/managers/screen/BaseTextAndGraphicManager.java

Fixes #1174 
update and run unit tests
change `templateTitle` to `title` to match iOS

change templateTitle to title

---

base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadChoicesOperation.java

Fixes #1194 
Test using `ChoiceSetManager` with static icons and make sure the icons are displayed correctly 
This PR fixes an issue in `ChoiceSetManager` where it doesn't display static icons. Also fixes potential NPE in `PreloadChoicesOperation`.

Fix issue with static icons and ChoiceSetManager

---

android/sdl_android/src/androidTest/assets/xml/MOBILE_API.xml
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/Test.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/Validator.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/RPCConstructorsTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/GridTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/WindowTypeCapabilitiesTest.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/requests/CreateWindowTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/responses/GetInteriorVehicleDataConsentResponseTests.java
base/src/main/java/com/smartdevicelink/proxy/rpc/CloseApplicationResponse.java
base/src/main/java/com/smartdevicelink/proxy/rpc/GetInteriorVehicleDataConsentResponse.java
base/src/main/java/com/smartdevicelink/proxy/rpc/Grid.java
base/src/main/java/com/smartdevicelink/proxy/rpc/ShowAppMenuResponse.java
base/src/main/java/com/smartdevicelink/proxy/rpc/UnpublishAppServiceResponse.java

Make sure that all tests pass
- Include the new  `MOBILE_API.xml` for RPC spec 6.0
- Update tests and rename some methods to match the sepc

Include the new  MOBILE_API.xml for RPC spec 6.0

---

CHANGELOG.md

- Open `CHANGELOG.md` and make sure all changes are accounted for
- Updated `CHANGELOG.md` to include all new features, bug fixes, etc.

4.10.0 release notes

---

base/src/main/java/com/smartdevicelink/proxy/SystemCapabilityManager.java

Fixes #1221 
This PR fixes some potential NPEs in SystemCapabilityManager

Fix some potential NPEs in SystemCapabilityManager

---

.github/workflows/android.yml

This PR updates the actions in `android.yml` file to the latest versions to increase the stability of GitHub actions CI:
* Update checkout action to v2
* Update codecov-action to v1.0.6
* Update android-emulator-runner action to v2

Update actions in android.yml to the latest version

---

android/hello_sdl_android/src/main/java/com/sdl/hellosdlandroid/SdlReceiver.java

- Verify app still runs against sdl core, menticore, and tdk
Removes an unnecessary check due to adding ManagerShouldUpdateLifecycle

Remove left over code in hellosdl

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/proxy/SystemCapabilityManagerTests.java
android/sdl_android/src/main/java/com/smartdevicelink/SdlConnection/SdlSession.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/ProxyBridge.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/SdlManager.java
android/sdl_android/src/main/java/com/smartdevicelink/proxy/RPCStreamController.java
android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
android/sdl_android/src/main/java/com/smartdevicelink/streaming/StreamRPCPacketizer.java
base/src/main/java/com/smartdevicelink/Dispatcher/IDispatchingStrategy.java
base/src/main/java/com/smartdevicelink/Dispatcher/ProxyMessageDispatcher.java
base/src/main/java/com/smartdevicelink/proxy/IProxyListener.java
base/src/main/java/com/smartdevicelink/proxy/TTSChunkFactory.java
base/src/main/java/com/smartdevicelink/proxy/callbacks/InternalProxyMessage.java
base/src/main/java/com/smartdevicelink/proxy/callbacks/OnError.java
base/src/main/java/com/smartdevicelink/proxy/callbacks/OnProxyClosed.java
base/src/main/java/com/smartdevicelink/proxy/callbacks/OnProxyOpened.java
base/src/main/java/com/smartdevicelink/proxy/callbacks/OnServiceEnded.java
base/src/main/java/com/smartdevicelink/proxy/callbacks/OnServiceNACKed.java
base/src/main/java/com/smartdevicelink/proxy/interfaces/IPutFileResponseListener.java
base/src/main/java/com/smartdevicelink/proxy/interfaces/ISdl.java
base/src/main/java/com/smartdevicelink/proxy/rpc/PutFile.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/SdlConnectionState.java
base/src/main/java/com/smartdevicelink/proxy/rpc/listeners/OnPutFileUpdateListener.java
javaSE/src/main/java/com/smartdevicelink/managers/lifecycle/LifecycleManager.java

Fixes #1362 
Unit tests should not be affected
This PR deprecates some public APIs to prepare for removing them in the next major version change

Deprecate APIs to prepare for next major release

---

android/hello_sdl_android/src/main/java/com/sdl/hellosdlandroid/SdlService.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/SdlManagerTests.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/SdlManager.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/SdlManagerListener.java
base/src/main/java/com/smartdevicelink/managers/BaseSdlManager.java
hello_sdl_java/src/main/java/com/smartdevicelink/java/SdlService.java
javaSE/src/main/java/com/smartdevicelink/managers/SdlManager.java
javaSE/src/main/java/com/smartdevicelink/managers/SdlManagerListener.java

Fixes #1313 
A new SdlManagerListener method would need to be added, and the old one should be deprecated.

SDL-0289 Support for Set Language Separately 

---

android/hello_sdl_android/build.gradle
android/sdl_android/build.gradle
android/sdl_android/src/androidTest/AndroidManifest.xml
android/sdl_android/src/main/java/com/smartdevicelink/SdlConnection/SdlSession.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/SdlManager.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/audio/AudioDecoderCompat.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/audio/AudioStreamManager.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/audio/BaseAudioDecoder.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/LockScreenManager.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/TCPTransport.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/TransportBroker.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/USBAccessoryAttachmentActivity.java
android/sdl_android/src/main/java/com/smartdevicelink/util/MediaStreamingStatus.java
android/sdl_android/src/main/java/com/smartdevicelink/util/SdlAppInfo.java
android/sdl_android/src/main/java/com/smartdevicelink/util/ServiceFinder.java

Fixes #835 
Tested to ensure I was still able to connect to core and a TDK over all transport types.
Tested to ensure LockScreen is still working as expected
Tested to ensure Audio Streaming is still working as expected
These Changes update the minSdk from api level 8 to 16, with this change there were several spots in the code where we check the Android version. If those checks were no longer relevant (checking for version over or under 16) they were changed or removed

Update Min SDK and Android API Checks

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/requests/AddSubmenuTests.java
base/src/main/java/com/smartdevicelink/proxy/rpc/AddSubMenu.java

Fixes #716 
Unit test added to AddSubMenuTest.java 
Core branch: https://github.com/smartdevicelink/sdl_core/pull/3447
Rpc_Spec branch: https://github.com/smartdevicelink/rpc_spec/pull/263
Generic_HMI branch: https://github.com/smartdevicelink/generic_hmi/pull/282
This PR implements [ SDL-0148 Template Improvements: Additional Submenus.](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0148-template-additional-submenus.md)
When testing create an integration branch with PR [SDL-0152 Driver Distraction: Command List Limitations](https://github.com/smartdevicelink/sdl_java_suite/pull/1422l) and test together. You can easily implement submenu feature by modifying …

Implement SDL-0148 Additional SubMenus

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/notifications/OnSystemRequestTests.java
base/src/main/java/com/smartdevicelink/proxy/rpc/OnSystemRequest.java

Fixes #906 
This PR is **[not ready]** for review.
This PR doesn't provide any library changes. Still, it gives unit tests that cover OnSystemRequest class itself with additional checking of the ```url``` parameter to be sure it is not changed in the library over the set/get process.
- New unit tests added for OnSystemRequest class

 [SDL 0200] - Removing url parameter max length

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java
android/sdl_android/src/main/java/com/smartdevicelink/util/AndroidTools.java
android/sdl_android/src/main/java/com/smartdevicelink/util/IntegrationValidator.java

Fixes part of the Java Suite Cleanup
- No unit tests for this class as it is an integration validation tool that will check the developers app for commonly missed items.
Added an integration validator class that handles the misc. checks that need to be done for a proper integration. The class is setup to add more tests to it in the future or modify them if necessary. 
If the app has a proper integration nothing will be shown. Otherwise, a report will be provided and a run time exception is thrown with that message.
* Developers should now be shown if their integration is correct.

Integration validator

---

base/src/main/java/com/smartdevicelink/proxy/rpc/OnVehicleData.java
base/src/main/java/com/smartdevicelink/proxy/rpc/WindowState.java
base/src/main/java/com/smartdevicelink/proxy/rpc/WindowStatus.java

Fixes #1094 
No Changes
these imports were missed from another PR being merged into develop shortly before the AndroidX PR was merged in

Import fixes for androidX

---

README.md

Fixes #1149 
This PR updates the javaSE and JavaSE versions in README to reference the latest versions

Fix JavaEE & JavaSE versions in README

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/transport/RegisteredAppTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/transport/SdlRouterServiceTests.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/TransportBroker.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/TransportManager.java
base/src/main/java/com/smartdevicelink/transport/TransportConstants.java

This PR makes **major** API changes.
- Removed deprecated code that could safely be removed
- Refactored some logic in the `TransportBroker` that is no longer necessary
- Fixed some spelling errors in the `TransportBroker`
- Removed a constant from `TransportConstants`
* Removed some public methods

Remove deprecated code from RouterService and TransportBroker

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/video/HapticInterfaceManagerTest.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/ImageResolutionTests.java

This PR makes **no** API changes. (Due to this being changes to only unit test methods)
Same tests, only test method names have changed.
Used regex to find improper naming `\s+public.*\s\w*[_]\w+\s*\(`
Renamed offending test methods with a few exceptions due to readability.
* Cleaned up test method signatures

Remove underscores in test method names

---

android/sdl_android/build.gradle

This PR updates the BSON library to the latest version that includes some fixes.

Update BSON to RC1_1.2.2

---

android/hello_sdl_android/build.gradle
android/hello_sdl_android/src/main/AndroidManifest.xml
android/hello_sdl_android/src/main/java/com/sdl/hellosdlandroid/MainActivity.java
android/hello_sdl_android/src/main/java/com/sdl/hellosdlandroid/SdlReceiver.java
android/hello_sdl_android/src/main/java/com/sdl/hellosdlandroid/SdlRouterService.java
android/hello_sdl_android/src/main/java/com/sdl/hellosdlandroid/SdlService.java
android/hello_sdl_android/src/main/res/layout/activity_main.xml
android/hello_sdl_android/src/main/res/menu/main.xml
android/hello_sdl_android/src/main/res/xml/accessory_filter.xml
javaEE/hello_sdl_java_ee/src/main/java/com/smartdevicelink/Main.java
javaEE/hello_sdl_java_ee/src/main/java/com/smartdevicelink/SdlService.java
javaSE/hello_sdl_java/src/main/java/com/smartdevicelink/java/Main.java
javaSE/hello_sdl_java/src/main/java/com/smartdevicelink/java/SdlService.java

This PR reformats the code in the sample hello sdl aps

Reformat hello sdl code

---

CHANGELOG.md

This PR updates the changelog to include 5.0 release notes

Add 5.0.0 release notes

---

generator/test/runner.py
generator/test/test_enums.py
generator/test/test_functions.py
generator/test/test_structs.py
generator/transformers/common_producer.py

This PR:
- Updates the RPC generator unit tests to fix the broken tests 
- Update the test runner to return with `exit (1)` to fail the Github actions test when the generator tests fail

Fix RPC Generator Tests 

---

README.md

Fixes #1534 
Additional tests not required as this only changes README documentation.
* Removed outdated information: Genivi links and "Proxy" references
* Added links to library documentation on smartdevicelink.com
* Added links to release documentation on GitHub

Update project documentation references in README

---

android/sdl_android/build.gradle

Fixes #1542 
This PR updates the BSON library to the latest stable version 1.2.2

Update BSON to 1.2.2

---

CHANGELOG.md

This PR updates the CHANGELOG.md to include the latest fixes and enhancements

Update release notes for 5.0.0

---

base/src/main/java/com/smartdevicelink/util/BitConverter.java

Fixes #193
Added checks to prevent `ArrayOutOfBoundsExceptions`

Add checks to avoid ArrayOutOfBoundsException

---

base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java
base/src/main/java/com/smartdevicelink/managers/lifecycle/RpcConverter.java

Fixes #1541 partly for 5.0
Same changes present as the PR #1552 
This PR should be reviewed and tested at the same time as it will require a Sync 2.0 TDK
* Fixes issue where policy table updates wouldn't occur on older systems

Add code to handle legacy PTU (5.0)

---

android/sdl_android/build.gradle
javaEE/javaEE/build.gradle
javaSE/javaSE/build.gradle

Fixes #1589
The PR updates the Taskmaster dependency to the latest version (0.4) which fixes an issue in pausing queues logic. For more info about the issue please see [this](https://github.com/livio/Taskmaster/issues/10).

Update Taskmaster to 0.4

---

base/src/main/java/com/smartdevicelink/proxy/rpc/AppInfo.java
base/src/main/java/com/smartdevicelink/proxy/rpc/RegisterAppInterface.java

Fixes #1608 
na
na
Updated appInfo Javadoc's in RegisterAppInterface.java and AppInfo.java per https://github.com/smartdevicelink/rpc_spec/pull/311
Updated appInfo Javadoc's in RegisterAppInterface.java and AppInfo.java per https://github.com/smartdevicelink/rpc_spec/pull/311

AppInfo rpc spec change

---

javaSE/javaSE/src/main/java/com/smartdevicelink/util/Log.java

Fixes #1397 
N/A
Run JavaSE app 
Core version / branch / commit hash / module tested against: [INSERT]
HMI name / version / branch / commit hash / module tested against: [INSERT]
Fixes issue for JavaSE where an unexpected exception is thrown in log tool in intelliJ for printing errors. When this happens in the PolicyFetcher we would get the exception: `PoliciesFetcher - 5.0.0: sendSystemRequestToUrl: IOException:  - x.x.x.x`, This would cause `SoftButtonObjects` `OnRPCNotificationListener` `OnButtonPress` notifications to be delayed as well as cause the LifeCycle Manager to continue to fetch policies. 
```
INFO: Julian - 5.0.0: onPress:    // This is the button onPress notification that was delayed by a minute.
INFO: …
```

Fix Log tool for JavaSE

---

android/sdl_android/src/androidTest/assets/json/AddCommand.json
android/sdl_android/src/androidTest/assets/json/AddSubMenu.json
android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/lifecycle/SystemCapabilityManagerTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/menu/MenuCellTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/MenuParamsTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/ImageFieldNameTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/TextFieldNameTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/requests/AddCommandTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/requests/AddSubmenuTests.java
base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseMenuManager.java
base/src/main/java/com/smartdevicelink/managers/screen/menu/MenuCell.java
base/src/main/java/com/smartdevicelink/proxy/rpc/AddCommand.java
base/src/main/java/com/smartdevicelink/proxy/rpc/AddSubMenu.java
base/src/main/java/com/smartdevicelink/proxy/rpc/MenuParams.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/ImageFieldName.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/TextFieldName.java

Fixes #1246 
Unit tests updated for changes
To test this PR please add secondaryText, tertiaryText, and secondaryArtwork to various menucells and submenu cells, examples below
```
MenuCell mainCell1 = new MenuCell("Test Cell 1 (speak)", image, null, new MenuSelectionListener() {
@Override
public void onTriggered(TriggerSource trigger) {
Log.i(TAG, "Test cell 1 triggered. Source: " + trigger.toString());
showTest();
}
});
mainCell1.setSecondaryText("Secondary Text");
mainCell1.setTertiaryText("Tertiary Text");
mainCell1.setSecondaryArtwork(image);
MenuCell subCell1 = new MenuCell("SubCell 1", null, null, new MenuSelectionListener() {
@Override
public void onTriggered(TriggerSource trigger) {
Log.i(TAG, "Sub cell 1 …
```

Add Changes from proposal for Main Menu UI updates

---

base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java

Alignment between libraries for #1588 
-Refactored the method that selects the security library for use when vehicle data is supplied
* Fix alignment with iOS library

Refactor security lib selection method (Alignment for 0293)

---

base/src/main/java/com/smartdevicelink/managers/file/UploadFileOperation.java

Fixes #1622
N/A
Try to upload menu items and softButtons with images and very that the images are uploaded propery
This PR will set the PutFile RPCs CRC data bassed on the file data in the UploadFileOperation.
The CRC data will also be set in the getMaxJSONSize method.

Add CRC to PutFile

---

android/hello_sdl_android/src/main/java/com/sdl/hellosdlandroid/SdlService.java
base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseMenuManager.java
javaSE/hello_sdl_java/src/main/java/com/smartdevicelink/java/SdlService.java

Fixes #1628
N/A
N/A
Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: N/A
Add new checks menuCommandSecondaryText, menuCommandTertiaryText, menuSubMenuSecondaryText, and menuSubMenuTertiaryText

Fix Main Menu UI updates do not take text field name into account

---

javaEE/hello_sdl_java_ee/src/main/java/com/smartdevicelink/SdlService.java

Fixes #1639
Verify JavaEE and Hello_SDL_JavaEE projects build
N/A
Core version / branch / commit hash / module tested against: [INSERT]
HMI name / version / branch / commit hash / module tested against: [INSERT]
Update

Update SdlService for 5.1 in JavaEE app

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java
android/sdl_android/src/main/res/values/sdl.xml

Fixes #1672 
This PR makes **no ** API changes.
Update RouterService version number

Router service version update

---

android/build.gradle
android/sdl_android/build.gradle
javaEE/hello_sdl_java_ee/build.gradle
javaEE/javaEE/build.gradle
javaSE/hello_sdl_java/build.gradle
javaSE/javaSE/build.gradle

Fixes #1674 
Removed JCenter from gradle files

Remove JCenter from gradle files

---

android/sdl_android/build.gradle

Fixes #1712 
This PR updates the BSON library to the latest stable version (1.2.5)

Update BSON to the latest stable version 1.2.5

---

base/src/main/java/com/smartdevicelink/proxy/rpc/AudioControlCapabilities.java
base/src/main/java/com/smartdevicelink/proxy/rpc/RadioControlCapabilities.java
base/src/main/java/com/smartdevicelink/proxy/rpc/SeatControlCapabilities.java

Fixes #1739 
n/a
n/a
Fix description for `SeatControlCapabilities` and `RadioControlCapabilities` per RPC spec 8.0.0 PR: :https://github.com/smartdevicelink/rpc_spec/pull/319
* Fix description for `SeatControlCapabilities` and `RadioControlCapabilities` per RPC spec 8.0.0

Fix description for `SeatControlCapabilities` and `RadioControlCapabilities`

---

base/src/main/java/com/smartdevicelink/managers/screen/BaseAlertManager.java

Fixes #1742 
Test showing an alert using the `AlertManager` and confirm it works as expected 
module tested against: SYNC 3.4
This PR updates the queue id for `AlertManager` to be different than the one used in `AudioStreamManager`

Update AlertManager queue id
