sdl_android_lib/src/com/smartdevicelink/proxy/rpc/PerformAudioPassThru.java

Fixes #80.  Changed return type of getMaxDuration from int to Integer.

Changed return type of getMaxDuration in PerformAudioPassThru class

---

sdl_android_lib/src/com/smartdevicelink/proxy/rpc/enums/VrCapabilities.java

Fixes #89.  Deprecated legacy object and added appropriate new object.  Modified valueForString method to follow project guidelines.

Modified VrCapabilities valueForString method to follow project guidelines.

---

sdl_android_lib/src/com/smartdevicelink/proxy/rpc/GetVehicleData.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/GetVehicleDataResponse.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/OnVehicleData.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/SubscribeVehicleData.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/SubscribeVehicleDataResponse.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/UnsubscribeVehicleData.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/UnsubscribeVehicleDataResponse.java

Fixes #84.  Deprecated fuelLevel_State methods and created fuelLevelState methods to follow Java naming conventions

Refactor fuel level state methods to conform to Java naming conventions

---

sdl_android_lib/src/com/smartdevicelink/protocol/enums/FunctionID.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/AlertManeuver.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/AlertManeuverResponse.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/ChangeRegistration.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/GetDTCsResponse.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/SendLocation.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/SendLocationResponse.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/ShowConstantTbt.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/ShowConstantTbtResponse.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/Turn.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/UpdateTurnList.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/UpdateTurnListResponse.java

Implemented Missing RPC APIs

---

sdl_android_lib/src/com/smartdevicelink/proxy/rpc/OnSystemRequest.java

Better bulk data handling in OnSystemRequest

---

sdl_android_lib/src/com/smartdevicelink/Dispatcher/IDispatchingStrategy.java
sdl_android_lib/src/com/smartdevicelink/Dispatcher/ProxyMessageDispatcher.java
sdl_android_lib/src/com/smartdevicelink/protocol/enums/FunctionID.java
sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android_lib/src/com/smartdevicelink/proxy/interfaces/IProxyListenerBase.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/DialNumber.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/DialNumberResponse.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/HMICapabilities.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/OnSystemRequest.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/PutFile.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/RegisterAppInterfaceResponse.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/TouchEvent.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/enums/AppInterfaceUnregisteredReason.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/enums/ImageFieldName.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/enums/KeyboardEvent.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/enums/LayoutMode.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/enums/RequestType.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/enums/Result.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/enums/TextFieldName.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/enums/VehicleDataResultCode.java
sdl_android_lib/src/com/smartdevicelink/streaming/StreamRPCPacketizer.java

:cat2: Ready for review :cat2: 
The following enums need to be updated to match the latest version of the 4.0 mobile api spec:
The following classes need to be updated to match the latest version of the 4.0 mobile api spec:

Updated rpcs to v4.0 

---

sdl_android_lib/src/com/smartdevicelink/Dispatcher/IDispatchingStrategy.java
sdl_android_lib/src/com/smartdevicelink/Dispatcher/ProxyMessageDispatcher.java
sdl_android_lib/src/com/smartdevicelink/SdlConnection/ISdlConnectionListener.java
sdl_android_lib/src/com/smartdevicelink/SdlConnection/SdlConnection.java
sdl_android_lib/src/com/smartdevicelink/SdlConnection/SdlSession.java
sdl_android_lib/src/com/smartdevicelink/protocol/ProtocolMessage.java
sdl_android_lib/src/com/smartdevicelink/protocol/enums/FunctionID.java
sdl_android_lib/src/com/smartdevicelink/proxy/RPCRequestFactory.java
sdl_android_lib/src/com/smartdevicelink/proxy/RPCStreamController.java
sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android_lib/src/com/smartdevicelink/proxy/interfaces/IProxyListenerBase.java
sdl_android_lib/src/com/smartdevicelink/proxy/interfaces/IPutFileResponseListener.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/OnStreamRPC.java
sdl_android_lib/src/com/smartdevicelink/proxy/rpc/StreamRPCResponse.java
sdl_android_lib/src/com/smartdevicelink/streaming/AbstractPacketizer.java
sdl_android_lib/src/com/smartdevicelink/streaming/IStreamListener.java
sdl_android_lib/src/com/smartdevicelink/streaming/StreamPacketizer.java
sdl_android_lib/src/com/smartdevicelink/streaming/StreamRPCPacketizer.java

:boom: READY FOR REVIEW :boom: 
Related to issue #58 
<h2>Summary</h2>
The PutFile RPC allows a developer to send a PutFile request using an offset and length.  Sending a series of PutFile requests allows a developer to split a large file into smaller blocks.  While having the ability to split large files into chunks is a great feature supported by SDL, the bookkeeping and management of offsets and lengths for each individual file is a cumbersome process that should be abstracted from app developers.  Having a mobile API that creates and sends a stream of PutFile requests reduces a large burden on app developers while working with the PutFile RPC.
<h2>Objective:</h2>
Provide a simple mobile public facing API that allows a developer to send a file via SDL to the vehicle head unit utilizing …

Update putfile stream enhancements

---

sdl_android_lib/src/com/smartdevicelink/Dispatcher/IDispatchingStrategy.java
sdl_android_lib/src/com/smartdevicelink/Dispatcher/ProxyMessageDispatcher.java
sdl_android_lib/src/com/smartdevicelink/trace/SdlTrace.java
sdl_android_lib/src/com/smartdevicelink/util/NativeLogTool.java

> _com/smartdevicelink/util/NativeLogTool_
>_com/smartdevicelink/trace/SdlTrace_
This is a very simple modification to existing log methods that makes them return a `boolean` value instead of being `void` methods. Since this return value can be ignored by current calling classes it has almost no effect, however, it will let us verify that messages were logged successfully and allow for better unit testing of this class.
Unit tests are (most likely) the only thing this pull request will effect.

Logging Feedback

---

sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java

Removes deprecation warnings by deprecating old methods related to the change with integer offset/length values and replaced them with the proper methods that accept long values. Documentation included.

Removes deprecation warnings in SdlProxyBase class.

---

sdl_android_lib/src/com/smartdevicelink/protocol/WiProProtocol.java

The mtu size that is specified by core for versions 3 and 4 protocols do not match the value in the mobile library.  Core (and the gen 3 module) set the value to 131072-12 as can be seen in the smartDeviceLink.ini file.  This change updates WiProProtocol.java to match these values.

Hotfix/mtu size for v3 & v4 protocols

---

.travis.yml
build.gradle

Adds a [travis-ci](https://travis-ci.org/) build configuration to the project. This will allow us to see if committed code builds it will also make sure pull requests build. Eventually we will be able to configure travis-ci to run all of our unit tests.
Builds status can be viewed here: [https://travis-ci.org/smartdevicelink/sdl_android](https://travis-ci.org/smartdevicelink/sdl_android)
**NOTE** This will not work for the `master` branch until the files are merged because travis will not build  a branch unless a `.travis.yml` is present.
**.travis.yml** is used to tell travis-ci how to build the Android project and eventually it will be configured to run the project's unit tests.
**gradle.build** is only used to tell travis-ci how to build the Android project. It should not affect …

Add travis-ci automated build

---

sdl_android_lib/src/com/smartdevicelink/proxy/rpc/TouchEvent.java

Gives better names to methods and deprecates old. Fixes issue #213

Rename TouchEvent helper methods  

---

sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterService.java

Some model phones display a race condition where they received the STATE_CHANGE disconnect intent before the RFCOMM/SPP channel disconnects. This would cause the handler for the RFCOMM channel to skip over the lifecycle call for transport disconnect. 
This PR moves the logic for checking if the service is closing just to the scope of whether or not it should restart its bluetooth transport to listen for connections. It will now call the correct disconnect lifecycle methods.

Correct disconnect logic when bluetooth adapter is being turned off 

---

sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyALM.java

During a merge some constructors were directly modified rather than adding new methods with altered method signatures and the old methods deprecated.
This PR reimplements the previous methods unaltered signatures but adds the deprecated tag.

Reimplement methods that should have been deprecated

---

sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBuilder.java

The proxy builder needs to default to the multiplexing transport for the next release. The previous constructor for the builder was deprecated, but it will continue to work until removal. 
The only addition is the builder now requires a context as a necessary parameter.

Builder to use multiplexing as default transport.

---

sdl_android_lib/src/com/smartdevicelink/transport/SdlBroadcastReceiver.java

Fixes #319 
The return type Class should have been parameterized to the correct type instead of just using a raw type.
This will help reduce dev's implementing the library as well as being the best practice overall.

Correct abstract class type in SdlBroadcastReceiver

---

sdl_android_lib/src/com/smartdevicelink/transport/BTTransport.java

From the crash reports in PlayStore I receive some ClassCastExceptions every now and then on devices (seems to be exclusive to tablets) running Android 4.1 and 4.2.
The exceptions occur in BTTransport.openConnection when some exception is cast to SdlException.
The reports contain no line numbers ... I suspect line 190 to be the cause of the error, since this is the only line containing an unchecked cast to SdlException.

Fixed ClassCastException in openConnection

---

sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterService.java
sdl_android_lib/src/com/smartdevicelink/transport/TransportBroker.java
sdl_android_lib/src/com/smartdevicelink/transport/TransportConstants.java

In the future it might be very helpful to have this information. If communication structures change between router service versions the client now has that information. So it will be better to provide this information from the start.
The code for the transport broker is commented out as of right now because there is no use at the moment.

Add router service version to register client response

---

sdl_android_lib/src/com/smartdevicelink/transport/SdlBroadcastReceiver.java

See #335 
List of potential router services was not being fully curated before bailing out. This hot fix will correct the logic.

Fixes #335

---

sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterService.java

This pull request will address #339 by increasing the timeout for the router service version check. 
It also introduces a new curated list of sdl enabled apps that should have the router service by doing a query on the system to find all broadcast receivers listening to the special sdl intent. When the running router service receives intents from all known sdl enabled apps it will perform the version check. 
In summery, timeout is increased, but best case time is decreased.

Better router version checking

---

sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterService.java

Fixed issue where binary frame headers were being added to data for v1 packets and causing an overflow in the data buffer.

Fixed binary frames being added to v1 packets

---

sdl_android_lib/src/com/smartdevicelink/util/HttpRequestTask.java

Set the HttpRequestTask callback to null after a single callback to prevent any other callbacks from happening after that callback event. 
Fixes #355

Prevent incorrect error callbacks in HttpRequestTask 

---

sdl_android_lib/src/com/smartdevicelink/transport/SdlBroadcastReceiver.java

Fix #361 . Change method call to handle case where the extra doesn’t exist

Fix NPE in SdlBroadcastReceiver

---

sdl_android_lib/src/com/smartdevicelink/transport/SdlBroadcastReceiver.java
sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterService.java
sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterStatusProvider.java
sdl_android_lib/src/com/smartdevicelink/util/AndroidTools.java

Adding checks to ensure the SdlRouterService is exported and prevent crashes when attempting to connect to non exported services.
Fixes #353

Add protection against incorrect implementations of SdlRouterService

---

sdl_android_lib/src/com/smartdevicelink/transport/RouterServiceValidator.java
sdl_android_lib/src/com/smartdevicelink/transport/SdlBroadcastReceiver.java

Fix issues with getting the trusted router service list

---

sdl_android_lib/src/com/smartdevicelink/transport/SdlBroadcastReceiver.java
sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterService.java
sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterStatusProvider.java
sdl_android_lib/src/com/smartdevicelink/transport/TransportBroker.java

Fixes #365 
Also fixed a few other obvious issues along the same line in the SdlRouterService.

Hotfix - NPE crash in RouterServiceProvider

---

sdl_android_lib/src/com/smartdevicelink/SdlConnection/SdlConnection.java
sdl_android_lib/src/com/smartdevicelink/transport/RouterServiceValidator.java
sdl_android_lib/src/com/smartdevicelink/transport/SdlBroadcastReceiver.java
sdl_android_lib/src/com/smartdevicelink/transport/TransportConstants.java
sdl_android_tests/AndroidManifest.xml
sdl_android_tests/src/com/smartdevicelink/transport/RSVTestCase.java

Addresses issue #371. 
Based on recent usage and issues, the RSVP system needs improvements. This PR will be merged as a hotfix to address the issues found by the following:

[Hotfix] RSVP Improvements

---

sdl_android_lib/src/com/smartdevicelink/transport/MultiplexBluetoothTransport.java
sdl_android_tests/src/com/smartdevicelink/test/transport/MultiplexBluetoothTransportTest.java

Fixing https://github.com/smartdevicelink/sdl_android/issues/373
- Remove interrupt()
- listening variable is not needed
- put transport in STATE_ERROR
Bluetooth Transport Log before fix (toggling BT rapidly):
```
01-23 14:18:11.804 23088-23088/? D/Bluetooth Transport: 1 Socket Type Secure cancel 
01-23 14:18:11.805 23088-23131/? E/Bluetooth Transport: Socket Type: Secureaccept() failed
java.io.IOException: read failed, socket might closed or timeout, read ret: -1
at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:741)
at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java:700)
at android.bluetooth.BluetoothSocket.accept(BluetoothSocket.java:460)
at android.bluetooth.BluetoothServerSocket.accept(BluetoothServerSocket.java:158)
at …
```

Proposal 1 to fix Issue_373

---

sdl_android_lib/src/com/smartdevicelink/transport/MultiplexBluetoothTransport.java

-addresses cases where mmInStream is null
-aimed at #380 and #382 
-tested by running sample app on Gen 3 TDK and toggling Bluetooth on and off

Handling NULL mmInStream cases

---

sdl_android_lib/src/com/smartdevicelink/transport/MultiplexBluetoothTransport.java

Bugfix #384 
-Comment specifies it is only to catch mmOutStream NPE (don’t be lazy)
-Tested connecting to Gen 3 TDK w/ sample app

Catching NPE on mmOutStream

---

sdl_android_lib/src/com/smartdevicelink/transport/MultiplexTransport.java

-Bugfix for #385 
-Tested connecting/disconnecting via BT to Gen 3 TDK with sample app

Added 'synchronized' keyword to lock threadLooper object

---

build.gradle
sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterService.java

- To resolve issue #376 
- this may contribute to #378 
- We just stop the service if permission isn't there, any further handling will be done at a future time

Check for BT Permission in SdlRouterService.onCreate()

---

sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java

Reverts smartdevicelink/sdl_android#432
Documentation should be changed to have developers check if the proxy closed reason was  due to a language change and restart their proxy instead of removing this call.

Revert "Bugfix/issue 431"

---

sdl_android/src/androidTest/java/com/smartdevicelink/SdlConnection/SdlConnectionTest.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/streaming/AbstractPacketizerTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/streaming/StreamPacketizerTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/streaming/StreamRPCPacketizerTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/transport/MultiplexBluetoothTransportTest.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/util/DeviceUtil.java
sdl_android/src/androidTest/java/com/smartdevicelink/transport/TransportBrokerTest.java

Adds a DeviceUtil class with isEmulator() function to detect if running in emulator. Aspects like MultiplexBT and BT adapter checks will account for if an emulator is running the test. Changed FTP url in Packetizer tests that was failing in emulator.

Fixing the failing unit tests in Emulator

---

sdl_android/src/main/AndroidManifest.xml

Removed android:debuggable=“true” from Manifest

---

sdl_android/src/main/AndroidManifest.xml

This is causing build issues for developers so we have to issue a hotfix. See #540 and #546

hotfix/Remove android:debuggable=“true” from Manifest

---

sdl_android/src/androidTest/java/com/smartdevicelink/transport/SdlRouterServiceTests.java
sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexBluetoothTransport.java
sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

Fixes #554 
Refactor of `MultiplexBluetoothTransport` to no longer be a singleton. It also cleans up a little of the code in the same class. Changes were also made to the `SdlRouterService` to no longer keep a static reference to the transport class.

bugfix/554 - Refactor of MultiplexBluetoothTransport to no longer be a singleton.

---

sdl_android/src/androidTest/java/com/smartdevicelink/test/BaseRpcTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/proxy/RPCRequestFactoryTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/proxy/RPCRequestTest.java
sdl_android/src/main/java/com/smartdevicelink/proxy/RPCRequest.java

Fixes #604 
This was tested by removing manually set correlation IDs in a test app's proxy and ensuring that they were auto set correctly by the library
- In `RPCRequest.java`, edit `getCorrelationID()` and check for the key in the `RPCMessage`. If it was not set manually, then set it.

Auto set correlation ID

---

sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java

Fixes #587 
Smoke testing of the broadcast receiver was performed
Prevent the `defineLocalSdlRouterClass()` from being called if not needed 
- `SdlBroadcastReceiver.java`

Bugfix / Issue 587

---

sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java
sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java
sdl_android/src/main/java/com/smartdevicelink/util/ServiceFinder.java

Fixes [#602](https://github.com/smartdevicelink/sdl_android/issues/602)
- Check build version so that the fix also applies for devices with build version > Android O
- Set higher priority for registration broadcast to increase the chance of broadcast reception in ServiceFinder
- Code cleanup

Android O p2 fix improvements

---

sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java

Fixes #637
During creation of the internal video streaming manager, a check was added to ensure the module supports spatial data before creating the haptic manager. Subsequent calls to the haptic manager are surrounded with checks to see if the manager is null or not.

Only start haptic manager if feature is supported

---

sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java

Fixes #641 
Moves the system capabilities query for haptic manager into `StartVideoStreaming` so that it isn't null

bugfix / issue 641

---

sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java

Fixes #662 
This was tested on a FORD TDK and test app. 
There was logic to prevent HMI notifications when an HMI level or Audio Streaming State did not change. However, there is additional information in those notifications that the developer might want. That comparison logic was simply removed.

bugfix/issue 662 HMI status not updating

---

sdl_android/src/main/java/com/smartdevicelink/proxy/SystemCapabilityManager.java

Fixes #666 
No API's were changed. Ran unit tests.
Prevent `OnSystemCapabilityListener` from being called twice as noted by @shiniwat 
* no breaking changes

bugfix/issue_666 prevent OnSystemCapabilityListener from being called twice

---

sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java

Fixes #616 
This does not change behavior, simply prevents possible NPE 
Fix potential NPE in SDLProxyBase. Hashtables cannot take nulls like hash maps can.

bugfix/issue 616 fix NPE in proxy base 

---

sdl_android/src/androidTest/java/com/smartdevicelink/transport/SdlRouterServiceTests.java
sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

Fixes #660 
I added 2 tests to handle the 2 cases that might be presented. Using reflection, i create the rare instance where an app who just was cleaned up is beaten by an app registering using the same sessionId. In this case, we check out the sessionHash and if its different (meaning a different app, the UAI packet is dropped). The second test covers the condition where it is the same app and the UAI packet is let through.
This PR takes care of a rare race condition. When an app is removed and another app is connecting, there is a chance that the connecting app might be assigned the same session key as the app that was removed. If this happens, the unregister app interface can come back and remove the app that just …

Bugfix/issue 660 UAI Race condition logic

---

sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterStatusProvider.java

Fixes [issue 688](https://github.com/smartdevicelink/sdl_android/issues/688).
Manual testing, verify that library does not crash when flow is initiated from a background thread.
Attach the main looper when creating ClientHandler in SdlRouterStatusProvider

#688 Handle a RuntimeException crash

---

sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

Fixes #698 
1. Turn off bluetooth adapter on device
2. Change targetAPI to 25 or lower and deploy app
3. Turn on Bluetooth
4. Router service notification should be displayed
5a. If no connection is made, notification should disappear after 10 seconds. 
5b. If a connection is made, notification should remain and contain connected devices bluetooth name
1. Turn off bluetooth adapter on device
2. Change targetAPI to 26 or higher and deploy app
3. Turn on Bluetooth
4. Router service notification should not be displayed as the implicit intent is not received from the OS
A new handler and runnable were added to the router service that will be run 10 seconds after the service enters the foreground, or 20 seconds if A2DP is in the …

Handle router service foreground notification removal

---

sdl_android/src/androidTest/java/com/smartdevicelink/test/proxy/SdlProxyBaseTests.java
sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/listeners/OnMultipleRequestListener.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/listeners/OnRPCResponseListener.java

Fixes #606 
As testing this is challenging (requiring response from a core instance), the tests were mainly carried out against Manticore. Unit tests were added, but at this point cannot test full functionality as we cannot mock core. 
Added 2 public methods:
- sendSequentialRequests - Allows multiple RPCRequests to be sent in an ArrayList and guarantees that they are executed in order.
- sendRequests - Allows multiple RPCRequests to be send in an ArrayList with no guarantee for order.

Feature/issue 606 send multiple RPCS

---

sdl_android/src/androidTest/java/com/smartdevicelink/transport/SdlRouterServiceTests.java
sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

Fixes #687 
Tested new method on TDK using a local versions of Hello Sdl Android to make sure nothing bad happened. Tested on `targetSdkVersion`'s of 25 and 26
- Some broadcast intents in the `SdlRouterService` were being sent implicitly, while android O+ requires them to be sent explicitly. Created a new private method to do just that and modified the broadcasts which need it to use the new method.
- Removed an unnecessary unregister intent in `onTransportDisconnected` in which a broadcast was sent out when there were no registered apps.

Bugfix/issue 687 - send intents explicitly

---

sdl_android/src/main/java/com/smartdevicelink/transport/RouterServiceValidator.java
sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java
sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java
sdl_android/src/main/java/com/smartdevicelink/transport/USBAccessoryAttachmentActivity.java
sdl_android/src/main/java/com/smartdevicelink/transport/USBTransport.java
sdl_android/src/main/java/com/smartdevicelink/util/AndroidTools.java
sdl_android/src/main/res/xml/accessory_filter.xml

Default USB testing plan will work for this PR
* Added the `accessory_filter.xml` to the res values
* Fixed direct call to `onTransportError`
* Prevent proxy cycle from happening if USB has been disconnected
* Fixed javadoc
* Fixed USB connection intent from being implicit
* Refactored explicit broadcast method to AndroidTools
* Fix RSV implicit broadcast

Minor Usb transport improvements and explicit broadcast refactor

---

sdl_android/src/main/java/com/smartdevicelink/transport/BTTransport.java

Fixes #480
-/-
switched BTTransport.disconnect from snychronized method to synchronized code block
* fixed deadlock when exception occurs in BTTransport.disconnect
- [X ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

#480 fixed deadlock when exception is thrown in BTTransport.disconnect

---

sdl_android/build.gradle
sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android/src/main/java/com/smartdevicelink/proxy/Version.java

- Add log line in SdlProxyBase.performCommon()
- Add line in gradle file to generate xml file that has library version string
Fixes [#703](https://github.com/smartdevicelink/sdl_android/issues/703)
Connect with head unit and verify library version is logged.
Verify that xml file is generated with library version string.

#703 Logging library version

---

sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java

Fixes #706 & #708
Instead of requiring type of strictly `RPCRequest`, list param was changed to `? extends RPCRequest` type.
Also adds check for null around listener for same methods.

Fixes #706 & #708

---

sdl_android/src/main/java/com/smartdevicelink/transport/TransportBroker.java

1. Install more than 1 SDL app.
2. Connect BT
3. Kill the app that has started the Router Service 
4. Wait
5. Router service will be started again and hardware will eventually reconnect
Added a call to `SdlBroadcastReceiver.queryForConnectedService` if the `TransportBroker` was unable to bind to the Router Service. Likely because the service itself is not running.

Add more recoverability to TransportBroker

---

sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/RegisterAppInterfaceResponse.java

This was tested against a Ford TDK
There are some rare occurrences where the stored `speechCapability` object is a not a list, and it is supposed to be. We check to see if the response is a list, and if not, that its an instance of `SpeechCapabilities` and return a list with that as its only object. If neither of these happen we return null as something went wrong.

added list check to speechcapabilities

---

sdl_android/src/main/java/com/smartdevicelink/util/ServiceFinder.java

1. Install more than 1 SDL app.
2. Connect BT
3. Kill the app that has started the Router Service
4. Wait
5. Router service will be started again and hardware will eventually reconnect
6. Repeat test a few times
* Put the handler inside the `ServiceFinder` class on the main looper to avoid the runnable not being posted

Put timeoutHandler for ServiceFinder on MainLooper so it doesn’t fail

---

sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java

Fixes #742 
Tested successfully on branch 
https://github.com/smartdevicelink/sdl_android/compare/develop...feature/mt_multiplexing
with situation described in issue - Router Service running with USB transport, then BT is toggled from OFF to ON. Can look into unit tests if necessary.
* Fixes bug described in issue.
- [ X ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

Pinging all running BT services on wake up

---

sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

Fixes #778 
No testing is required for this PR
This PR makes the router service notification clickable. When the user clicks on it, a webpage that has info about the SDL notifications opens.

Feature/issue 778  - Create a webpage to explain why SDL notification pops up

---

sdl_android/src/main/java/com/smartdevicelink/transport/BTTransport.java
sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexBluetoothTransport.java

Fixes #765 
1. Install Android P on device
2. Use Legacy Bluetooth
3. Connection should be successful
Deprecating methods that used reflection on Android SDK classes that are non-SDK interfaces.
* Ignores an "invalid" channel number if the android build version is greater than Android Oreo (v26)

Fixes #765 - Remove reflection dependency on Android SDK classes

---

sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java

Fixes #785  
1. Set the transport type to `MULTIPLEX`
2. Make sure that `com.smartdevicelink.router.service` action is added to the router service's intent-filter
2. Pair the device with TDK
3. Run the app and check logcat messages
4. You should see no warnings about intent-filter in logcat
This PR fixes an issue in the way the library is checking whether the router service has the intent-filter declared correctly in AndroidManifest. The previous way was having a bug where the `filter` is always `null`.

Feature/issue 785 - SdlBroadcastReceiver throws false positive warnings

---

sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java

Fixes #787 
1. Prepare a VPM app and connect to Core
2. Use a single touch to press down, move and release. Correction Action items received
3. Touch one pointer; receive an ACTION_DOWN, touch another pointer without release first; receive an ACTION_POINTER_DOWN. Release one of the pointers; ACTION_POINTER_UP is received. Release the other pointer; ACTION_UP is received.
A private static class was introduced to handle the translation of SDL touch events to Android motion events. 
* Multitouch is now better supported
* ACTION_CANCEL should not be received between multiple pointer touch begins

Fix vpm multi touch

---

sdl_android/src/main/java/com/smartdevicelink/proxy/RPCRequestFactory.java
sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java

Fixes #792 
- Deprecate `RPCRequestFactory` class as described in the proposal.
- Replace all calls to `RPCRequestFactory` factory methods in the library with RPC constructor calls.

Feature/Deprecate RPCRequestFactory class

---

sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexBluetoothTransport.java
sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java
sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

1. Clear testing app memory or reinstall it from device
2. Connect bluetooth to device (TDK, bluetooth headset)
3. First time should have a timeout of 10 milliseconds
4. Disconnect device
5. Reconnect device
1.  If device previously connected through SDL the timeout should be upped to 20 seconds. 
2. If device did not connect through SDL, timeout should be 10ms.
Add better logic to create an even less intrusive notifications for end users. If a device is found to have not connected through SDL, the timeout will decrease significantly (10ms) and the notification will essentially not be displayed.
* Less intrusive notifications for end users
* Notification while waiting for a connection is now swipeable

Even less intrusive notification

---

sdl_android/src/androidTest/assets/json/GetVehicleData.json
sdl_android/src/androidTest/assets/json/SubscribeVehicleData.json
sdl_android/src/androidTest/assets/json/UnsubscribeVehicleData.json
sdl_android/src/androidTest/java/com/smartdevicelink/test/Test.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/Validator.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/VehicleDataHelper.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/FuelRangeTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/FuelTypeTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/VehicleDataTypeTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/notifications/OnVehicleDataTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/requests/GetVehicleDataTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/requests/SubscribeVehicleDataTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/requests/UnsubscribeVehicleDataTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/responses/GetVehicleDataResponseTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/responses/SubscribeVehicleDataResponseTest.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/responses/UnsubscribeVehicleDataResponseTest.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/FuelRange.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/GetVehicleData.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/GetVehicleDataResponse.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/OnVehicleData.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/SubscribeVehicleData.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/SubscribeVehicleDataResponse.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/UnsubscribeVehicleData.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/UnsubscribeVehicleDataResponse.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/FuelType.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/VehicleDataType.java

Fixes #552 
Added new unit tests and expanded existing ones
Added Vehicle Data RPC's, structs, enums as defined in the fuel range proposal.

Feature/issue 552 - New vehicle data - FuelRange

---

sdl_android/src/androidTest/java/com/smartdevicelink/test/proxy/SdlProxyBaseTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/notifications/OnRCStatusTests.java
sdl_android/src/main/java/com/smartdevicelink/protocol/enums/FunctionID.java
sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android/src/main/java/com/smartdevicelink/proxy/interfaces/IProxyListenerBase.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/OnRCStatus.java

Fixes #657, #783 
Added new unit tests and expanded existing ones
Added RPC's, structs, enums as defined in the Remote Control OnRCStatus notification proposal.

Feature/issue 657, 783 - Remote Control - OnRCStatus notification

---

sdl_android/build.gradle
sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java

Fixes #833 
Tested against Ford TDK to ensure no `IllegalStateExceptions` on apps targeting O or above
If O or above, call `startForegroundService` in the `pingRouterService` method

fix IllegalStateException starting service

---

sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/RegisterAppInterfaceResponse.java

Fixes #453 
This is a follow up commit on the revision of the proposal. It simply sets the `iconResumed` value to false if it is not set.

App Icon Resumption Revision

---

sdl_android/src/androidTest/java/com/smartdevicelink/api/SdlManagerTests.java
sdl_android/src/main/java/com/smartdevicelink/api/ManagerListener.java
sdl_android/src/main/java/com/smartdevicelink/api/SdlManager.java
sdl_android/src/main/java/com/smartdevicelink/api/SdlManagerListener.java

-SdlManager now takes in a ManagerListener with callbacks for start up and destroy
-Destroy callback is called in dispose() method
-Gives a way for SdlManager to “restart”
-Adds HMI listener methods to let developer know when to start video or audio stream

Add ManagerListener with way to notify of disposal

---

sdl_android/build.gradle
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/notifications/OnHMIStatusTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/streaming/MockPacketizer.java
sdl_android/src/main/java/com/smartdevicelink/marshal/JsonRPCMarshaller.java
sdl_android/src/main/java/com/smartdevicelink/proxy/RPCStruct.java
sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/OnHMIStatus.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/RegisterAppInterfaceResponse.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/SdlMsgVersion.java
sdl_android/src/main/java/com/smartdevicelink/streaming/AbstractPacketizer.java
sdl_android/src/main/java/com/smartdevicelink/streaming/StreamRPCPacketizer.java
sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java
sdl_android/src/main/java/com/smartdevicelink/util/Version.java

RPC Struct now has a format method that can be used to properly format RPCs based on the rpc spec version

Add ability for RPCs to be versioned/formatted

---

sdl_android/src/androidTest/assets/json/RegisterAppInterface.json
sdl_android/src/androidTest/java/com/smartdevicelink/test/Test.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/requests/RegisterAppInterfaceTests.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/RegisterAppInterface.java

Fixes #738 
* Updated the current unit tests to work with the new `fullAppID` field in `RegisterAppInterface`.
This PR adds a new `fullAppID` parameter to `RegisterAppInterface` RPC as described in the proposal.

Feature/issue 738 - Support for Short and Full UUID App ID

---

sdl_android/src/androidTest/java/com/smartdevicelink/test/util/DeviceUtil.java

Fixes #854 
1. Create a new Android Emulator
2. Run `com.smartdevicelink.SdlConnection.SdlConnectionTest` on the emulator
3. All tests should pass
Fixed an issue in `isEmulator()` method where it returns false on new emulators while it is supposed to return `true`

Issue 854 - Fix an issue in isEmulator

---

sdl_android/src/main/java/com/smartdevicelink/api/SdlManager.java

This PR adds `addOnRPCNotificationListener` to `SdlManager` so developers can register to receive specific notifications. For example when the HMI level changes or when `OnVehicleData` update is received.

Add addOnRPCNotificationListener method to SdlManager

---

sdl_android/src/main/java/com/smartdevicelink/api/SdlManager.java
sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android/src/main/java/com/smartdevicelink/security/SdlSecurityBase.java

Because `_proxyListener` is no longer an instance of `Service` after adding the managers layer, the method `sendBroadcastIntent` in `SdlProxyBase` is always returning without actually sending a broadcast:
https://github.com/smartdevicelink/sdl_android/blob/42ef06bb9a212371abf778a8f6d4f5ba255a98a0/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java#L896
Also the `getService()` method will always return `null` for the same reason:
https://github.com/smartdevicelink/sdl_android/blob/42ef06bb9a212371abf778a8f6d4f5ba255a98a0/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java#L867
* Pass context from`SdlManager` to `SdlProxyBase` to use it directly to send broadcast instead of getting the …

Feature/issue 782 - Fix broadcast issue in SdlProxyBase

---

sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/ButtonNameTests.java
sdl_android/src/main/java/com/smartdevicelink/proxy/RPCRequest.java
sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/RegisterAppInterfaceResponse.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/ButtonName.java

Fixes #229 
- Updated unit tests.
- Test with develop branch of Core
- Test with older systems using new enums
Added the PLAY_PLAUSE enum value. There was also javadoc added to clarify the situation until the next major release.  Essentially both OK and PLAY_PAUSE will receive the events when one comes in from core for this release. In the next major release this will be sorted out with less confusion.
Developer API |Version & Direction | Core
---------------|----------------------|------------
Received               |<~~~~~~~| Sent
Drop           |< 5                   | PLAY_PAUSE
PP & OK        |>= 5                  | PLAY_PAUSE
OK & PP  |< 5                   | OK
OK & PP      |>= 5                  | OK
Sent …

Add PLAY_PAUSE enum value

---

sdl_android/src/main/java/com/smartdevicelink/streaming/video/VideoStreamingParameters.java

Fix issue-882: maxBitrate in VIDEO_STREAMING capability is misread
Fixes #882 
N/A
Fix the VideoStreamingParamters to handle maxBitrate correctly.
N/A
N/A
#882 
None

Fix issue-882: maxBitrate in VIDEO_STREAMING capability is misread

---

sdl_android/src/main/java/com/smartdevicelink/util/AndroidTools.java

Fix issue-884: sdl.router.startservice broadcast was sent twice unexpectedly
Fixes #884 
N/A
sendExplicitBroadcast unexpectedly sent broadcast twice if the given apps param was null.
* N/A
* N/A
* #884 
- N/A

Fix issue-884: sdl.router.startservice broadcast was sent twice unexpectedly

---

hello_sdl_android/src/main/AndroidManifest.xml
sdl_android/build.gradle
sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/LockScreenManager.java

- fix lock screen showing up when DD_ON notification is received when application is backgrounded
- fix activity stack order for when lock screen should be shown when foregrounded
- clean up code

add lifecycle listeners

---

sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexTransportConfig.java
sdl_android/src/main/java/com/smartdevicelink/transport/RouterServiceValidator.java
sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java
sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java
sdl_android/src/main/java/com/smartdevicelink/transport/TransportConstants.java
sdl_android/src/main/java/com/smartdevicelink/transport/TransportManager.java
sdl_android/src/main/java/com/smartdevicelink/transport/USBAccessoryAttachmentActivity.java
sdl_android/src/main/java/com/smartdevicelink/transport/USBTransportConfig.java

1. Install app that uses legacy USB transport and does not have router service declared. Plug in USB, ensure app connects
2. Install second app that has router service declared. Plug in USB, ensure both apps connect.
3. Change second app's router service version to less than 8. Plug in USB, only the first app should show.
Introduced a new scheme to handle the legacy bluetooth connection scenario. It will also ensure that if a router service is available to host a USB connection it is used and the originating app can handle the USB connection (through multiplexing) still.

Fix issue with legacy USB connections

---

sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/AddSubMenu.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/DisplayCapabilities.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/GetVehicleData.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/OnHMIStatus.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/OnSystemRequest.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/OnVehicleData.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/RGBColor.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/RegisterAppInterface.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/SetDisplayLayout.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/SetMediaClockTimer.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/SingleTireStatus.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/SubscribeVehicleData.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/SystemRequest.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/TemplateColorScheme.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/UnsubscribeVehicleData.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/VideoStreamingCapability.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/AudioStreamingIndicator.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/ImageFieldName.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/RequestType.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/TPMS.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/TurnSignal.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/VideoStreamingState.java
sdl_android/src/main/java/com/smartdevicelink/util/AndroidTools.java

Only documentation was updated
- JavaDocs updated to reflect 5.0 spec version instead of 4.6
- Also fix a few minor missing or misleading doc entries

Fix javadocs rpc version

---

sdl_android/src/main/java/com/smartdevicelink/managers/screen/ScreenManager.java

This PR removes the `setDisplayLayout` method from `ScreenManager` to align with iOS and allow the developer to attach a listener to the RPC request.

Remove ScreenManager setDisplayLayout

---

sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java

Fixes #908
This PR fixes an issue in `SdlProxyBase.getService()`. It was always returning null if the new managers' layer is used.

Fix null issue in getService()

---

hello_sdl_android/src/main/java/com/sdl/hellosdlandroid/SdlService.java
sdl_android/src/androidTest/java/com/smartdevicelink/managers/SdlManagerTests.java
sdl_android/src/main/java/com/smartdevicelink/managers/SdlManager.java

Remove unnecessary SdlException throw in SdlManager

Remove incorrect SdlException throw in SdlManager

---

.github/PULL_REQUEST_TEMPLATE.md

Fixes #913 
Added SDL GitHub Best Practices link and review request information to pull_request_template.md, per issue #913 .

add best practices link and review info to PR template

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
sdl_android/build.gradle
sdl_android/src/main/java/com/smartdevicelink/protocol/SdlPacket.java
sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java
sdl_android/src/main/java/com/smartdevicelink/transport/TransportBroker.java

Fixes #925
- Create an app  (App A) with library version 4.6.3 or lower
- Create second app (App B) with library version 4.7.0 or newer, but do not include router service
- Ensure that App B connects to App A
Hotfix is to enable apps to connect to legacy router services. While the scenario should never happen, some OEMs have implemented companion apps that will take a while to implement new versions of the library therefore the library should be able to handle that situation.
- Addressed issue in TransportBroker that caused previous router service's connection messages to be dropped. Add logic to check router service version and perform appropriate logic.
- Added check if packet doesn't include a transport record
- Fixed a …

Hotfix 4.7.2

---

sdl_android/src/main/java/com/smartdevicelink/managers/SdlManager.java
sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java

Fixes #928 
This PR makes ** minor** API changes.
- Connect with Core
- Use new method to retrieve register app interface
- Moved the `SdlManager.Builder` class to end of file
- Added public method to retrieve the RegisterAppInterface Response in it's entirety.
* Developers should have access to all information that comes back through the RAI response similar to the iOS library.

Expose RAI response and move SdlManager.Builder

---

sdl_android/src/main/java/com/smartdevicelink/managers/file/filetypes/SdlArtwork.java
sdl_android/src/main/java/com/smartdevicelink/managers/screen/SoftButtonState.java
sdl_android/src/main/java/com/smartdevicelink/managers/screen/TextAndGraphicManager.java

Fixes #916 
This PR adds a public method in `SdlArtwork` to set the `isTemplate` value. It also modifies `ScreenManager` to load the `isTemplate` value from `SdlArtwork` and set it in the corresponding `com.smartdevicelink.proxy.rpc.Image` instance before using the image.

Add support for Template Images in ScreenManager

---

sdl_android/src/androidTest/java/com/smartdevicelink/transport/SdlRouterServiceTests.java
sdl_android/src/main/java/com/smartdevicelink/protocol/SdlPacketFactory.java
sdl_android/src/main/java/com/smartdevicelink/protocol/SdlProtocol.java
sdl_android/src/main/java/com/smartdevicelink/protocol/WiProProtocol.java
sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

Fixes https://github.com/smartdevicelink/sdl_android/issues/943
- Repeat the repro steps mentioned in https://github.com/smartdevicelink/sdl_android/issues/943
- Run the newly added unit tests.
This PR updates SdlRouterService to generate an End Session frame with BSON document for protocol version >= 5.
* None
* None
* fix: Router service doesn't support HashID for V5 protocol
- None

fix: Router service doesn't support HashID for V5 protocol

---

sdl_android/src/main/java/com/smartdevicelink/managers/screen/TextAndGraphicManager.java

Fixes #930 
When the app developer uses screen manager and updates soft buttons only. the completion handler will never be called. Fixed by immediately calling completion handler.

ScreenManager does not call completion listener if TextAndGraphicManager is not dirty

---

sdl_android/src/main/java/com/smartdevicelink/managers/audio/AudioStreamManager.java

Fixes #963 
Run a test navigation app that uses audio streaming on Core and Generic HMI and make sure it doesn't crash.
When the audio service is ended, `sdlAudioStream` gets set to `null`. However, the `sdlAudioStream` may still be used to send data in `onAudioDataAvailable` which causes an NPE.

Fix NPE in AudioStreamManager

---

sdl_android/src/main/java/com/smartdevicelink/managers/screen/TextAndGraphicManager.java

Fixes #948 
Currently, in the `TextAndGraphicManager` if the head unit responded with an error for the sending a `Show` request, the `inProgressUpdate` will not be set to `null`. We only set it to `null` when a successful response comes back as shown in the following line:
https://github.com/smartdevicelink/sdl_android/blob/490be41b20ec4bb4a81837e73eb6ea9bfcea7a8a/sdl_android/src/main/java/com/smartdevicelink/managers/screen/TextAndGraphicManager.java#L255
However, if the `inProgressUpdate` is not set to `null`, all subsequent `TextAndGraphicManager` updates will hit this if:
https://github.com/smartdevicelink/sdl_android/blob/490be41b20ec4bb4a81837e73eb6ea9bfcea7a8a/sdl_android/src/main/java/com/smartdevicelink/managers/sc …

Handle onError in TextAndGraphicManager

---

sdl_android/src/main/java/com/smartdevicelink/proxy/SystemCapabilityManager.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/SystemCapabilityType.java

Fixes #965 
This PR modifies `SystemCapabilityManager` to make it query only for queryable capabilities  
* Add `isQueryable` boolean to `SystemCapabilityType` enum
* Update `SystemCapabilityManager.retrieveCapability()` to query only for for queryable capabilities  
- [ x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

Make SystemCapabilityManager query only for queryable capabilities

---

sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/ScreenManagerTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/TextAndGraphicManagerTests.java
sdl_android/src/main/java/com/smartdevicelink/managers/screen/TextAndGraphicManager.java

Fixes #942 
Test cases added to the `ScreenManagerTests` and `TextAndGraphicManagerTests` classes.
The blank artwork object was never created due to a bug where the blank artwork could only be created if it was already not `null`. 
* Developers can now successfully clear a primary or secondary graphic when using the screen manager.

Fixed the screen manager not being able to clear images

---

sdl_android/src/main/java/com/smartdevicelink/protocol/SdlProtocol.java
sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java
sdl_android/src/main/java/com/smartdevicelink/transport/UsbTransferProvider.java
sdl_android/src/main/java/com/smartdevicelink/util/AndroidTools.java

Fixes #924 
- Plug the usb cable
- Unpulg the cable
- Plug the cable again
- Keep doing the previous steps and make sure that the app doesn't reach an unreceverable state 
This PR attempts to fix more USB cable disconnecting issues by doing the following:
- Check to see if the USB cable is physically connected before opening the USB accessory and starting the usb transport
- Handle disconnecting logic when the disconnect happens before `StartSessionACK` is received. Previoulsy   it was not hitting this condition if the ack was not received: https://github.com/smartdevicelink/sdl_android/blob/490be41b20ec4bb4a81837e73eb6ea9bfcea7a8a/sdl_android/src/main/java/com/smartdevicelink/protocol/SdlProtocol.java#L1153

More usb enhancements 

---

sdl_android/src/androidTest/java/com/smartdevicelink/managers/file/FileManagerTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/SoftButtonManagerTests.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/Validator.java
sdl_android/src/main/java/com/smartdevicelink/managers/file/FileManager.java
sdl_android/src/main/java/com/smartdevicelink/managers/file/filetypes/SdlArtwork.java
sdl_android/src/main/java/com/smartdevicelink/managers/file/filetypes/SdlFile.java
sdl_android/src/main/java/com/smartdevicelink/managers/screen/SoftButtonManager.java
sdl_android/src/main/java/com/smartdevicelink/managers/screen/SoftButtonState.java
sdl_android/src/main/java/com/smartdevicelink/managers/screen/TextAndGraphicManager.java

Fixes #848 
Unit tests were modified to test static icons additions. 
This PR adds support for static icons to SdlArtwork and managers as described in the proposal.

SDL 0196 - Add Support for Static Icons to SDLArtwork

---

sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/StartTimeTest.java
sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/requests/SetMediaClockTimerTests.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/SetMediaClockTimer.java
sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/StartTime.java

Fixes #856 
Unit tests are added to make sure that the values are set correctly in the Initializers
This PR implements the updated SetMediaClockTimer Initializers to match the ones in iOS

SDL 0197 - Update SetMediaClockTimer Initializers

---

hello_sdl_android/src/main/AndroidManifest.xml
sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexUsbTransport.java
sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java
sdl_android/src/main/java/com/smartdevicelink/transport/TransportBroker.java
sdl_android/src/main/java/com/smartdevicelink/transport/USBAccessoryAttachmentActivity.java
sdl_android/src/main/java/com/smartdevicelink/transport/UsbTransferProvider.java
sdl_android/src/main/res/values/sdl.xml

(Attempting to) Fixes #924 
For the most effective testing a few items should be noted
1. Should be tested on a variety of devices and OS levels as this issue has different behavior between them
2. One app should be installed (included hello sdl app) that is chosen to accept the USB attachment intent. A second app should be installed that does not have the USB attachment activity in its manifest and it's SdlRouterService version upped past the hello sdl's version so that it can be guaranteed the second app is hosting the router service.
- Made the USB read buffer the max AOA size
- Refactored some items for optimization
- ~Moved the sampel app's UsbAttatchementAcitity into the SdlRouterService process~
- An easier fix was …

usb enhacements

---

sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java

Fixes #975 
- Test with any sdl app that has a RouterService
- Use the default SdlRouterService class in`SdlReceiver.defineLocalSdlRouterClass` and confirm that you see this message in the logs
```
Can't use default SdlRouterService class, must be extended in your project
```
- Use the app's SdlRouterService class in`SdlReceiver.defineLocalSdlRouterClass` and confirm that the previous error message is not logged 
This PR logs a warning message if the developer used the default SdlRouterService class in `SdlReceiver.defineLocalSdlRouterClass` instead of using the app's SdlRouterService class

Show warning if default SdlRouterService class is used in SdlReceiver

---

javaEE/bintray.gradle
javaEE/bintray.properties
javaEE/build.gradle
javaSE/bintray.gradle
javaSE/bintray.properties
javaSE/build.gradle

Update bintray.properties file then try to run `gradle bintrayUpload` for javaSE and javaEE and make sure it actually uploads to bintray.
This PR adds bintray support to javaSE and javaEE in a way that is similar to how it works for Android.

Add bintray upload support to javaSE & java EE

---

javaSE/src/main/java/com/smartdevicelink/managers/SdlManager.java
javaSE/src/main/java/com/smartdevicelink/managers/lifecycle/LifecycleManager.java

Block old SDL head units from connecting to cloud apps

Block Old SDL Head Units from Cloud apps

---

android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
base/src/main/java/com/smartdevicelink/managers/screen/BaseScreenManager.java
base/src/main/java/com/smartdevicelink/proxy/SystemCapabilityManager.java
javaSE/src/main/java/com/smartdevicelink/managers/SdlManager.java
javaSE/src/main/java/com/smartdevicelink/managers/lifecycle/LifecycleManager.java
javaSE/src/main/java/hello_sdl/Main.java

- JAVA: Add ability to listen for requests
- JAVA: allow sending of notifications and responses
- ANDROID: hook up `addOnRPCListener` and `removeOnRPCListener` in proxy base
- ANDROID: remove direct call to SCM from `sendDisplayLayoutResponse` in proxy base

Cloud RPC Request Listeners

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/requests/UnsubscribeVehicleDataTests.java
base/src/main/java/com/smartdevicelink/proxy/rpc/UnsubscribeVehicleData.java

Fixes #1026 
Fix the `UnsubscribeVehicleData.setCloudAppVehicleID()` method signature as described in the issue

Fix the UnsubscribeVehicleData.setCloudAppVehicleID() method 

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

Fixes #932 (again...hopefully for good)
Two tests are really needed to ensure everything works properly.
1. Delete all SDL enabled apps from device
2. Install Ford Alexa app, connect to tdk, Alexa shows and hosts router service
3. Install Hello Sdl app, app also shows on tdk
4. Turn off tdk, Hello SDL app notification should be removed.
1. Install WebEx and Acast App from Play Store
2. Install Hello SDL App from Tag RC2 or use attached APK.
3. Connect Android device to SYNC
4. Wait for all Apps to show up on SYNC. Observe notifications on Android device. All 3 apps will show notifications.
5. Disable Bluetooth on Ford SYNC. Alternatively, perform Ignition Cycle
4. Turn off tdk, Hello SDL app notification should be removed. …

Fix issue in RS when removing Parcel objects for notifying all cliets

---

javaEE/build.gradle
javaSE/build.gradle

~1 - Remove `BuildConfig.java` file from sdl_android/javaSE/src/main/java/com/smartdevicelink~
2 - Change lib version in `VERSION` file
3 - Run `gradle build` and make sure the jar is generated correctly and that `versionName` is correct in `BuildConfig` file in the jar
4 - Change lib version again in `VERSION` file
5 - Run `gradle bintrayUpload` and make sure the lib is uploaded to bintray and that `versionName` is correct in `BuildConfig` in the uploaded lib
6 - Repeat steps (1 -> 5) for javaEE library
This PR fixes some issues in `generateSources` gradle task
* Add the new task to javaEE
* Set the `upToDateWhen` to `false` to prevent the task from beeing skipped

Fix issues in updating BuildConfig

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/proxy/SystemCapabilityManagerTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/AppServicesCapabilitiesTests.java
base/src/main/java/com/smartdevicelink/proxy/SystemCapabilityManager.java
base/src/main/java/com/smartdevicelink/proxy/rpc/AppServicesCapabilities.java

- New unit tests added
- A publisher should publish a service, ensure it gets added to the SCM. Have the publisher's service removed and check the SCM that it removed the entry.
- Add a check to the `AppServiceCapabilities.updateAppServices` for update reason
- Refactor the method as well for simpler code path.

Handle AppService Removed reason in SCM

---

base/src/main/java/com/smartdevicelink/managers/screen/BaseTextAndGraphicManager.java

Fixes #1035
Smoke tests
In the `sdlUpdate` function, there is a line that tells the manager that there is a queuedUpdate ready, if the manager is in the process of completing an update:
```java
//Updating Text and Graphics
if (inProgressUpdate != null){
//In progress update exists, queueing update
if (queuedUpdateListener != null){
//Queued update already exists, superseding previous queued update
queuedUpdateListener.onComplete(false);
queuedUpdateListener = null;
}
if (listener != null){
queuedUpdateListener = listener;
}else{
hasQueuedUpdate = true; // <- here
}
return;
}
```
However, if an update is sent with a listener, and a subsequent update is not, that second update will never tell the manager that there is a …

make sure hasQueuedUpdate gets set

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/TransportBroker.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/TransportManager.java

1. Install an app with 4.7.x
2. Install an app with 4.8RC, but remove manifest declaration for RS
3. Connect to module
4. Disconnect form module via Ignition Cycle
There is an issue in the first gen of multi transport router services that will remove certain extras from messages to the TransportBroker if older apps are connected that do not support the multi transport messages. Because of that, we check the records we have and if the transport matches we assume it was the original transport that was received regardless of the address.

Handle corner case during transport d/c

---

android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
javaSE/src/main/java/com/smartdevicelink/managers/lifecycle/LifecycleManager.java

Fixes #1037
This PR is **Ready** for review.
This PR makes **no** API changes
This PR fixes the issue where app receives only `OK` button press notification after subscribing and pressing the `PLAY_PAUSE` button. It also adds `PLAY_PAUSE` button handling to javaSE.
- Add a listener for `OnButtonPress`
- Send a `SubscribeButton` request with button name set to `PLAY_PAUSE`
- Run the app
- Press the OK/PLAY_PAUSE button on the head unit
- Confirm that the app receives `OnButtonPress` notifications for both OK & PLAY_PAUSE 
- Repeat the test for the javaSE library

Fix issue in PLAY_PAUSE button handling 

---

javaSE/src/main/java/com/smartdevicelink/managers/file/filetypes/SdlArtwork.java
javaSE/src/main/java/com/smartdevicelink/managers/file/filetypes/SdlFile.java

This PR removes the `SdlFile` constructor that takes resourceId as a param because `resourceId` works only for android, not pure java.

Remove unnecessary SdlFile constructor in javaSE

---

android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/TransportManager.java
base/src/main/java/com/smartdevicelink/proxy/rpc/DisplayCapabilities.java
base/src/main/java/com/smartdevicelink/proxy/rpc/SoftButtonCapabilities.java

Fixes #1051 
* See Bug Fixes
* Fixed issue in TransportManager that had unreachable code by overriding the previous method of receiving Legacy mode notifications
* Fix issue where the RAI was being sent with max version of RPC sepc the lib could handle, but modules will only accept 1.0.0
* Added format method calls to two RPCs that have mandatory parameters but v1.0 of the RPC spec didn't have the params

Handle origin modules (Rpc Version 1.0 & Protocol Version 1.0)

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/SdlManagerTests.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/SdlManager.java
javaSE/src/main/java/com/smartdevicelink/managers/SdlManager.java

Fixes #1052 
A test case has been added to check the state. Also, this test can be run to confirm: 
1. Connect sdl app to Core
2. Check `SdlManager` state (should be READY)
3. Disconnect from Core
4. Check `SdlManager` state (should be SHUTDOWN)
This PR transitions the state of the `SdlManager` to `SHUTDOWN` once `SdlManager.dispose()` is called. It also transitions the manager state to `ERROR` when an error happens.

Update SdlManager state when dispose() is called 

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/TireStatusTest.java
base/src/main/java/com/smartdevicelink/proxy/rpc/TireStatus.java

Fixes #1057 
I tested this fix with Manticore's vehicle data notifications and was able to receive the correct values
Fix the `pressureTelltale` key in the `TireStatus` struct that was incorrect and did not match the RPC specs.

Fix Pressure Tell Tale

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/SdlManagerTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/proxy/SdlProxyBaseTests.java
android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
base/src/main/java/com/smartdevicelink/proxy/rpc/listeners/OnMultipleRequestListener.java
javaSE/src/main/java/com/smartdevicelink/managers/lifecycle/LifecycleManager.java

Fixes #1061
This PR fixes some issue in `sendRPCs` and `sendSequentialRPCs` methods:
- Calls the `onResponse/onError` for every RPC's `OnRPCResponseListener` 
- Calls the `onResponse/onError` in the `OnMultipleRequestListener` for every RPC 
- Continue sending RPCs if one failed
- `onUpdate` in `OnMultipleRequestListener`  is called for every RPC incuding the failed ones 
- Create a list of RPCs that you want to send and make sure one of them at least fails. The one that fails should not be the last one.
- Set an `OnRPCResponseListener` listener for all RPCs
- Send the RPCs using `sendSequentialRPCs`
- Make sure that `onResponse/onError` is called for every RPC in both the RPC's `OnRPCResponseListener` and the …

Fix issues in sendRPCs and sendSequentialRPCs

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/TransportManager.java

Fixes #1064
- Added a check to ensure that the TransportBroker instance actually started correctly. If it fails, close out the transport manager. 
* Handle case with older library using AOA connection that starts up newer apps.

Close library when unable to connect to router service

---

README.md
android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/video/VideoStreamManagerTests.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/video/VideoStreamManager.java
android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java

Fixes #972 and it is based on #973 
Unit tests will be added to test converting one `OnTouchEvent` that has multiple `TouchEvents` to multiple `MotionEvents`
-  Update `VideoStreamManager` to be able to convert one Sdl `OnTouchEvent` to multiple Android `MotionEvents`
-  Update `SdlProxyBase` to be able to convert one Sdl `OnTouchEvent` to multiple Android `MotionEvents`
- Pass list of all active pointers to `MotionEvent` so the developer can later get the correct number of active pointers from the `MotionEvent` and the coordinates for each pointer
- Update the converted `MotionEvent` actions to exactly match the native Android ones. For example, if the user touches the screen using two fingers at the same time, the action …

Add support for handling multiple TouchEvents in one OnTouchEvent notification 

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/BeltStatusTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/notifications/OnVehicleDataTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/responses/GetVehicleDataResponseTests.java
base/src/main/java/com/smartdevicelink/proxy/rpc/BeltStatus.java

Fixes #1078 
- Send `GetVehicleData` request and set `getVehicleData.setBeltStatus(true)`
- Check the `LeftRearInflatableBelted` in the reponse and make sure the value is correct and it is not `null`
This PR updates the `LeftRearInflatableBelted` key value in `BetlStatus` to match RPC Specs. Also, unit tests are updated accordingly.

Update LeftRearInflatableBelted key to match RPC Specs 

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/audio/AudioStreamManagerTest.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/audio/AudioStreamManager.java
android/sdl_android/src/main/java/com/smartdevicelink/streaming/StreamPacketizer.java
base/src/main/java/com/smartdevicelink/proxy/interfaces/IAudioStreamListener.java
base/src/main/java/com/smartdevicelink/streaming/StreamPacketizer.java
hello_sdl_java/src/main/java/com/smartdevicelink/java/SdlService.java

Fixes #1075 #1042 
Unit tests are updated. Also, smoke tests can be run to confirm that the new  `pushBuffer()` API works:
- Prepare raw audio `ByteBuffer`. For example, you can load a .raw audio file and convert its content to `ByteBuffer`
- Pass the `ByteBuffer` to `AudioStreamManager.pushBuffer()` and confirm that audio plays on HU and that `completetionListener` is called 
This PR adds a new public API to play audio from a raw buffer as described in the proposal

Add Pushing Buffer Support to AudioStreamManager

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

Fixes #1101 
The map is set to null during the onDestroy method call. So there is a race condition to access the last messages to be processed and that map getting destroyed. Added a null check to prevent the NPE.
* Added a null check to prevent NPE when `packetWriteTaskMasterMap` is set to null during the service shutdown

Fixes #1101

---

android/sdl_android/src/androidTest/assets/json/CloseApplication.json
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/requests/CloseApplicationTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/responses/CloseApplicationResponseTests.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/ProxyBridge.java
android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
base/src/main/java/com/smartdevicelink/protocol/enums/FunctionID.java
base/src/main/java/com/smartdevicelink/proxy/interfaces/IProxyListenerBase.java
base/src/main/java/com/smartdevicelink/proxy/rpc/CloseApplication.java
base/src/main/java/com/smartdevicelink/proxy/rpc/CloseApplicationResponse.java

Fixes #658 
Smoke tests added for the `CloseApplication` response and request classes.
Added `CloseApplication` request and response classes to the library.
* Added new RPC `CloseApplication` to the library.

New RPC CloseApplication

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/MediaServiceDataTests.java
base/src/main/java/com/smartdevicelink/proxy/rpc/MediaServiceData.java

Fixes #1047 
Code snippet
```java
final SdlArtwork mediaImage = new SdlArtwork("mediaImage.png", FileType.GRAPHIC_PNG, R.drawable.media_image, false);
sdlManager.getFileManager().uploadArtwork(mediaImage, new CompletionListener() {
@Override
public void onComplete(boolean success) {
Log.i(TAG, "onComplete: service published and file sent");
if(!success){
Log.e(TAG, "onComplete: file didn't send correctly");
return;
}
OnAppServiceData onAppServiceData = new OnAppServiceData();
MediaServiceData mediaServiceData = new MediaServiceData();
mediaServiceData.setMediaTitle("The title is media");
Image image = new Image();
image.setImageType(ImageType.DYNAMIC);
image.setIsTemplate(false);
image.setValue(mediaImage.getName()); …
```

Add Currently Playing Media Image to MediaServiceData

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/KeyboardPropertiesTests.java
base/src/main/java/com/smartdevicelink/managers/screen/choiceset/KeyboardAutocompleteCompletionListener.java
base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PresentChoiceSetOperation.java
base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PresentKeyboardOperation.java
base/src/main/java/com/smartdevicelink/proxy/rpc/KeyboardProperties.java

Fixes #649 
Unit tests are updated. This code snippet can be used for smoke testing:
```
KeyboardListener keyboardListener = new KeyboardListener() {
@Override
public void onUserDidSubmitInput(String inputText, KeyboardEvent event) {
Log.i(TAG, "onUserDidSubmitInput Input Text: " + inputText + " | Input Event: " + event.name());
}
@Override
public void onKeyboardDidAbortWithReason(KeyboardEvent event) {
Log.w(TAG, "onKeyboardDidAbortWithReason Event: " + event.name());
}
@Override
public void updateAutocompleteWithInput(String currentInputText, KeyboardAutocompleteCompletionListener keyboardAutocompleteCompletionListener) {
Log.i(TAG, "updateAutocompleteWithInput Update Auto Complete: " + currentInputText); …
```

[SDL 0108] AutoCompleteList

---

android/sdl_android/src/androidTest/assets/json/Alert.json
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/ImageFieldNameTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/requests/AlertTests.java
base/src/main/java/com/smartdevicelink/proxy/rpc/Alert.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/ImageFieldName.java

Fixes #795 
Unit tests have been updated to test the new `alertIcon` param
- Add new `alertIcon` param to the alert RPC

[SDL 0177] Alert icon

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/Validator.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/proxy/SystemCapabilityManagerTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/SystemCapabilityTypeTests.java
base/src/main/java/com/smartdevicelink/proxy/SystemCapabilityManager.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/SystemCapabilityType.java

Fixes #1123 
Unit tests and smoke tests
```java
sdlManager.getSystemCapabilityManager().getCapability(SystemCapabilityType.PRERECORDED_SPEECH, new OnSystemCapabilityListener() {
@Override
public void onCapabilityRetrieved(Object capability) {
List<PrerecordedSpeech> prerecordedSpeeches = SystemCapabilityManager.convertToList(capability, PrerecordedSpeech.class);
for (PrerecordedSpeech speech : prerecordedSpeeches){
Log.i(TAG, "SPEECH CAP: "+ speech.toString());
}
}
@Override
public void onError(String info) {
}
});
```
Add new capability type

Add prerecorded speech to SystemCapabilityManager

---

android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/LockScreenConfig.java

Fixes #1125 
Smoke testing was performed against the develop branch of core on an ubuntu VM
Change the default value of showDeviceLogo in the LockscreenConfig from false to true to match iOS

Implement Issue 1125 Show OEM Logo Lockscreen

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/ScreenManagerTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/SoftButtonManagerTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/Validator.java
base/src/main/java/com/smartdevicelink/managers/screen/BaseSoftButtonManager.java
base/src/main/java/com/smartdevicelink/managers/screen/SoftButtonObject.java
base/src/main/java/com/smartdevicelink/managers/screen/SoftButtonState.java

Fixes #1126 & #1127 
Unit tests have been updated.
- Add `isHighlighted` & `systemAction` setters to `SoftbuttonState`
- Improve `buttonId` setting logic in `SoftButtonManager`. The manager now allows devs to set their own ids and will not alter them. However, if the dev did not set `buttonId`, the manager will still automatically set one on the dev's behalf

SoftButtonObject enhancements

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/file/FileManagerTests.java
base/src/main/java/com/smartdevicelink/managers/file/BaseFileManager.java

Fixes #1133 
Unit tests have been updated. To smoke test the new method:
```
sdlManager.getFileManager().getBytesAvailable()
```
This PR adds `getBytesAvailable()` API to `FileManager` to let the developer know the number of bytes still available for files.

Add getBytesAvailable() to FileManager

---

android/sdl_android/src/androidTest/assets/json/Show.json
android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/ScreenManagerTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/TextAndGraphicManagerTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/TextFieldNameTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/requests/ShowTests.java
base/src/main/java/com/smartdevicelink/managers/screen/BaseScreenManager.java
base/src/main/java/com/smartdevicelink/managers/screen/BaseTextAndGraphicManager.java
base/src/main/java/com/smartdevicelink/proxy/rpc/Show.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/TextFieldName.java

Fixes #818 
Unit tests has been added to test the new `templateTitle` param. Also smoke testing can be done  using this snippet:
```
sdlManager.getScreenManager().setTemplateTitle("Template Title");
```
This PR adds `templateTitle` param to `Show` RPC as described in the proposal. It also updates `ScreenManager` accordingly to let the devs set `templateTitle` directly from the managers.

[SDL 0186] Template Titles

---

android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/TransportBroker.java
base/src/main/java/com/smartdevicelink/protocol/SdlProtocolBase.java

- Add a call to close the `TransportManager` when ending a session
- Always try to unbind from `RouterService` when called
- Fix where unbinding attempts were being made
- Fix issue in `RouterService` where a `SparseArray` was empty and the method `valueAt` would return a generic `Object` instance and cause a `ClassCastException`

Fix TransportBroker for Feature/implement sdl0054 change registration manager 

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/video/VideoStreamManagerTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/ImageResolutionTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/VideoStreamingCapabilityTests.java
android/sdl_android/src/main/java/com/smartdevicelink/encoder/VirtualDisplayEncoder.java
android/sdl_android/src/main/java/com/smartdevicelink/haptic/HapticInterfaceManager.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/video/VideoStreamManager.java
android/sdl_android/src/test/java/com/smartdevicelink/haptic/HapticInterfaceManagerTest.java
android/sdl_android/src/test/java/com/smartdevicelink/streaming/video/VideoStreamingParametersTest.java
base/src/main/java/com/smartdevicelink/proxy/rpc/ImageResolution.java
base/src/main/java/com/smartdevicelink/proxy/rpc/VideoStreamingCapability.java
base/src/main/java/com/smartdevicelink/streaming/video/VideoStreamingParameters.java

Fixes #804 
Unit tests added for:
- VideoStreamManager
- VideoStreamingCapability
- VideoStreamingParameters
- HapticManagerTest
Functional testing can be done by editing the preferred resolution,
and scale in HMI and testing that the captured view has the proper size and touches are reported
correctly and with the correct coordinates while clicking on the HMI interface.
Also the Automatic Haptic Rect sent to HMI should have the propper size according to the scale value set. 
The main change is related to changing the size of the view captured.
This is done by adding a new scale parameter in the video
streaming capability and by dividing the preferred resolution from the
HMI and the scale.
Changes in the calculation of …

[SDL 0179]Pixel density and Scale

---

android/sdl_android/src/main/java/com/smartdevicelink/managers/video/VideoStreamManager.java
android/sdl_android/src/main/java/com/smartdevicelink/streaming/video/SdlRemoteDisplay.java

Fixes #1102 (Similar to PR #1116)
Tested on own version of app + custom web-based HMI
Added a state transition to Video Stream Manager so that the state machine works, and added an alternative condition to show a SdlRemoteDisplay (which is when there already was a previous but different Display)
* NA
* NA
* Added state transition to VideoStreamManager
* Altered if condition in SdlRemoteDisplay
- NA

Bug fix for #1102: Resuming video stream

---

android/sdl_android/src/main/java/com/smartdevicelink/SdlConnection/SdlSession2.java
android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
base/src/main/java/com/smartdevicelink/protocol/SdlProtocolBase.java

Fixes #1150, #1151 
Smoke testing as described in issues
Allow the proper video service flags to be reset when video services disconnect. this also fixes the case where sdlproxybase would not know if a video service that was hosted on a secondary transport disconnected.

Allow Video Service to restart after secondary transport disconnection

---

base/src/main/java/com/smartdevicelink/protocol/SdlProtocolBase.java

Fixes #1181 
This PR fixes an issue that causes RPC service `ISdlServiceListener` not to be called when the service is started again as an encrypted service

ISdlServiceListener not called when RPC is service started again

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/USBAccessoryAttachmentActivity.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/USBTransport.java

Fixes #1086 
- Connect AOA for both multiplexing and legacy USB connections
- Added a check in `USBAccessoryAttachmentActivity` to not send broadcast if `usbAccessory` is null.
- Changed private method signature to take in a reference to the `usbAccessory`
- Added null checks to methods in the `USBTransport` class;
* Should prevent NPE from happening in known possible case

Add safeguards for null usbAccessory

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java
android/sdl_android/src/main/res/values/sdl.xml

Fixes #1167 
This bug is currently not possibly reproduce in a "testing" setting. We need to work to find a way to actually reproduce the bug.
This PR was tested by making the router service start and stop very quickly, this involved power cycling the bluetooth adapter once a connection was made.
In order to test the new UncaughtExceptionHandler, modify the code in the `SdlRouterService`'s method `enterForeground` to return immediately without creating a notification or calling `startForeground`;
- Added a call to `startForegroundService` during many possible cases and before `stopSelf` is called.
- Added an `UncaughtExceptionHandler` that will look for the ANR exception caused by the service not calling `startForeground` …

Attempts to fix  #1167 

---

android/sdl_android/src/main/java/com/smartdevicelink/managers/SdlManager.java
javaSE/src/main/java/com/smartdevicelink/managers/SdlManager.java

Fixes #1172
- Stop the SdlService as soon as the SdlManager becomes ready. Observe no errors because of missing cleanup.
- Connect and disconnect transport an observe no regression errors.
- When SdlManager.dispose() is called the underlying main layers need to also be disposed. The PR calls the dispose and stop methods of the current proxy layer and lifecycle manager layer for the Android and Java projects.
* The dispose call will now properly shut down and clean up items in the library as to not leak receivers and bound connections to services.

Dispose main underlying layers when sdlManager is disposed

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/util/VersionTest.java
base/src/main/java/com/smartdevicelink/proxy/SystemCapabilityManager.java
base/src/main/java/com/smartdevicelink/proxy/rpc/HMICapabilities.java
base/src/main/java/com/smartdevicelink/util/Version.java

Fixes #1159 
- Test with 6.0.0 RPC spec version of Core and with 5.1.0 version
- Added `AppServices`, `Displays`, and `SeatLocation` to HMICapabilities
- Added cases to switch statement in SCM for previously added items
- Added compatibility in case statements for previous RPC spec versions that supported feature but didn't include items

Add missing HMICapabilities

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/DisplayCapabilitiesTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/WindowCapabilityTests.java
base/src/main/java/com/smartdevicelink/managers/screen/BaseScreenManager.java
base/src/main/java/com/smartdevicelink/proxy/rpc/DisplayCapabilities.java
base/src/main/java/com/smartdevicelink/proxy/rpc/WindowCapability.java

Fixes #1076 
This PR move `menuLayoutsAvailable` from `DisplayCapabilities` to `WindowCapability` as mentioned in the proposal.

Move menuLayoutsAvailable to WindowCapability

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

Fix for issue-1190: register ACTION_STATE_CHANGED, so that mListenForDisconnect can handle the action correctly.
Fixes #1190 
N/A
Fix for issue-1190: register ACTION_STATE_CHANGED, so that mListenForDisconnect can handle the action correctly.
* N/A
* N/A
* This PR fixes the issue #1190: SdlRouterService does not handle the case where Bluetooth Adapter is turned off.
- N/A

Fix for issue-1190

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/TransportManager.java

- Force app into legacy mode to use legacy BT
- Turn off the bluetooth adapter
- Ensure legacy mode is exited
- Added STATE_CHANG as action to listen for while running in legacy mode BT

Register legacyBT BR to listen for state change

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/ScreenManagerTests.java
base/src/main/java/com/smartdevicelink/managers/screen/BaseScreenManager.java

This PR renames `getTemplateTitle()` in the ScreenManager to `getTitle()`

Rename getTemplateTitle() to getTitle()

---

base/src/main/java/com/smartdevicelink/managers/screen/SoftButtonObject.java

Fixes #1199 
This PR updates `SoftButtonObject` javadoc to mention that `SoftButtonState` list cannot be reused for multiple `SoftButtonObjects`

Update SoftButtonObject javadoc

---

base/src/main/java/com/smartdevicelink/managers/file/BaseFileManager.java

Change list files on error to allow the manager to transition to ready, and keep SDLManager from transitioning to an error state and not starting

Keep File Manager from Error State

---

android/sdl_android/src/main/java/com/smartdevicelink/managers/SdlManager.java
javaSE/src/main/java/com/smartdevicelink/managers/SdlManager.java

Sdl manager crashes if language is null in the RAIR. THis param is optional, therefore it should not crash

sdl manager crashes when non-mandatory language is null

---

android/sdl_android/src/main/java/com/smartdevicelink/managers/SdlManager.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/video/VideoStreamManager.java
android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
android/sdl_android/src/main/java/com/smartdevicelink/streaming/StreamPacketizer.java
base/src/main/java/com/smartdevicelink/protocol/SdlProtocolBase.java

Fixes #1110 
1. Create a sample video streaming application
2. Connect with IVI system, select app, and observe video stream starting
3. Disconnect transport during streaming
4. Reconnect transport, observe video stream starting
5. Repeat process multiple times and ensure stream starts every time
- Correctly identify if high bandwidth transport is required and shutdown service if not available during transport disconnection
- Remove incorrect call to start two stream packetizers by accident
- Handle case where older systems didn't perform video streaming param negotiation
* The reported bug occured because the buffer that the `put` call was used on was full. This happened because there was actually an error in the …

Fix issue with video streaming stability

---

android/sdl_android/src/androidTest/assets/json/RegisterAppInterface.json
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/Test.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/Validator.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/RPCConstructorsTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/AppInfoTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/requests/RegisterAppInterfaceTests.java
base/src/main/java/com/smartdevicelink/proxy/rpc/AppInfo.java
base/src/main/java/com/smartdevicelink/proxy/rpc/RegisterAppInterface.java

Fixes #1217 
Unit tests are added to test `AppInfo` struct and the RAI
This PR adds the `AppInfo` struct that was missing from the java suite library

Add AppInfo to RegisterAppInterface RPC

---

android/sdl_android/src/main/java/com/smartdevicelink/util/SdlAppInfo.java

Fixes #1227 
Install two sdl apps on the phone and make sure the router service is selected based on the compare function in `BestRouterComparator`
This PR fixes a potential overflow issue that could happen if the result of subtracting to `long` numbers is outside the boundaries of an `int`

Fix potential overflow issue in BestRouterComparator

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/menu/MenuManagerTests.java
base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseMenuManager.java

Fixes #1215 
Try setting the menu to `null` and make sure the menu cells are getting cleared correctly without crashing the app:
```
sdlManager.getScreenManager().setMenu(null);
```
This PR fixes some potential NPEs in `MenuManager` when setting the menu to `null`

Fix potential NPEs in BaseMenuManager

---

javaEE/bintray.gradle
javaEE/bintray.properties
javaSE/bintray.gradle
javaSE/bintray.properties

- Update the version `VERSION` file to a temp test version something like `test_4.10.1` 
- Use the `bintrayUpload` Gradle task to make sure that scripts pushes correctly to bintray
```
./gradlew bintrayUpload
```
- Confirm that the compile line starts with `com` like 
```
compile 'com.smartdevicelink:sdl_java_se:{version}'
```
- Use the bintray gradle line to fetch the library and confirm that the library works
This PR updates the `groupId` in the bintray compile line for the `JavaSE` & `JavaEE` to `com.smartdevicelink` to match the `Android`'s `groupId`.

Update Bintray groupId to com.smartdevicelink

---

android/sdl_android/src/main/java/com/smartdevicelink/managers/video/VideoStreamManager.java
android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java

Fixes #1245 
* Connect to a headunit that can send video streaming capability without `hapticSpatialDataSupported`
* Start video streaming
* Make sure app does not crash
Fix two NPE issue in `SdlProxyBase` and `VideoStreamManager`

Fix NPE issue with IsHapticSpatialDataSupported()

---

README.md
codecov.yml

This PR makes the following changes:
*  Updates `codecov.yml` file for Codecov to set patch status target to 60%. [More info about patch status can be found here](https://docs.codecov.io/docs/commit-status)
* Update Codecov badge  in `README`  (it was broken previously)
* Update CI badge in `README` to use GitHub Actions instead of Travis

Change Codecov patch status target

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/proxy/SystemCapabilityManagerTests.java
base/src/main/java/com/smartdevicelink/proxy/SystemCapabilityManager.java

Fixes #1275 
Added more unit tests to test the fix
1. Use `SCM.addOnSystemCapabilityListener()` to add a listener for `NAVIGATION` capability for example
2. Make sure the listener is called
3. Call `SCM.getCapability(SystemCapabilityType.NAVIGATION, ..., true)`
3. Confirm the listener that was added in step 1  is called again 
This PR fixes an issue with `addOnSystemCapabilityListener()` method that causes the listeners not to be triggered if a fresh copy of the capability is received when the developer calls `getCapability()` and sets `forceUpdate` to `true`

Update SCM to notify listeners if fresh copy of capability is received

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java
android/sdl_android/src/main/res/values/sdl.xml

Fixes #1267 (partially)
-None specifically. This revolves around bluetooth connections.
Added the notification channel delete method call back into the router service. Some phones like the pixel 2 & 3 were only clearing the notification 5-7 seconds after the service called stopForeground. Deleting the channel removes the notification instantly. We added a check to avoid a race condition in which the channel is deleted before the notification was actually shown.
* Notification being displayed even after service leaves foreground
* Added check to timer to make sure it is not going to negative numbers
* Incremented router service version

Delete notification channel when possible

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexUsbTransport.java

Fixes #1279
Removed a call to reset the buffer array after a packet was found to be finished or entered an error state. The loop would continue but the data in the buffer would be all `0x00`'s. Added a continue call to ensure the loop is continued and easily readable as to what should happen.
* Fixes #1279 as the data should not be reset before continuing the loop now

Remove setting new buffer after PSM FINISHED/ERROR states in USB tarnsport

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/file/FileManagerTests.java
base/src/main/java/com/smartdevicelink/managers/file/BaseFileManager.java

Fixes #1284 
This PR is **ready**
Added unit test to test to make sure static icons are not uploaded.
Tested using Manticore
Added logic to align uploadFiles() to uploadFile() in baseFileManager to handle static Icons the same. Before uploadFiles would upload static icons and uploadFile would not and return the lister as success. Now uploadFiles will not upload static icons.
* Aligned uploadFiles with uploadFile in BaseFileManager to handle static Icons the same.

Bugfix/issue 1284 UploadFiles() doesn't handle static icons correctly

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/lifecycle/RpcConverterTest.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/AppInterfaceUnregisteredReasonTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/MaintenanceModeStatusTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/MessageTypeTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/PermissionStatusTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/ResultTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/TimerModeTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/VehicleDataActiveStatusTests.java
base/src/main/java/com/smartdevicelink/protocol/enums/FunctionID.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/AppInterfaceUnregisteredReason.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/BitsPerSample.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/Dimension.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/DisplayType.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/HMILevel.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/Jingle.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/Language.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/MaintenanceModeStatus.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/MessageType.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/MetadataType.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/PermissionStatus.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/PredefinedLayout.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/Result.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/SamplingRate.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/SoftButtonType.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/StaticIconName.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/SystemContext.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/TimerMode.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/TriggerSource.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/VehicleDataActiveStatus.java

Fixes #1283 
Added unit tests for the new enums
This PR adds some missing enums that exist in the RPC Spec but not in Java Suite.
* Added the enums: `MaintenanceModeStatus`, `MessageType`, `PermissionStatus`, `TimerMode`, `VehicleDataActiveStatus`
* Added missing values for existing enums: `FunctionID.RESERVED`, `AppInterfaceUnregisteredReason.UNSUPPORTED_HMI_RESOURCE`, `Result.CHAR_LIMIT_EXCEEDED`
* Rename `INTERNAL_NAME` to `VALUE` for existing enums

Add missing enums

---

base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseVoiceCommandManager.java

Fixes #1293
1- Set voice commands and verify they are working correctly
2- Set different voice command and make sure they are updated correctly
This PR fixes an issue `setVoiceCommands()`. Where `oldVoiceCommands` is set to the wrong value.

Fix an issue in setVoiceCommands()

---

android/sdl_android/src/main/java/com/smartdevicelink/proxy/RPCRequestFactory.java
android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
base/src/main/java/com/smartdevicelink/proxy/rpc/DeviceInfo.java

Fixes #1290 
This PR depreciates `DeviceInfo.DEVICE_OS`as it doesn't exist in the spec

Deprecate DeviceInfo.DEVICE_OS

---

.github/workflows/android.yml

Fixes #1297 
This PR updates the Github Actions `android.yml` file to trigger the CI on opening a pull request. This makes the CI run when the pull request is started from a fork.

Make Github Actions run on opening a PR

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/file/FileManagerTests.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/file/filetypes/SdlArtwork.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/file/filetypes/SdlFile.java
base/src/main/java/com/smartdevicelink/managers/file/BaseFileManager.java
javaSE/src/main/java/com/smartdevicelink/managers/file/filetypes/SdlFile.java

Fixes #1302 
Added unit test to test file not overwriting itself in BaseFileManager.uploadfiles as well as BaseFileManager.uploadFiles
Tested using manticore.
Added overwrite property to SdlFile in Android and JavaSE, added logic to baseFileManager.java to handle the overwrite property when uploading files.
Overwrite property is always set to true, in next major release to align with IOS we need to change it to false
To test I recommend after uploading one file to set the SdlFIle's overwrite property to false and upload it the second time in the completion listener's onComplete of the first upload to verify that the file has uploaded before it tries to upload it again. Ex:
```
SdlFile livio = new SdlFile("livio", …
```

Add overwrite property

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/file/FileManagerTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/SoftButtonManagerTests.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/file/filetypes/SdlFile.java
base/src/main/java/com/smartdevicelink/managers/screen/SoftButtonObject.java
base/src/main/java/com/smartdevicelink/managers/screen/SoftButtonState.java
base/src/main/java/com/smartdevicelink/managers/screen/choiceset/ChoiceCell.java
base/src/main/java/com/smartdevicelink/managers/screen/menu/MenuCell.java
javaSE/src/main/java/com/smartdevicelink/managers/file/filetypes/SdlFile.java

Fixes # 1257
Added testSoftButtonEq() and testSoftButtonStateEq() to SoftButtonManagerTests and testSdlFIleEq() to FileManagerTest
Tested using manticore
Added a method in SdlFile in android and JavaSE, softButtonObjects, and SoftButtonState that overrides their equals methods. The new equals methods compare the objects variables instead of their memory address.
*  Added a method in softButtonObjects that overrides its equals method. 
*  Added a method in softButtonState that overrides its equals method. 
*  Added a method in SdlFile that overrides its equals method for android and JavaSE.

Add Override Equals method to softButtonObject

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

- [-] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [-] I have tested Android, Java SE, and Java EE
- I have only tested with Android as it is the only affected platform for these changes.
- Bluetooth adapter should be on.
- Bluetooth headset that does not support SDL should already be paired but not currently connected.
- IVI system that supports SDL should already be paired but not currently connected.
- Create a signing config for the hello_sdl_android app
1. Install hello_sdl_android with a release build selected (eg multi_sec_offRelease) 
2. Go to Settings -> Apps & notifications (or similar) and select "Hello SDL Android"
3. Fore Stop the app, go to …

Refactor router service's exitForeground logic

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/notifications/OnButtonPressTests.java
android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
base/src/main/java/com/smartdevicelink/managers/screen/BaseSoftButtonManager.java
base/src/main/java/com/smartdevicelink/proxy/rpc/OnButtonPress.java

Fixes #547
Updated corresponding `OnButtonPress` tests.
This PR updates the names of `setCustomButtonName()` & `getCustomButtonName()` in `OnButtonPress` to match the RPC spec.

Fix OnButtonPress's CustomButtonID getter/setter naming

---

base/src/main/java/com/smartdevicelink/protocol/enums/FunctionID.java
base/src/main/java/com/smartdevicelink/proxy/rpc/OnLockScreenStatus.java
base/src/main/java/com/smartdevicelink/proxy/rpc/OnSdlChoiceChosen.java
base/src/main/java/com/smartdevicelink/proxy/rpc/OnStreamRPC.java
base/src/main/java/com/smartdevicelink/proxy/rpc/StreamRPCResponse.java

Fixes #14
This PR deprecates the following RPCs as they are only used internally and they are not part of the RPC spec:
- `OnLockScreenStatus`
- `OnSdlChoiceChosen`
- `OnStreamRPC`
- `StreamRPCResponse`

Deprecate internal RPCs

---

android/hello_sdl_android/src/main/java/com/sdl/hellosdlandroid/SdlReceiver.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterStatusProvider.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/USBAccessoryAttachmentActivity.java
android/sdl_android/src/main/java/com/smartdevicelink/util/AndroidTools.java

Reverts smartdevicelink/sdl_java_suite#1347
These changes prevent the excpetion from happing in prodcution. however:
- The solution should try and make SDL work in production by using the next RS
- We should think about what happens when the app that starts the RS has the permission but the app that hosts it doesn't

Revert "Bugfix/issue_1343 foreground permissions exception"

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/permission/PermissionManagerTests.java
base/src/main/java/com/smartdevicelink/managers/permission/BasePermissionManager.java
base/src/main/java/com/smartdevicelink/managers/permission/PermissionStatus.java

Fixes #1353
Updated permission manager unit tests to reflect the new changes.
1. Run the app and connect to Manticore
2. Add an `OnPermissionChangeListener` for the `GetWayPoints` RPC
3. Confirm listener is triggered 
This PR fixes an issue in `PermissionManager` where it doesn't trigger the listener with the cached value after adding the listener. This means the listener was not getting triggered if the permission change happened before adding the listener.

Trigger OnPermissionChangeListener callback with cached value after adding the listener 

---

base/src/main/java/com/smartdevicelink/managers/permission/BasePermissionManager.java

This change is to ensure the Javadocs for `PermissionManager.addListener()` align with the behavior expected for the java suite library

Update javadocs for PermissionManager.addListener

---

.github/workflows/android.yml
android/hello_sdl_android/build.gradle
android/hello_sdl_android/src/main/AndroidManifest.xml
android/hello_sdl_android/src/main/java/com/sdl/hellosdlandroid/SdlService.java

Fixes #1374 
Ensured HelloSdl is able to run against Core and Manticore using the proposed changes. Also ensured HelloSdl is able to run against Core and Manticore using Android R.
This change will set Hello SDL to target Android SDK 29. It will also set the foregroundServiceType to connectedDevice for the SdlService and SdlRouterService in the AndroidManifest File.

Target SDK 29 and add foregroundServiceType param

---

android/sdl_android/src/main/java/com/smartdevicelink/managers/SdlManager.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/lifecycle/LifecycleManager.java
base/src/main/java/com/smartdevicelink/managers/BaseSdlManager.java
base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java
javaSE/src/main/java/com/smartdevicelink/managers/SdlManager.java
javaSE/src/main/java/com/smartdevicelink/managers/lifecycle/LifecycleManager.java

* Connect app to the head unit
* While the app is connected, change the language on the head unit side
* Make sure that the app unregisters then registers again with the new language
Core version / branch / commit hash / module tested against: Ford Sync 3.2
HMI name / version / branch / commit hash / module tested against: Ford Sync 3.2
This PR fixes two issues introduced by this PR #1366:
* Propagate the disconnect reason correctly so the app reconnects after language change
* Fix an issue that causes managerListener.onDestroy to be called twice

Fix app reconnection issue after language change 

---

base/src/main/java/com/smartdevicelink/managers/BaseSdlManager.java
base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java

Fixes #1400 
1. In the SdlService add a OnHashChange listener and store the hashId in sharedPreferences when notified
2. Set Menu items in the SdlService
3. Run your app against core and verify that a hashId has been stored and that the menu items are available.
4. In SdlService call sdlManager.setHashId with the hashId set in your shared preferences.
5. Comment out the call to setMenus() in the SdlService.
6. Rerun the application, and make sure the RegisterAppInterfaceResponse is successful and that the menu items are still available
This PR will add the option to set the HashId via the sdlManager builder. This will enable the developer the set the resumption HashId if needed for their application. The SdlManager …

Add hashId to sdlmanager builder

---

base/src/main/java/com/smartdevicelink/proxy/rpc/listeners/OnRPCResponseListener.java

Unit tests unchanged at this point as only the method was deprecated. Next release where the method is removed, the tests will need to be updated.
-Added the deprecated flag and description to the onError method in the OnRPCResponseListener
* Deprecated a confusing callback that can be addressed in the next major version

Deprecate onError for OnRPCResponseListener

---

base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadChoicesOperation.java

Fixes #1336 
Tested against Sync 3.0 and manticore
In ``PreloadChoicesOperation.preloadCells`` For every request sent in the list the OnMultipleRequestListener onResponse or onError will be called depending on if the request was successful or a failure, then onFinished() gets called after the list is complete. 
With the current implementation ```PreloadChoicesOperation.super.onFinished();``` will get called in the onError and onFinished as well as the completion listener will always get notified as a success. If one failed to a GENERIC_ERROR, this could lead to you being notified that preloading is a success and when you go to present a choiceSet you will get an "INVALID_ID, null" error.
To test in …

Choice Set Error

---

android/sdl_android/src/main/java/com/smartdevicelink/util/Log.java
base/src/main/java/com/smartdevicelink/util/NativeLogTool.java
hello_sdl_java/src/main/java/com/smartdevicelink/java/Main.java
javaSE/src/main/java/com/smartdevicelink/util/Log.java

This PR updates the `Log` methods to return `void` instead of a hardcoded integer value. It also removes the if statement that prints an error message if the returned value is less than the chunk size. Because that will make the `NativeLogTool` prints an error message for every log message:
https://github.com/smartdevicelink/sdl_java_suite/blob/9946777469c0f58a9732cab42669c56850edb761/base/src/main/java/com/smartdevicelink/util/NativeLogTool.java#L133

Fix loggin issue in DebugTool

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/proxy/RPCStructTests.java
base/src/main/java/com/smartdevicelink/proxy/RPCStruct.java

Fixes #1407 
Get `tirePressure` using the following code snippet and make sure the value is retrieved correctly without crashing the app
```
GetVehicleData getVehicleData = new GetVehicleData();
getVehicleData.setTirePressure(true);
getVehicleData.setOnRPCResponseListener(new OnRPCResponseListener() {
@Override
public void onResponse(int correlationId, RPCResponse response) {
GetVehicleDataResponse getVehicleDataResponse = (GetVehicleDataResponse) response;
Log.i(TAG, "tirePressure: " + getVehicleDataResponse.getTirePressure().getLeftFront().getPressure());
}
});
sdlManager.sendRPC(getVehicleData);
```
Module tested against: Manticore
This PR fixes an issue in `RCPStruct` that causes a class cast exception when the app …

Fix ClassCastException when calling RPC getter method returning Float 

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/TestValues.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/Validator.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/DriverDistractionCapabilityTest.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/HMICapabilitiesTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/SystemCapabilityTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/SystemCapabilityTypeTests.java
base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java
base/src/main/java/com/smartdevicelink/proxy/SystemCapabilityManager.java
base/src/main/java/com/smartdevicelink/proxy/rpc/DriverDistractionCapability.java
base/src/main/java/com/smartdevicelink/proxy/rpc/HMICapabilities.java
base/src/main/java/com/smartdevicelink/proxy/rpc/SystemCapability.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/SystemCapabilityType.java

Fixes #729 
Unit tests added for the new RPCs
Core branch: smartdevicelink/sdl_core#3447
Rpc_Spec branch: smartdevicelink/rpc_spec#263
Generic_HMI branch: smartdevicelink/generic_hmi#282
This PR implements [SDL-0152](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0152-driver-distraction-list-limits.md) to allow the HMI to limit menu structures while driving.
Create an integration branch and test with [Implement SDL-0148 Additional SubMenus](https://github.com/smartdevicelink/sdl_java_suite/pull/1423)
* Implements (#962) the ability for an HMI to limit menu structures while driving.

SDL-0152 Driver Distraction: Command List Limitations

---

generator/transformers/enums_producer.py

Fixes #1425 
To smoke test the PR, use the generator to generate `ImageFieldName` enum and make sure all the values are generated correctly. 
This PR fixes an issue in the RPC generator that makes it generate enum values with incorrect capitalization. Please refer to the issue to see an example.

Fix generated enum value names in RPC generator

---

generator/README.md
generator/transformers/functions_producer.py
generator/transformers/structs_producer.py

Fixes #1444 
- Use the RPC generator to generate all RPCs
- Confirm that the `annotations` imports are correct and they use the Android X library
This PR updates the RPC Generator to generate correct Android X imports instead of the old support library imports

Update RPC Generator to generate correct Android X imports

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/file/filetypes/SdlFileTests.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/file/filetypes/SdlFile.java

Fixes #1451
This PR makes **major** API changes.
`SdlFile` unit tests have been updated to assert that the default value for overwrite is `false`
- Create a `SdlFile` and don't set the `overwrite` property 
- Upload the file and make sure it gets uploaded the first time
- Try to upload the file again and make sure it doesn't get uploaded the second time
- Create another `SdlFile` and set `overwrite` to `true`
- Upload the file and make sure it gets uploaded the first time
- Try to upload the file again and make sure it gets uploaded the second time
This PR Updates the default value for the `overwrite` property in SdlFile to be `false` to match iOS implementation

Set default value for overwrite to false in SdlFile

---

javaSE/src/main/java/com/smartdevicelink/managers/file/FileManager.java
javaSE/src/main/java/com/smartdevicelink/managers/file/filetypes/SdlArtwork.java
javaSE/src/main/java/com/smartdevicelink/managers/file/filetypes/SdlFile.java

Fixes #1469
This code snippet can be used to test uploading a file using URI:
```
void testSdlFileURI (){
// Get URI
File file = new File("<file path>");
URI uri = file.toURI();
// Upload file
final SdlArtwork sdlFile = new SdlArtwork(null, FileType.GRAPHIC_PNG, uri, false);
sdlFile.setOverwrite(true);
sdlManager.getFileManager().uploadFile(sdlFile, new CompletionListener() {
@Override
public void onComplete(boolean success) {
if (success) {
Log.i(TAG,"File Uploaded: " + sdlManager.getFileManager().hasUploadedFile(sdlFile));
// Send Show
Show show = new Show();
show.setMainField1("Hi There");
Image image = new Image(sdlFile.getName(), ImageType.DYNAMIC);
show.setGraphic(image);
show.setOnRPCResponseListener(new …
```

JavaSE - Add SdlFile constructor that takes URI

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/RPCStructTests.java
base/src/main/java/com/smartdevicelink/proxy/RPCStruct.java

Fixes #1473 
- Added a test class for the RPCStruct class. Currently only one test to test the format object for cases of empty lists, null as first value, null in lists, and happy path list.
- All other RPC tests should also be performed to ensure the new behavior doesn't break.
Chnages to the RPCStruct.formatObject method
- If list is empty, the method will now return an empty but not null list object instead of a null object
- The method will now attempt to traverse the list to find the first instance of a nonnull value
- If even after traversing the list only null values are found, an instance of the list is returned
* Empty lists and lists with null objects at the head of the list now return properly

Fix Issue 1473 - Null items as head or empty lists

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/ManagerUtilityTests.java
base/src/main/java/com/smartdevicelink/managers/ManagerUtility.java

Fixes #1465 
- Added unit tests around the utility classes that were modified
Added null checks to a couple methods in the `ManagerUtility` class that iterates over lists. While there was a null check for the list itself, it skipped such check on the items stored in the list.
* Check for null in multiple cases now since null is a valid item in a list

Fix Issue 1465 - NPE in ManagerUtility

---

base/src/main/java/com/smartdevicelink/managers/ManagerUtility.java

Fixes #1495 
Tested against Sync 3.0 TDK-X2-U2-150
Fix NPE in ManagerUtility.getMaxNumberOfMainFieldLines that occurs on a sync 3.0 tdk
* Added an null check for TextFields.getName()

Add check to prevent NPE in ManagerUtility class

---

base/src/main/java/com/smartdevicelink/streaming/audio/AudioStreamingLPCMParams.java

Fixes #1306 
This PR deprecates the enum `AudioStreamingLPCMParams` as it is not used anywhere in the library

Deprecate AudioStreamingLPCMParams enum

---

base/src/main/java/com/smartdevicelink/managers/screen/BaseSoftButtonManager.java

Fixes #1499 
Tested sending a setDisplayLayout request to core with template DOUBLE_GRAPHIC_WITH_SOFTBUTTONS then changing to GRAPHIC_WITH_TEXT. 
Core version / branch / commit hash / module tested against: Core 6.1
HMI name / version / branch / commit hash / module tested against: Generic_HMI 0.8.1
Add null check to BaseSoftButtonManager onCapabilityRetrieved to check if incoming softButtonCapabilities are null or not. If null setting the SoftButton capabilities to null
* [Breaking change info]
* [Enhancement info]
* Fix NPE from issue #1499

Add NPE check to SoftButtonCapabilities onCapabilityRetrieved

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/protocol/SdlPacketTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/protocol/heartbeat/HeartbeatMonitorTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/responses/SubscribeVehicleDataResponseTest.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/responses/UnsubscribeVehicleDataResponseTest.java
base/src/main/java/com/smartdevicelink/session/BaseSdlSession.java

Fixes #1306 
This PR fixes some todo comments in the library

Fix some todo comments 

---

android/sdl_android/src/main/java/com/smartdevicelink/streaming/StreamPacketizer.java
base/src/main/java/com/smartdevicelink/streaming/video/RTPH264Packetizer.java

Fixes #1398 
- None added
There was a potential race condition where the producer thread (main) would be trying to add data to the shared buffer but was blocked awaiting the consumer thread to take data during a stop() method call. The consumer thread is interrupted and set to null then the queue itself is cleared. This opens up space in the queue and more data is added. If there is currently a buffer being iterated through to create the NAL units the queue can quickly fill up again and cause a deadlock to occur since there is no consumer.
* Check if the consumer thread is dead before continuing to iterate through a buffer.

Fix Issue 1398 - Avoid deadlock from using blocking queues

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/TestValues.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/HMICapabilitiesTests.java
base/src/main/java/com/smartdevicelink/proxy/rpc/HMICapabilities.java

This PR updates the name for HMICapabilities.setDriverDistraction() to setDriverDistractionAvailable() to align with the other APIs in that class.

Fix inconsistency with HMICapabilities API names 

---

generator/transformers/common_producer.py

Fixes #1506
This PR fixes an issue in RPC Generator where it cuts off the Javadoc comments after @TODO

Fix JavaDoc comments cutoff after todo in RPC Generator 

---

base/src/main/java/com/smartdevicelink/util/FileUtls.java

Fixes #1513 
Follow the reproduction steps in the issue description to reproduce the bug
Core version : 7.0.0 / Generic HMI
This PR sets the user agent for the HTTP request in `downloadFile()` API so the request doesn't get rejected by the server

Set user agent in downloadFile()

---

android/sdl_android/src/main/java/com/smartdevicelink/session/SdlSession.java

To smoke test the fix, use an SDL app that uses multiplex as transport then:
1- Connect the app to TDK via Bluetooth 
2- Connect a USB cable and wait for USB to fully connect
3- Disconnect Bluetooth from the phone
4- Make sure that the app registers again via USB
Core version / branch / commit hash / module tested against: Ford SYNC 3.4
This PR reverts one of the changes that were done in this commit https://github.com/smartdevicelink/sdl_java_suite/commit/f2ca3db47bb8b4381f3086db44dc0f7f82ae5183 that causes `mediaStreamingStatus.isAudioOutputAvailable()` to always get called when `isAudioRequirementMet()` is called. The extra  `mediaStreamingStatus.isAudioOutputAvailable()` call is making the app send `EndService` …

Fix an issue in switching to backup transport

---

base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java

Fixes #1518 
to smoke test the PR:
1. Install hello sdl android and make sure it uses multiplex as a transport 
2. Connect the app to TDK via Bluetooth
3. Do not put the app in HMI `FULL`
4. Connect a USB cable and wait for USB to fully connect
5. Disconnect Bluetooth from the phone
6. Put the app in HMI `FULL`
7. Confirm text and graphics are displayed
Core version / branch / commit hash / module tested against: Ford SYNC 3.4
This PR fixes an issue that causes the `ScreenManager` queues not to work properly when the app re-registers on backup transport. The reason for the issue was that the taskmaster doesn't reset correctly when proxy recycles.

Reset taskmaster when LifecycleManager recycles 

---

android/sdl_android/src/main/java/com/smartdevicelink/session/SdlSession.java
javaSE/javaSE/src/main/java/com/smartdevicelink/session/SdlSession.java

Fixes #1520 
Core version / branch / commit hash / module tested against: Ford SYNC 3.4
This PR fixes an issue in `OnServiceError()` where it hardcodes an error message instead of passing the correct error message.

Fix onServiceError message in SdlSession

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/lockscreen/LockScreenManagerTests.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/LockScreenManager.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/SDLLockScreenActivity.java

Fixes #1515  
Create app with Lockscreen config:
```java
LockScreenConfig lockScreenConfig = new LockScreenConfig();
lockScreenConfig.setDisplayMode(LockScreenConfig.DISPLAY_MODE_ALWAYS);
lockScreenConfig.enableDismissGesture(true);
```
Test 1:
1. Ensure DriverDistraction is OFF on Manticore
2. Deploy app
3. Notice the lockscreen appears
4. Enable DriverDistraction on Manticore
5. Notice there is now the option to swipe away lockscreen
6. Swipe away lockscreen
7. Notice no lockscreen is displayed
8. Turn OFF DriverDistraction on Manticore
9. Notice no lockscreen is displayed
Test 2:
1. Ensure DriverDistraction is ON on Manticore
2. Deploy app
3. Notice the lockscreen appears with option to swipe away
4. Swipe away …

Correct Lockscreen start behavior

---

generator/templates/function_template.java
generator/templates/struct_template.java

Fixes #1463 
N/A
Tested using the RPC Generator to make sure it generated structs and functions correctly, as well as making sure setters and chainable.
Edited `function_template.java` and `struct_template.java` to make RPC setters chainable when it generates Rpc's
* RPC generator will now make RPC setters chainable

Make Rpc setters chainable in RPC generator

---

generator/test/test_functions.py
generator/test/test_structs.py

Fixes #1531 
This PR updates the annotations imports in the RPC generator tests to use the new AndroidX ones.

Fix AndroidX imports in RPC generator unit tests

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/ManagerUtilityTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/proxy/RPCRequestFactoryTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/RPCStructTests.java

Fixes #1540
This PR is **read** for review.
`ManagerUtilityTests.java` and `RPCStructTests.java` were apart of the hotFix, but were developed during 5.0. The test needed to be modified slightly to work with 4.12.1. 
- Use `CharacterSet.CID2SET` instead of Using `CharacterSet.UTF_8` in `ManagerUtilityTests.java`
- Use `import android.support.test.runner.AndroidJUnit4` instead of `import androidx.test.ext.junit.runners.AndroidJUnit4` in `ManagerUtilityTests.java` and `RPCStructTests.java`
- Fix unit test in `RPCRequestFactoryTests.java` in relation to #1473

Fix unit test for Hotfix

---

base/src/main/java/com/smartdevicelink/proxy/rpc/OnSystemRequest.java
base/src/main/java/com/smartdevicelink/proxy/rpc/PutFile.java
base/src/main/java/com/smartdevicelink/proxy/rpc/TouchEvent.java

Fixes #1536
This PR adds the missing `Use @link` annotations to some deprecated APIs to clarify what new APIs should be used instead

Add missing `Use @link` annotations to some deprecated APIs

---

base/src/main/java/com/smartdevicelink/managers/screen/TextAndGraphicUpdateOperation.java

Fixes #1541
To smoke test the PR, use this code snippet and confirm that the media track field is displayed on hmi:
```
sdlManager.getScreenManager().beginTransaction();
sdlManager.getScreenManager().setTextField1("Hi there");
sdlManager.getScreenManager().setMediaTrackTextField("Media Track");
sdlManager.getScreenManager().commit(new CompletionListener() {
@Override
public void onComplete(boolean success) {
Log.i(TAG, "success: " + success);
}
});
```
Module tested against: SYN 3.4
This PR fixes an issue in the T&G manager where it was not setting the MediaTrack field correctly in the show.

Fix issue in setting MediaTrack in the T&G manager

---

android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
android/sdl_android/build.gradle
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/util/VersionTest.java

Fixes #1551 
To smoke test the PR: compile Hello Sdl Android, connect to Core, and make sure it connects successfully 
Module tested against: Core 7.0
This PR:
- Update Gradle plugin to the current latest version (4.1)
- Add `VERSION_NAME` as a variable in `build.gradle` to force Gradle to add that var the `BuildConfig` so the Android library can use it

Fix Gradle 4.1 compatibility issue

---

base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java
base/src/main/java/com/smartdevicelink/managers/lifecycle/RpcConverter.java

Fixes part of #1541 
- Added code to the RPC converter to handle legacy RPCs that no longer have classes associated with them
- Added logic to process the legacy PTU RPCs as newer, still supported RPC classes
* Fixes issue where policy table updates wouldn't occur on older systems

Add code to handle legacy PTU (v4.12)

---

base/src/main/java/com/smartdevicelink/managers/screen/BaseTextAndGraphicManager.java

Fixes part of #1541 
This PR is **[ready / not ready]** for review.
This PR makes **[no / minor / major]** API changes.
Added the missing set for media track when extracting text lines from a show request.
* Media track will now properly be set for all systems that use it

Fix missing media track field (v4.12)

---

base/src/main/java/com/smartdevicelink/protocol/SdlProtocolBase.java

Fixes #1574 
Security should be set up to see the errors. So it is better to test with test suite.
modify the testSuite so that you can call `sdlManager.dispose()` I added it to `appInfo` menu item
Test 1)
Connect your testSuite to core and open the application on core.
Now that the SDL service is started you can call `sdlManager.dispose()` and in the logs you should no longer observer the following log messages:
```
E/BaseEncryptionLifecycleManager: RC_5.0.0: onServiceError, session Type: NAV, reason: Transport disconnected
E/BaseEncryptionLifecycleManager: RC_5.0.0: onServiceError, session Type: PCM, reason: Transport disconnected
```
Test 2)
Make sure you set the test suite to type Navigation.
Connect your testSuite …

Add map to track which transports started a service

---

android/sdl_android/src/main/java/com/smartdevicelink/managers/screen/TextAndGraphicManager.java
base/src/main/java/com/smartdevicelink/managers/BaseSdlManager.java
javaSE/javaSE/src/main/java/com/smartdevicelink/managers/screen/TextAndGraphicManager.java

Fixes #1579 
Core version module tested against: 7.0
This PR changes the blank artwork used to show no artwork to be persistent rather than ephemeral.

Change T&G BlankArtwork to persistent artwork

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/proxy/RPCStructTests.java
base/src/main/java/com/smartdevicelink/proxy/RPCStruct.java

Fixes #116
Added Unit tests to RPCStructTests to verify new method behaviors
This PR adds methods to the RPCStruct class to override the Clone, Equals, and hashCode methods.
RPCStruct now implements Clonable and the `clone()` method will create a deepCopy of RPCStruct when called.
`equals()` is now overriden and can be used to compare two RPCStruct objects
`hashCode()` will return the hashCode of the store in the RPCStruct

Override Clone, Equals, and hashcode for RPCStruct

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/file/FileManagerTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/lifecycle/SystemCapabilityManagerTests.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/file/FileManager.java
base/src/main/java/com/smartdevicelink/managers/ISdl.java
base/src/main/java/com/smartdevicelink/managers/file/BaseFileManager.java
base/src/main/java/com/smartdevicelink/managers/file/DeleteFileOperation.java
base/src/main/java/com/smartdevicelink/managers/file/DispatchGroup.java
base/src/main/java/com/smartdevicelink/managers/file/FileManagerCompletionListener.java
base/src/main/java/com/smartdevicelink/managers/file/ListFilesOperation.java
base/src/main/java/com/smartdevicelink/managers/file/SdlFileWrapper.java
base/src/main/java/com/smartdevicelink/managers/file/UploadFileOperation.java
base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java
javaSE/javaSE/src/main/java/com/smartdevicelink/managers/file/FileManager.java

Fixes #1572  & #1580 
Unit tests have been updated to test the new `FileManager`
Core version tested against : 7.0.0
This PR refactors `FilesManager` to:
- Split the code into multiple operations and run the operations using transaction queues
- Update sending big files logic to split the data into multiple RPCs if the data size exceeds the MTU site

Refactor FileManager to use queues 

---

base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PresentChoiceSetOperation.java

Fixes #1593 
The PR can be testing using the sample code that is included on the issue page
This PR updates `PresentChoiceSetOperation` to set `AutoCompleteText` in addition to `AutoCompleteList` to make the feature backward compatible with old head units that don't support `AutoCompleteList`.

Set AutoCompleteText in PresentChoiceSetOperation

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/RPCGenericTests.java

Fixes #1597 
Added ignore annotation to `RPCGenericTests`
This PR adds `Ignore` annotation to `RPCGenericTests` so they don't run automatically on every push. Because the `RPCGenericTests` will keep failing if the state of the java code doesn't match the state of the master branch for rpc_spec. The tests can still be run manually at the end of every release when java code and master branch for rpc_spec are in sync.

Ignore RPCGenericTests

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/audio/AudioStreamManagerTest.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/audio/AudioDecoderCompat.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/audio/AudioDecoderCompatOperation.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/audio/AudioStreamManager.java
base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java

Fixes #1596
To smoke test the PR you will need to test audio streaming with either of the following two options: 
- Test on a phone that has API < 21 
- Test on a new phone and force the pre 21 decoder logic by manually changing the decoder from `AudioDecoder` to `AudioDecoderCompat` for newer phones on this line:
https://github.com/smartdevicelink/sdl_java_suite/blob/5e80169552e4f51ec8d9d083a01f52678545342f/android/sdl_android/src/main/java/com/smartdevicelink/managers/audio/AudioStreamManager.java#L438
Core version / branch / commit hash / module tested against: Core 7.0 & SYNC 3.4
This PR refactors `AudioDecoderCompat` to use Taskmaster to run decoding operations instead of creating a new thread every time.

Use TaskMaster in AudioDecoderCompat

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/requests/SetMediaClockTimerTests.java
base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java
base/src/main/java/com/smartdevicelink/proxy/rpc/SetMediaClockTimer.java

Fixes #1147 
Add the following code to Hello SDL and adjust the CountRate and ensure the MediaClockTimer reflects this countRate on the HMI
```
SetMediaClockTimer mediaClockTimer = new SetMediaClockTimer().countUpFromStartTimeInterval(30, 253, 
AudioStreamingIndicator.PAUSE);
mediaClockTimer.setCountRate(0.25f);
sdlManager.sendRPC(mediaClockTimer);
```
Core version / branch / commit hash / module tested against: [https://github.com/smartdevicelink/sdl_core/pull/3597]
HMI name / version / branch / commit hash / module tested against: [https://github.com/smartdevicelink/generic_hmi/pull/329]
Adds CountRate to the `SetMediaClockTimer` RPC

Add Changes from proposal for CustomPlaybackRate

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/streaming/video/SdlRemoteDisplayTest.java
android/sdl_android/src/main/java/com/smartdevicelink/streaming/video/SdlRemoteDisplay.java

Fixes #858
Core version tested against: Core 7.0
This PR replaces the usage of refresh handler in `SdlRemoteDisplay` with `ScheduledExecutorService` which runs on a different thread and has a specific API to run logic repeatedly at a preset rate.

Remove handler from SdlRemoteDisplay

---

base/src/main/java/com/smartdevicelink/proxy/rpc/Show.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/TextFieldName.java

Fixes #1606 
n/a
n/a
Deprecated MediaClock in Show.java and TextFieldName.java according to rpc spec changes https://github.com/smartdevicelink/rpc_spec/pull/309
* Deprecated MediaClock in Show.java and TextFieldName.java

Deprecate mediaClock

---

base/src/main/java/com/smartdevicelink/streaming/video/VideoStreamingParameters.java

Fixes #1611 
VideoStreamingParameters.update will now set a default value for resolution if it was null before trying to assign a new resolutionHeight or resolutionWidth
This will prevent the update method from trying to call setResolutionHeight or setResolutionWidth on a nullObjectReference

Prevent potential npe on resolution

---

android/sdl_android/src/main/java/com/smartdevicelink/encoder/VirtualDisplayEncoder.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/video/VideoStreamManager.java
base/src/main/java/com/smartdevicelink/streaming/video/VideoStreamingParameters.java

Fixes #1569 
This PR does not include additional Unit Tests.
Based on SDL 0274 enabled Core and HMI, verified that video streaming works correctly.
Core version / branch / commit hash / module tested against: Core feature/issue-3243 branch; commit #3934b0d8804fc658ccca96f5ce558b9987255f4e.
HMI name / version / branch / commit hash / module tested against: Xevo custom HMI
Implement SDL 0323: Align vide streaming parameters with VideoStreamingCapability
* No breaking changes.
* This implements issue #1569.
* No bug fixes.
None

Implement SDL 0323: Align video streaming parameters with VideoStreamingCapability

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/lifecycle/SystemCapabilityManagerTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/TextFieldNameTests.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/TextFieldName.java

Fixes #1367 
Additions were made to unit test.
Implements proposal [SDL 0305](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0305-homogenize-textfieldname.md) which Homogenizes the Enum TextFieldName in HMI_API.xml with MOBILE_API.xml in the Rpc spec.
* Adds  timeToDestination, and turnText to TextFieldName enum.

SDL-0305 Homogenize TextFieldName

---

android/hello_sdl_android/src/main/java/com/sdl/hellosdlandroid/SdlService.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/SdlManagerTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/streaming/MockInterfaceBroker.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/SdlManagerListener.java
android/sdl_android/src/main/java/com/smartdevicelink/session/SdlSession.java
base/src/main/java/com/smartdevicelink/managers/BaseSdlManager.java
base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java
base/src/main/java/com/smartdevicelink/protocol/SdlProtocolBase.java
base/src/main/java/com/smartdevicelink/protocol/enums/ControlFrameTags.java
base/src/main/java/com/smartdevicelink/proxy/rpc/RegisterAppInterfaceResponse.java
base/src/main/java/com/smartdevicelink/session/BaseSdlSession.java
base/src/main/java/com/smartdevicelink/session/ISdlSessionListener.java
base/src/main/java/com/smartdevicelink/util/SystemInfo.java
javaEE/hello_sdl_java_ee/src/main/java/com/smartdevicelink/SdlService.java
javaSE/hello_sdl_java/src/main/java/com/smartdevicelink/java/SdlService.java
javaSE/javaSE/src/main/java/com/smartdevicelink/managers/SdlManagerListener.java
javaSE/javaSE/src/main/java/com/smartdevicelink/session/SdlSession.java

Fixes part of #1588 
- Updated unit tests to handle the new API updates
- [Core version](https://github.com/LuxoftSDL/sdl_core/tree/feature/sdl_0293_enable_oem_exclusive_apps_support)
- [HMI](https://github.com/LuxoftSDL/sdl_hmi/tree/feature/sdl_0293_enable_oem_exclusive_apps_support)
- Added updates to implement part of the evolution proposal SDL-0293
- The changes included this PR reflect only the protocol level changes up to the manager layer APIs. A second PR is necessary to implement the Android specific router service feature of the proposal.
- The `SdlSession` will now extract the `SystemInfo` from the `StartSerivceACK` for the RPC service and pass that to the `LifecycleManager`. There the LCM will pass it to the …

[SDL-0293] OEM Exclusive App Support - Protocol & Manager layers

---

base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseMenuManager.java

Fixes #1623 
N/A
Create a menuCell and set the secondartText and tertiaryText to an empty string, When the menuCells are sent to core, all menuCells should be uploaded correctly
If the secondaryText or tertiaryText field of a MenuCell is set to an empty string, the BaseMenuManager will replace the value with null so core can support it.

Fix empty string bug with MenuCell text fields

---

base/src/main/java/com/smartdevicelink/proxy/rpc/BodyInformation.java
base/src/main/java/com/smartdevicelink/proxy/rpc/DisplayCapabilities.java
base/src/main/java/com/smartdevicelink/proxy/rpc/GetVehicleData.java
base/src/main/java/com/smartdevicelink/proxy/rpc/Show.java
base/src/main/java/com/smartdevicelink/proxy/rpc/SubscribeVehicleData.java
base/src/main/java/com/smartdevicelink/proxy/rpc/UnsubscribeVehicleData.java
generator/templates/base_template.java
generator/templates/javadoc_version_info.java

Fixes #1626 
This PR:
- Updates the `@deprecated` keyword in class Javadoc to `@property-deprecated` to prevent Android Studio from marking the whole class as deprecated if only one property in the class is deprecated.
- Updates the RPC Generator to generate the correct deprecated annotations.

Fix deprecated keyword issue in class javadoc

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/StaticIconNameTests.java
base/src/main/java/com/smartdevicelink/proxy/rpc/enums/StaticIconName.java

Fixes #1632
Updated for the new enum value
This PR will deprecate the `AUXILLARY_AUDIO` value and add the `AUXILIARY_AUDIO` value in `StaticIconName.java`

Fix spelling of "Auxillary"

---

android/sdl_android/src/main/java/com/smartdevicelink/managers/video/VideoStreamManager.java

- Setup encryption in Core & HMI
- Start encrypted video stream from the app
- Make sure encrypted NAV service is started and that packets get encrypted before they get sent to Core
Core version / branch / commit hash / module tested against: 7.1.0 RC
This PR fixes an issue in `startRemoteDisplayStream()` where the incorrect `isEncrypted` param is passed instead of `encrypted` param

Fix issue in passing  encrypted param to startRemoteDisplayStream()

---

android/sdl_android/src/main/java/com/smartdevicelink/managers/video/VideoStreamManager.java

N/A
Try to stream video with both videoStreamingRanges set at `new VideoStreamingRange(null, null, 0.0, null, null);`
Core version / branch / commit hash / module tested against: Core 7.1
HMI name / version / branch / commit hash / module tested against: 5.5.0
Updated so that 0.0 is considered a valid minDiagonal size

Developer can set minDiagonal to 0 in VideoStreamingRange

---

base/src/main/java/com/smartdevicelink/managers/screen/BaseScreenManager.java

Fixes #1643 
1. Set soft button via screen manager, send an alert with a softButton via the AlertManager, verify that the correct listeners get called when you click on the Alert softButtons and the softButtons set via the screenManager.
Core version / branch / commit hash / module tested against: Core 7.1 RC
HMI name / version / branch / commit hash / module tested against: generic HMI
This PR fixes the issue that would cause the ScreenManager's sub-managers to generate overlapping button IDs that trigger the same button listeners. The AlertManager will now consider the SoftButtonManager's button IDs and vice versa.

Fix issue of overlapping softButton ID's in the screenManager

---

base/src/main/java/com/smartdevicelink/protocol/SdlProtocolBase.java
base/src/main/java/com/smartdevicelink/transport/SdlPsm.java

Fixes #1642 
The library is now setup to correctly encrypt multi frame packets by encrypting each frames payload rather than the entire payload first. The first frame will also no longer be marked as encrypted because it is not. Also fixed the logic for single frame messages when they were approaching the max size of a TLS record but still under the MTU. Receiving encrypted multiframe packets will no longer crash the library as the data size is reset to the decrypted data size before parsing further. 
* Fixed incorrect encryption flag being set for first frame
* Fixed encryption flow to match what is expected and frankly possible with TLS
* Fixed incoming encrypted multiframe packets from crashing the app

Implement multiframe encryption correctly

---

base/src/main/java/com/smartdevicelink/protocol/SdlProtocolBase.java

1. Setup encryption between all platforms
2. Require PutFile to be encrypted
3. Set MTU to lower value than encryption max data size (16,091)
4. Encrypt RPC service
5. Send a PutFile manually (not through manager)
6. Observe the frame size is that of the set MTU and not of the encryption max data size
Added logic to take the minimum between the service type MTU and the max encryption data size. Prior to this PR, the library would use the max encryption data size even if the MTU had been set lower.
* Fixed the corner case that an IVI can support encryption but its MTU is lower than the ~16k bytes.

Fix encryption mtu corner case

---

android/hello_sdl_android/src/main/AndroidManifest.xml
android/sdl_android/src/main/java/com/smartdevicelink/util/IntegrationValidator.java

1. Install HelloSDL Android application
2. Connect with head unit over bluetooth
3. Observe connection is established and HelloSDL is hosting the router service
1. Create an additional Android app with SDL integration and install alongside HelloSDL
2. Connect with head unit over bluetooth
3. Observe connection is established and only one app is hosting the router service. 
If you remove the queries section from the manifest of either app it should be observed that two router services are started instead, one by each app.
Android 30 introduced a new permission `QUERY_ALL_PACKAGES` that was necessary to query the Android device for other apps. While adding hte permission into the manifest was a simple update, a recent …

Implement queries instead of blanket QUERY_ALL_PACKAGES permission

---

android/sdl_android/src/main/java/com/smartdevicelink/managers/video/VideoStreamManager.java
android/sdl_android/src/main/java/com/smartdevicelink/streaming/video/SdlRemoteDisplay.java

Added a flag to prevent a listener from being added multiple times and with each time being added, it gets an immediate callback which therefore causes the video stream to stop and restart. This caused issues when the IVI simply displays an alert or dialog over the stream which would move the app to HMI_LIMITED but cause the stream to stop and restart.
Also added a check for null in the remote display class as it was simply just catching the NPE and printing it out in normal logs. It will no longer cause an NPE and exceptions will be logged through the `DebugTool` instead of `Log`.
* Incorrectly restarting stream when moving between HMI states
* Avoidable NPE in the remote display class

Fix video streaming incorrect restart

---

README.md
android/README.md
javaEE/javaEE/README.md
javaSE/javaSE/README.md

N/A
N/A
Update READMEs to use mavenCentral repository and version 5.1

Update readmes for mavenCentral

---

base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java

Fixes #1658 
Based on the reported issue the testing revolved around adding and removing service listeners which happens during connection and disconnection. So simply connecting and disconnected on different transports with different types of apps was used.
The `BaseLifecycleManager` made an assumption that the session variable would always be not null, however, it is set to null in the `stop()` method. Therefore it is possible that the session instance is null when operations are attempted on it. Added a synch block around the check of the session instance with the lock as the LCM itself, the same that is used in the `stop()` method.
We should consider this for a hotfix, especially if there are any other issues we need …

Add null checks and synch around session in LCM

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

Fixes #1239 
The issue itself not reproducible so to test this code change simply perform quick transport connection/disconnections with and without multiple transports connected. Also test apps registering and unregistering quickly.
There is not a way to reproduce the issue, but this fix took into consideration that it could be a timing/race condition issue as well as added a try/catch block as an additional safeguard.
This PR should be considered for a hotfix if one is being released.
* Added missing synchronization blocks around code in question
* Added extra logic checks before casting 
* Added try/catch block as a final safeguard

Attempt to fix unreproducible ClassCastException

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/menu/VoiceCommandTests.java
base/src/main/java/com/smartdevicelink/managers/screen/menu/VoiceCommand.java

Fixes #1664 
Added unit test for lists with duplicate strings
Test sending a list of voiceCommands where there are duplicate strings
You should now only see one voice command for each unique string you set
Core version / branch / commit hash / module tested against: Manticore
HMI name / version / branch / commit hash / module tested against: Manticore
This PR adds a helper function to VoiceCommand.java that will remove any duplicate strings when setVoiceCommands gets called. This PR adds the appropriate unit tests

add removceDuplicate helper method to VoiceCommand

---

android/sdl_android/src/main/java/com/smartdevicelink/streaming/StreamPacketizer.java
base/src/main/java/com/smartdevicelink/streaming/video/RTPH264Packetizer.java

Fixes #1667
N/a
Follow steps outlined in issue using java test suite
Core version / branch / commit hash / module tested against: 7.1
HMI name / version / branch / commit hash / module tested against: sdl_hmi 5.5.1
When the MaximumRpcPayloadSize is greater than the max queue size the queue capacity was being set to a decimal or 0 value. Adding a math.max to make sure it is always atleast 1.

Make sure mOutputQueue capacity is never < 1

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/transport/SdlPsmTests.java
base/src/main/java/com/smartdevicelink/transport/SdlPsm.java

Fixes #1678 
Additional tests were added to test the SdlPsm.java class and some tests were refactored. These included more corner case issues as provided in #1678. 
Basic smoke testing can be done to ensure the packet state machine still works as intended. It is difficult to perform tests that would have actually broken the PSM so we rely on the unit tests for those scenarios.
- Surrounded the base operation of the SdlPsm class in a try/catch that will set the state to ERROR state and safely exit. This prevents exceptions from being thrown in developer's applications. A log is written out through the DebugTool
- Added a check for correct service types. This helps with recovery tremendously. 
- Added better dataSize …

Improve packet state machine

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexBluetoothTransport.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/utl/SdlDeviceListener.java

Tested with Sync Gen3 TDK
Performed tests as outline with the original SdlDeviceListener proposal in PR #1384 
- Remove all SDL apps from phone, if HelloSDL was installed be sure to clear storage prior to uninstall
- Turn on bluetooth adapter on phone.
- Allow BT to connect (A2DP); pair with IVI if necessary.
- Install Hello SDL and ensure it is the only SDL app installed.
- Observe through logs that the SDL Listener was started and is currently listening on an RFCOMM channel.
- IVI should connect with SDL Listener's RFCOMM channel, this will cause the listener to close the connection and attempt to start the router service. (Might need to perform SDP Query / press "Find new apps"
- Observe the router service …

Allow SdlDeviceListener to start after BT connection

---

base/src/main/java/com/smartdevicelink/exception/SdlException.java
base/src/main/java/com/smartdevicelink/managers/BaseSdlManager.java
base/src/main/java/com/smartdevicelink/managers/file/UploadFileOperation.java
base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java
base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseMenuManager.java
base/src/main/java/com/smartdevicelink/proxy/RPCStruct.java
base/src/main/java/com/smartdevicelink/proxy/rpc/OnSystemRequest.java
base/src/main/java/com/smartdevicelink/transport/SiphonServer.java
base/src/main/java/com/smartdevicelink/util/FileUtls.java

Fixes #1687 
This PR makes exception reporting consistent in that the library uses the `DebugTool` only to print out known exceptions that occur. This also gives the chance to add a little more description to the occurence. 
* `DebugTool.e()` is used instead of `e.printStackTrace()` to report/print exceptions

Move exception reporting to debugtool

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/menu/VoiceCommandManagerTests.java
base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseVoiceCommandManager.java

Fixes #1675
Unit tests were added to VoiceCommandManagerTests.java
Test sending voice commands with extra white space on the front and back for example: "  command one  ", verify that extra white space is removed and the uploaded voice command is:  "command one"
Test sending two voice commands one with an empty string set like " " and one normal one, verify that only the normal voice command is sent to the update operation.
Test sending voice commands only with empty strings, like "   ". Verify that an error message is printed out in the logs: "New voice commands are invalid, skipping..."
Core version / branch / commit hash / module tested against: Core 7.1.1
HMI name / version / branch / commit hash / module tested …

Fix for voice command that contains no string should be removed

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/lifecycle/SystemCapabilityManagerTests.java
base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java

Fixes #1690
Added unit tests to test the workaround logic 
On Sync 3.0:
1. Connect a media app, it will start on the media template
2. Change the layout to something else, like textAndGraphic
3. Change the layout back to MEDIA
4. Try to show another image and confirm it appears 
Core version / branch / commit hash / module tested against: 7.1.1
HMI name / version / branch / commit hash / module tested against: Generic HMI 0.10.0
This PR updates the `LifecycleManager` to replace the incorrect capabilities that are included in the `SetDisplayLayoutResponse` for MEDIA apps with the ones from `RegisterAppInterfaceResponse` as a workaround to fix a bug in SYNC3.
Workaround for a Ford Sync 3 bug where doing `SetDisplayLayout` to …

Update LCM to workaround Sync 3 bug with media capabilities 

---

base/src/main/java/com/smartdevicelink/managers/file/BaseFileManager.java

Fixes #1692 
1. Send a graphic of type persistent
2. Send the same graphic with type non-persistent
3. Kill the app
4. Re-open and connect the app to the same Core instance (e.g. Manticore)
5. Send the graphic with type non-persistent and confirm that the image appears
Core version / branch / commit hash / module tested against: Core 7.1.1
HMI name / version / branch / commit hash / module tested against: 0.10.0
This PR fixes an issue in `FileManager.hasUploadedfile()` method where it incorrectly returns `false` when the file is uploaded

Fix issue in hasUploadedFile() where it incorrectly returns false when the file is uploaded 

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/TransportManager.java

Fixes #1703 
This race condition is difficult to reproduce. The main tests should be that the legacy mode continues to work. Also have the library close the connection to ensure that still works at closing the connection properly. 
There was a possible race condition where two sections of code could modify the legacy transport and set it to null. This could cause NPEs to occur even after null checks. The code was refactored a little to simple call into the synchronous method that exits out of legacy mode. This means the only time the legacy transport is created or set to null will be in the synchronized enter and exit legacy mode methods.
* Should fix chance of a race condition modifying same variable to cause NPE

Move legacy mode modifications to single points

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/menu/VoiceCommandManagerTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/menu/VoiceCommandUpdateOperationTests.java
base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseVoiceCommandManager.java
base/src/main/java/com/smartdevicelink/managers/screen/menu/VoiceCommand.java
base/src/main/java/com/smartdevicelink/managers/screen/menu/VoiceCommandUpdateOperation.java

Fixes #1676 
Unit test were added in `VoiceCommandUpdateOperationTests.java`
TEST:
Test 1:
VoiceCommandA = "command one"
VoiceCommandB = "command two"
Upload A and B on startup
VoiceCommandC = "command one"
VoiceCommandD = "command four"
Upload C and D in a menuSelection listener.
Verify Voice commands on HMI are "command one" and "command four"
Verify that when "command one" is selected the listener for VoiceCommandC is triggered.
Test2: 
Upload A on startup
VoiceCommandA = "command one"
Upload C in a menuSelection listener.
VoiceCommandC = "command one"
Verify that when "command one" is selected the listener for VoiceCommandC is triggered.
Test3:
Upload A on startup
VoiceCommandA = "command one"
After A is …

Fix to avoid deleting and setting identical voice commands

---

base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java

Fixes #1697 
Tests performed:
- Minimum protocol version check fail
- Minimum RPC version check fail
- `SystemInfo` check fail
- Sending an `UnregisterAppInterface` and receiving a response
- Receiving an `OnAppInterfaceUnregistered` notification. (Triggered via SDL_HMI ignition cycle)
Test code can be used to trigger an `OnAppInterfaceUnregistered` from the library. In the `BaseLifecycleManager` where RPCs are received, after the RAI processes the following code can be added to trigger a sending of the notification. 
```java
new Handler(Looper.getMainLooper()).postDelayed(new Runnable() {
@Override
public void run() {
Log.d(TAG, "Sending OnAppInterfaceUnregistered. Icon may not clear from IVI, but service on phone should …
```

Add onClose callbacks after LCM clean() calls

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/lifecycle/SystemCapabilityManagerTests.java
base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseSystemCapabilityManager.java

Fixes #1705 
Unit test were added in SystemCapabilityManagerTests.java
Tested that if the HMI gives us NON_MEDIA as a template, the library converts it to "NON-MEDIA"
with: 
```
sdlManager.getSystemCapabilityManager().getDefaultMainWindowCapability().getTemplatesAvailable().contains("NON-MEDIA");
```
Core version / branch / commit hash / module tested against: 7.1.1, 
HMI name / version / branch / commit hash / module tested against: Generic_HMI 0.10.0
Added "NON-MEDIA" to templatesAvailable In a case where sync's response for templatesAvailable had "NON_MEDIA" instead
* Added "NON-MEDIA" to templatesAvailable In a case where sync's response for templatesAvailable had "NON_MEDIA" instead

Fix PredefinedLayout.NON_MEDIA not found in templatesAvailable

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/lockscreen/LockScreenManagerTests.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/LockScreenManager.java

Fixes #1695 
1. Set lockscreen displayMode to ALWAYS
2. Send DriverDistraction to the app with `DD_OFF` and `lockScreenDismissalEnabled = true`
3. The user should be shown a dismissible lockscreen
4. Dismiss the lockScreen
5. Send DriverDistraction to the app with `DD_ON` and `lockScreenDismissalEnabled = false`
6. The lockscreen should be launched again without a dismiss message
Core version / branch / commit hash / module tested against: Core 7.1.1
HMI name / version / branch / commit hash / module tested against: 0.10.0
This PR fixes an issue in `LockscreenManager` that prevents lockscreen from showing again after dismissal if a DD notification is received where `DismissalEnabled` is `false`

Make lockscreen show again after dismissal if a DD notification is received where DismissalEnabled is false

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/menu/MenuManagerTests.java
base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseMenuManager.java

Fixes #1688 
Remove ImageFilds `menuCommandSecondaryImage` and `menuSubMenuSecondaryImage` from generic HMI as a supported field. To do this you need to remove all instances of them in `src/js/controllers/DisplayCapabilities.js` and rebuild the hmi
Test 1:
Step 1. With ImageField "menuCommandSecondaryImage" removed as a supported field from generic_hmi, Upload a menu with a normal cell that uses the same image for primary and secondary.
Verify: Only primary image is uploaded on menuCell.
Test 2:
With ImageField "menuSubMenuSecondaryImage" removed as a supported field from generic_hmi, Upload a menu with a menu cell that has subCells that uses the same image for primary and secondary.
Verify: Only primary image is …

Fix MenuManager sending secondary image with menuCells when menuCommandSecondaryImage is not supported

---

base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java

- Send a `SetDisplayLayout` without a template 
- Make sure the app doesn't crash
Core version / branch / commit hash / module tested against: 7.1.1
This PR fixes a potential NPE in `LifecycleManager` if the app sends a `SetDisplayLayout` without setting a template. This scenario shouldn't happen in real life because a template is required but it shoud still not crash the app.

Fix potential NPE in LifecycleManager

---

.github/workflows/android.yml
android/sdl_android/src/androidTest/java/com/smartdevicelink/test/streaming/video/SdlRemoteDisplayTest.java

This PR:
- Adds the new `workflow_dispatch` event to allow manually triggering a CI run 
- Fix `testTouchEvents()` test that fails sometimes randomly when the tests are run by the CI

Add a way to manually trigger the Github CI

---

android/sdl_android/src/main/java/com/smartdevicelink/encoder/VirtualDisplayEncoder.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/LockScreenManager.java
android/sdl_android/src/main/java/com/smartdevicelink/protocol/heartbeat/HeartbeatMonitor.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexBluetoothTransport.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/TransportManager.java

Fixes #1696
N/A
Smoke Test app still connects and videoStreaming still works
The Handler constructor with no parameters has now been depreacted. To avoid using deprecated methods this PR will update the Handler constructors to take a Looper as a parameter. In the VirtualDisplayEncoder if we receive a message terminate then we quit the looper, in this case we will use myLooper rather than getMainLooper as we cannot quit the main thread.

Update Handler constructors from deprecated versions

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/video/HapticInterfaceManagerTest.java

There seems to be a strange issue with Mockito that happens randomly sometimes when the tests try to mock `View` or `ViewGroup` classes.
This PR rewrites `HapticInterfaceManagerTest.createViews()` to create the same views without mocking `View` or `ViewGroup` classes which makes the tests more reliable.

Fix Mockito exception

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

Fixes #1741 
Tested connecting to tdk via Bluetooth having two other apps connect to test apps routerService
Core version / branch / commit hash / module tested against: Sync 3.0
HMI name / version / branch / commit hash / module tested against: Sync 3.0
Fix IndexOutOfBoundsException that can happen in `SdlRouterService.getCompatPrimaryTransport()`
* Fit IndexOutOfBoundsException in SdlRouterService

Fix IndexOutOfBoundsException in SdlRouterService

---

android/sdl_android/build.gradle
android/sdl_android/gradle.properties
javaEE/javaEE/build.gradle
javaEE/javaEE/gradle.properties
javaSE/javaSE/build.gradle
javaSE/javaSE/gradle.properties

Fixes #1763 
This PR updates the gradle setup for android, javaSE & javaEE to read the version from one single file called `VERSION` instead of having 4 different files that needed to be updated separately. 
1. Update the version in `VERSION` file to any unique version (like `5.3.0_xyz` for example) 
2. Run `./gradlew build` for javaSE
3. Upload the `JavaSE` binary to maven central staging 
4. Confirm that the generated `BuildConfig` and uploaded library still use the old version that was set in `gradle.properties`
5. Repeat the same steps for Android library

Update android, javaSE & javaEE gradle setup to read version for one file 

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/test/protocol/SecurityQueryPayloadTests.java
base/src/main/java/com/smartdevicelink/protocol/SecurityQueryPayload.java
base/src/main/java/com/smartdevicelink/session/BaseSdlSession.java

Fixes #1753
Updated SecurityQuery Unit Tests
Verify Encryption Still works.
---and---
Force sendHandshake to fail and verify the library has the json payload set with the error message information
Core version / branch / commit hash / module tested against: Core 8.0
HMI name / version / branch / commit hash / module tested against: Sdl HMI 5.6
This PR updates SecurityQueryPayload implementation to make sure the JSON data and error Byte are set when responding with an error notification to Core

Update SecurityQueryPayload to include json data

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

Fixes #1661
This PR makes **[no / minor / major]** API changes.
n/a
Run test 9.008 in the 5.3 SDL_Android Test Plan on sheet Multiplexing Security Tests.
Core version / branch / commit hash / module tested against: Synce 3.0
HMI name / version / branch / commit hash / module tested against: Sync 3.0
Added Bluetooth adapter available check to RouterService for spp error notification. This prevents a rare edge case where when having connected Bluetooth and USB, you keep turning on and off Bluetooth, you can get the spp error notification.
* [Added Bluetooth adapter available check to RouterService for spp error notification.

Add Bluetooth adapter available check in RouterService for spp error notification 

---

base/src/main/java/com/smartdevicelink/proxy/rpc/ScrollableMessage.java
base/src/main/java/com/smartdevicelink/proxy/rpc/Slider.java

Fixes #1775
This PR makes no API changes.
N/A - This PR only changes documentation, not runnable code.
N/A - This PR only changes documentation, not runnable code.
Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: N/A
This PR adds the units (milliseconds) to the Javadoc comments related to timeouts in `ScrollableMessage`
* None
* Better documentation
* Fixes #1775
* None

Add timeout units to Javadoc comments

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/ScreenManagerTests.java
android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/SoftButtonManagerTests.java
base/src/main/java/com/smartdevicelink/managers/screen/SoftButtonObject.java
base/src/main/java/com/smartdevicelink/managers/screen/SoftButtonState.java

Fixes #1774
This PR adds a new public getter function to SoftButtonObject
- `testConstructSoftButtonObjectWithEmptyStateList()` passes if `getAttemptedToAssignEmptyStateList()` returns true after an empty state list is passed to the main primary constructor and fails otherwise.
- `testAssignEmptyStateListToSoftButtonObject()` passes if an `getAttemptedToAssignEmptyStateList()` returns true after an empty state list is passed to `setStates()` of an instance of `SoftButtonObject` that already has at least one state in its state list. 
- Constructed an instance of `SoftButtonObject` with a state list containing a single state, added it to a list of `SoftButtonObject`s, and attempted to display them to the Generic HMI using `ScreenManager`. Results: 
- That …

Fix soft button object invalid states

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/utl/SdlDeviceListener.java

Fixes #1780
This PR is **[not ready]** for review.
N/A
[List of tests performed against Core and behaviors verified]
Core version / branch / commit hash / module tested against: [INSERT]
HMI name / version / branch / commit hash / module tested against: [INSERT]
In `SdlDeviceListener` the `bluetoothTransport` and `bluetoothHandler` are only initialized if the device has not connected previously. In the event that the device has connected before the `bluetoothTransport` is not initialized because we get the relevant data from the shared preferences. If this is the case `bluetoothTransport` will not be initialized and will be null. If this is the case the `vehicleInfo` will be retrieved from the shared preferences instead and the logic to retrieve the …

Prevent NPE in SdlDeviceListener

---

base/src/main/java/com/smartdevicelink/protocol/SecurityQueryPayload.java

Fixes #1790 
N/A
Attempt to test Encrypted Video Streaming using an app with the app ID wrong_app_id and the default security lib
Observe this log when Encrypted Video Stream Fails
Security Query module internal error: INVALID_CERT
Core version / branch / commit hash / module tested against: release/8.1.0
HMI name / version / branch / commit hash / module tested against: Generic HMI release/0.12.0
There was a condition where we were cutting the bulk short by 1 byte. This should not happen so that condition was removed and the bulkdata will now be set to the appropriate size.

Make sure errorCode is not cut off

---

android/sdl_android/src/main/java/com/smartdevicelink/managers/SdlManager.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/lifecycle/LifecycleManager.java
base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java
javaSE/javaSE/src/main/java/com/smartdevicelink/managers/SdlManager.java
javaSE/javaSE/src/main/java/com/smartdevicelink/managers/lifecycle/LifecycleManager.java

This PR fixes some issues where the library is shutting down but the app wasn't unregistered from the IVI properly. It also fixes a SYNG 4 bug that caused incorrect app closing after a reregister.
* Fixed properly sending an UnregisterAppInterface when the LCM is shutting down
* Removed redundant code that closed the RPC service before cleaning the whole LCM
* Removed code from the UnregisterAppInterface response listener that caused issues with SYNC 4.
* Added a missing init call in the Java SE LCM

Fix LCM to close down properly

---

base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseVoiceCommandManager.java

Fixes #1798 
This PR makes no API changes.
N/A - This PR only adds logging
1. Create `VoiceCommand` containing no command strings
2. Attempt to send the `VoiceCommand` to an HMI using `VoiceCommandManager`
3. Observe debug logs
Expected Results: The `VoiceCommand` fails to send and a warning is logged
Observed Results: The `VoiceCommand` fails to send and a warning is logged
```markdown
- Ford TDK 3.4 (19353_DEVTEST_r133796)
- SDL Core v7.1.1 SDL HMI 5.5.1
- SDL Core v8.1.1 SDL HMI 5.7
```
Adds more logging to `BaseVoiceCommandManager.removeEmptyVoiceCommands()`
* None
* None
* #1798

Add error logging when removing empty voice commands and voice command strings

---

base/src/main/java/com/smartdevicelink/managers/screen/PresentAlertOperation.java

Fixes #1800
This PR makes no API changes.
N/A
On Core, I ran the following code in `testBlank()` of a local clone of sdl_test_suite_java and a modified local copy of sdl_java_suite in which `PresentAlertOperation.supportSoftButtonImages()` is public.
<details>
<summary>Test Code</summary>
```java
AlertView.Builder builder = new AlertView.Builder();
builder.setText("Test Alert");
AlertView view = builder.build();
//test null capability
try {
WindowCapability windowCapability = null;
//WindowCapability windowCapability = new WindowCapability();
//windowCapability.setSoftButtonCapabilities(Collections.emptyList());
//windowCapability.setSoftButtonCapabilities(Collections.singletonList(null));
PresentAlertOperation presentAlertOperation = new …
```

Add multiple checks to supportsSoftButtonImages()

---

android/sdl_android/src/main/java/com/smartdevicelink/encoder/VirtualDisplayEncoder.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/video/VideoStreamManager.java

Fixes #1803 
This PR makes no API changes.
Ran Existing CI Tests
Tested on Samsung Galaxy S21 5G, Android 12 using sdl_test_suite_java
1. Connect an Android SDL Navigation app to SDL Core with either sdl_hmi or generic_hmi
2. Start streaming a video to the HMI
3. Switch the video stream to a resolution lower than 320x240 (ex: 400x100)
4. Attempt to stream at a supported resolution
Expected results: The low resolution video fails to play, an error is printed. Afterwards, the supported resolution plays successfully
Observed results: The low resolution video fails to play, an error is printed. Afterwards, the supported resolution plays successfully
Core version / branch / commit hash / module tested against: SDL Core release/8.1.0 …

Improve handling of unsupported resolutions

---

android/sdl_android/src/main/java/com/android/grafika/gles/Texture2dProgram.java
android/sdl_android/src/main/java/com/smartdevicelink/encoder/VirtualDisplayEncoder.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/video/VideoStreamManager.java

Fixes #1807 
Test:
Start a video stream to sdl_hmi
Using voice commands exit out of the app
Open app on HMI
Result:
You should be prompted by hmi to start streaming, click ok and video should stream.
Core 8.1 with sdl_hmi
Adds check to VideoStreamManager to check if HMI level is streamable before restarting video streaming, and added behavior for the stream to auto-restart when hmi is in a streamable state
* Fixes video stream manager form going into an unrecoverable state when it tries to start video streaming in a nonstreamable state

Fix auto restart video stream to ensure hmi level is streamable

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/SoftButtonManagerTests.java
base/src/main/java/com/smartdevicelink/managers/screen/BaseSoftButtonManager.java
base/src/main/java/com/smartdevicelink/managers/screen/SoftButtonReplaceOperation.java

Fixes #1738 
Unit tests were updated with the new parameter and one test was added in SoftButtonManagerTest
Tested sending a softbutton with an image, verifying that the image displays.
```
SoftButtonState softButtonState = new SoftButtonState("artworkTest", "Button", new SdlArtwork("testArtwork1", FileType.GRAPHIC_PNG, R.drawable.ic_sdl, true));
SoftButtonObject softButtonObject = new SoftButtonObject("jk", softButtonState, new SoftButtonObject.OnEventListener() {
@Override
public void onPress(SoftButtonObject softButtonObject, OnButtonPress onButtonPress) {
}
@Override
public void onEvent(SoftButtonObject softButtonObject, OnButtonEvent onButtonEvent) {
}
}); …
```

1738 - Soft button manager image upload fix 

---

base/src/main/java/com/smartdevicelink/proxy/rpc/AddCommand.java
base/src/main/java/com/smartdevicelink/proxy/rpc/AddSubMenu.java
base/src/main/java/com/smartdevicelink/proxy/rpc/BodyInformation.java
base/src/main/java/com/smartdevicelink/proxy/rpc/MenuParams.java
base/src/main/java/com/smartdevicelink/proxy/rpc/OnVehicleData.java
base/src/main/java/com/smartdevicelink/proxy/rpc/Show.java

Fixes #1819
CI Tests
N/A
This PR only updates documentation
This PR updates the Javadoc tables listed in #1819 to align with code and spec. In cases where the code and spec do not match, the Javadoc was changed to match the code.
N/A
N/A
* Fixes #1819

Update Javadoc tables to match code

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java

Fixes #1815 
Tested against Sync 3.0 with Android 12 device and Android 9 device.
Android 12 device: 
I was able to replicate the issue by using a delayed handler. I had to put the try-catch inside of the handler to catch it.
```
final Handler handler = new Handler(Looper.getMainLooper());
handler.postDelayed(new Runnable() {
@Override
public void run() {
try {
serviceIntent.putExtra(FOREGROUND_EXTRA, true);
DebugTool.logInfo(TAG, "Attempting to startForegroundService - " + System.currentTimeMillis());
setForegroundExceptionHandler(); //Prevent ANR in case the OS takes too long to start the service
context.startForegroundService(serviceIntent);
} catch (ForegroundServiceStartNotAllowedException e) {
Log.e(TAG, …
```

Android 12 Catch ForegroundServiceStartNotAllowedException 

---

android/hello_sdl_android/build.gradle
android/hello_sdl_android/src/main/AndroidManifest.xml
android/hello_sdl_android/src/main/java/com/sdl/hellosdlandroid/MainActivity.java
android/sdl_android/build.gradle

Fixes #1812 
n/a
POST_NOTIFICATIONS TESTS 
**1 app API 33 on Android 13 device**
Test 1:
1. App request POST_NOTIFICATIONS permission.
2. Accept permission
3. Connect to core
Results: Notifications appear and the app works as expected
Test 2:
1. App request POST_NOTIFICATIONS permission.
2. Click Don't Allow for permission.
4. Connect to core
Results: Notifications do not appear and the app works as expected
Test 3:
1. App request POST_NOTIFICATIONS permission.
2. Swipe away the request to allow notifications.
3. Connect to core
Results: Notifications do not appear and the app works as expected
Test 4:
1. App does not request POST_NOTIFICATIONS permission.
2. Connect to core
Results: Notifications do not appear and …

Bugfix/issue 1812 Android 13 Support

---

android/hello_sdl_android/build.gradle
android/hello_sdl_android/src/main/java/com/sdl/hellosdlandroid/SdlService.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/lifecycle/LifecycleManager.java
android/sdl_android/src/main/java/com/smartdevicelink/session/SdlSession.java

Fixes #1802 
_Note: method added to library scoped class and therefore no API was added._
N/A These tests need to be ran manually.
1. Set test app to Media using multiplexing (new HelloSdl build flavor: requiresAudioSupport)
2. Turn off bluetooth adapter on phone
3. Connect AOA through multiplexing, observe test app did not register
4. Turn on bluetooth and allow phone to connect to IVI
5. If app does not register automatically, open the manually and observe it did register
6. Turn off bluetooth adapter, observe app unregisters and is removed on the IVI apps screen
IVI Info: Sync Gen3
This PR addresses the issue of apps not unregistering when they require audio support, it is initially given, and then is removed. …

Bugfix/issue 1802 Unregister apps when audio output becomes unavailable

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/lifecycle/SystemCapabilityManagerTests.java
base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseSystemCapabilityManager.java

Fixes #1824 
Unit test were updated in SystemCapabilityManagerTests.java
Tested to verify that ScreenParams and MediaClockFormats from SystemCapabilityManager `DisplayCapabilities` matched `DisplayCapabilities` from RAIR.
Test retrieving DefaultMainWindowCapability from SystemCapabilityManager modifying it then retrieving it again from SystemCapabilityManager to verify that it was not modified in the manager. 
Core version / branch / commit hash / module tested against: Manticore v 2.10.0
HMI name / version / branch / commit hash / module tested against: Manticore v 2.10.0
When we get the new `DisplayCapability`, we update the old deprecated `DisplayCapabilities` based on the new `DisplayCapability`. When we do that, …

Bugfix/issue 1824 Add missing DisplayCapabilities info and window ID

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterStatusProvider.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/USBAccessoryAttachmentActivity.java

Fixes #1829 
N/A as these exceptions occur on random Android devices and are not easily reproducible outside of adding logic to make it happen.
N/A This only occurs because of Android having a bug when starting foreground services and isn't related to Core or the IVI directly.
Searched the project for any calls to `startForegroundService` and surrounded them with a try/catch. If an exception occurs it is passed to a method to handle it by logging out the reason for the exception.
* Prevent exceptions being thrown for Android's inability to properly time starting foreground services based on when the OS can start them instead of the time at which the `startForegroundService` is called initially.

Prevent exceptions being thrown for remaining startForegroundService calls

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/TextAndGraphicUpdateOperationTest.java
base/src/main/java/com/smartdevicelink/managers/screen/BaseTextAndGraphicManager.java
base/src/main/java/com/smartdevicelink/managers/screen/TextAndGraphicUpdateOperation.java

Fixes #1828
*Note: This branch has been tested for Android by Chloe, Julian Tested JavaSE
- `testOnShowFailBadDataDoesNotUpdateScreen()` : Tests the show failure branch within the `sendShow` method which notifies the `currentScreenDataUpdateListener` of an `errorState`.
- `testUpdateTargetStateWithErrorStateNullDoesNotUpdateCurrentScreen()`: Tests the `updateTargetStateWithErrorState` method to ensure that fields set to null will not be updated on the current screen.
- `testUpdateTargetStateWithErrorBadDataDoesNotUpdateCurrentScreen()` : Tests the `updateTargetStateWithErrorState` method to ensure that fields set to bad data will not be updated on the current screen.
- …

Bugfix/issue 1828 Good text failing

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/TextAndGraphicUpdateOperationTest.java
base/src/main/java/com/smartdevicelink/managers/screen/TextAndGraphicUpdateOperation.java

Fixes #1833 
I updated existing unit test in TextAndGraphicUpdateOperationTest
Tested updating the template and check currentScreenData in BaseTextAndGraphicManager after the update.
Core version / branch / commit hash / module tested against: Manticore
HMI name / version / branch / commit hash / module tested against: Manticore
This PR  adds a missing check in`TextAndGraphicUpdateOperation`  that would check for a template config after an update and add that to `currentScreenData` for the `TextAndGraphicManager`.  
* Adds a missing check in`TextAndGraphicUpdateOperation`  that would check for a template config after an update and add that to `currentScreenData` for the `TextAndGraphicManager`.

Update current screen data in T&G manager with template config

---

android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/PresentAlertOperationTest.java
base/src/main/java/com/smartdevicelink/managers/screen/PresentAlertOperation.java

Fixes #1835 
Unit test were updated in PresentAlertOperationTest.
Test sending Alert with Image via ScreenManager and verify that the image correctly appears.
Core version / branch / commit hash / module tested against: Manticore
HMI name / version / branch / commit hash / module tested against: Manticore
Changed check fileManager.hasUploadedFile to fileManager.fileNeedsUpload.
* Fixes incorrect conditional statement when creating AlertRPC so Images will appear correctly

Bugfix/issue 1835 AlertManager File upload fix

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java
android/sdl_android/src/main/res/values/sdl.xml

Fixes #1843 
N/A
- Installed app after RS was already connected and ensured that that app connected through SDL
- Additionally, can test my killing HelloSdl while RS connected using a button on screen and adding the following logic:
```java
findViewById(R.id.helloSdlButton).setOnClickListener(new View.OnClickListener() {
@Override
public void onClick(View v) {
try {
android.os.Process.killProcess(android.os.Process.myPid());
} catch (Exception e) {
e.printStackTrace();
}
}
});
```
After this occurs the app will be restarted and connect through the pings sent out by the RS.
Core version: SYNC 3
HMI name: SYNC 3
Ensured the `PendingIntent` object was contained in the intents that were sent out during pings and transport …

Add pending intent to ping intents

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java

Fixes #1845 
N/A
Tested if the SdlService exception specifically for not starting service in time was being handled.
Fix a typo in the uncaught exception handler that should only catch specific exceptions
* Fixed typo in if conditional

Fixes #1845

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java

Fixes #1848 
Two apps, App A and App B.
App A is a normal SDL app.
App B is modified so that it will not enter the foreground when SdlService is started.
Install app A, connect to TDK
Install app B
Observe: 
UncaughtExceptionHandler catches `RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground():`
The exception still hits and the app still crashes.
Tested using Sync 3
Fix UncaughtExceptionHandler in SdlBroadcastReceiver to catch  `RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground():`
The handler does catch it, but only after the exception …

Fix case for UncaughtExceptionHandler in SdlBroadcastReceiver for RemoteServiceException

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

Fixes #1869 
n/a
I tested manually setting the HashMap registerApps to null just before the spot where the NPE was hitting and connecting to a Sync 3 tdk.
This PR adds a null check in the RouterService to prevent an NPE from appearing for a partner app.

Fix NPE in SdlRouterService

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

Fixes #1867 
n/a
Test 1
1. Install SDL app to phone
2. Connect to tdk via Bluetooth
3. Observe SDL app connection
4. Disconnect from tdk by clicking on the BT connection and clicking disconnect on the phone.
Repeat steps 2-4 up to 30 times
Observe: 
Bluetooth notification does not appear for too many apps using Bluetooth.
Test 2
1. Install SDL app to phone 
2. Connect to TDK
3. Disconnect Bluetooth from TDK, but leave Bluetooth turned on.
4. Install and run this app https://github.com/shiniwat/consumespp and let it consume all available SPP resources
5. Connect to TDK
Observe:
Bluetooth notification appears for too many apps using Bluetooth
Core version / branch / commit hash / module tested against: Sync 3
HMI name / …

Bugfix/issue 1867 Bluetooth notification error fix 

---

android/sdl_android/src/main/java/com/smartdevicelink/managers/lifecycle/LifecycleManager.java

Fixes #1865 
n/a
Tested connecting hello sdl using mulit_high_bandwidthDebug build and observed no service connecting leak.
Core version / branch / commit hash / module tested against: Sync 3
HMI name / version / branch / commit hash / module tested against: Sync 3
This PR adds a missing call to clean up the LifecycelManager before closing it.
* This PR fixes the service connection leak seen with high_bandwidth app builds.

Clean LifecycleManager before closing

---

android/hello_sdl_android/build.gradle
android/hello_sdl_android/src/main/AndroidManifest.xml
android/hello_sdl_android/src/main/java/com/sdl/hellosdlandroid/SdlService.java
android/hello_sdl_android/src/main/res/values/strings.xml

Fixes #1863 
n/a
I tested multiple apps including adding a new build variant to hello sdl and having multiple apps connect to sync.
Core version / branch / commit hash / module tested against: Sync 3
HMI name / version / branch / commit hash / module tested against: Sync 3
NOTE: Gradle PR must be reviewed first
This PR improves the build variants for hello sdl so we can test multiple versions of hello sdl by changing a few values or adding a new build variant.

Bugfix/issue 1863 update gradle build variants for hello_sdl

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java

Fixes #1861 
n/a
Note: Before you install a second and thrid app, unplug the phone from the computer and switch the build variant before deploying app to the phone otherwise Android Studio will kill the app. 
Or you can open each app up on the phone after deploying all three apps.
Test 1
Install 3 apps to the phone
Connect via Bluetooth to TDK
Observe all apps connect.
Test 2
Repeat test 1 but with release build versions of the apps.
Core version / branch / commit hash / module tested against: Sync 3
HMI name / version / branch / commit hash / module tested against: Sync 3
This PR adds a package to pending intents in the RouterService to prevent an exception from being thrown in the RouterService.
* Add Package to …

Android 14 add package to PendingIntents in RouterService

---

android/hello_sdl_android/build.gradle
android/sdl_android/build.gradle
android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/LockScreenManager.java
android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/SDLLockScreenActivity.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/TransportManager.java
android/sdl_android/src/main/java/com/smartdevicelink/util/AndroidTools.java
android/sdl_android/src/main/java/com/smartdevicelink/util/MediaStreamingStatus.java
android/sdl_android/src/main/java/com/smartdevicelink/util/ServiceFinder.java

Fixes #1857
No additional unit test were added
Note used an integration branch with All Android 14 PRs to test.
Build variants on Android 14 test plan card on trello.
All Test are designed to trigger BroadcastReceivers that I added the export flag behavior.
Test 1:
Install app A
Connect to TDK via Bluetooth
Enable moving on TDK
Observe:  LockScreen in enabled.
Test 2
Add LockScreenConfig to SdlManager builder with enableDismissGesture to true.
Install Hello_Sdl with TCP build variant.
Connect to manticore
Enable DD
Dismiss LockScreen.
Observe: that LockScreen dismisses.
Test 3.
Install App A
Connect to tdk via Bluetooth
Observe App A connect to tdk
Install App B (Note, Before you install App B, unplug the phone from …

Android 14 Runtime registered broadcast receivers export behavior 

---

base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java

Fixes #1872 
N/A
1. Install base version of Hello SDL (no security)
2. Change package name and SDL app ID in gradle, sync build
3. Install modified Hello SDL
4. Connect to IVI
5. Observe one of the apps connect and the other properly closes because of a duplicate name error
Core version / branch / commit hash / module tested against: Ford TDK Gen3
HMI name / version / branch / commit hash / module tested against:  Ford TDK Gen3
This PR simply adds a check to make sure the`RegisterAppInterface` response RPC was successful. In the case that it is not, it will clean the LCM and close the instance. This allows the app to close its service class as well and be prepared for the next connection. While the test is not a real world …

Add logic to handle RAI response failure

---

.github/workflows/android.yml
android/hello_sdl_android/src/main/AndroidManifest.xml
android/hello_sdl_android/src/main/java/com/sdl/hellosdlandroid/SdlReceiver.java
android/hello_sdl_android/src/main/java/com/sdl/hellosdlandroid/SdlService.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java
android/sdl_android/src/main/java/com/smartdevicelink/transport/UsbTransferProvider.java
android/sdl_android/src/main/java/com/smartdevicelink/util/AndroidTools.java

Fixes #1859 
Unit tests were run on the integration branch. CI check failed due to needing the app to target API 34.
Note: Before you install a second and third app, unplug the phone from the computer and switch the build variant before deploying the app to the phone otherwise Android Studio will kill the app.
Apps A, B and C.
Test 1:
Install App A
Accept BT permission
Install App B
Deny BT permission
Connect to TDK via AOA
Select App A to receive intent
Allow App B to connect when prompted
Observe: App B pass hosting the RS to app A and both apps connect.
Test 2:
Install App A
Deny BT permission
Install App B
Deny BT permission
Connect to TDK via AOA
Select App A to receive intent
Allow App B to connect when prompted …

Android 14 foreground service type required

---

android/sdl_android/src/main/java/com/smartdevicelink/util/IntegrationValidator.java

Fixes #1874 
N/A
N/A
This PR updates the `IntegrationValidator` to include some of the newly required permissions over the last couple of Android OS updates. It also added checks to ensure that the `SdlRouterService` is exported for the app along with the app's extension of the `SdlBroadcastReceiver`.
* Add checks for missing permissions
* Add checks for exported flags being set to try for SDL components

Update integration validator with latest permissions and checks for exported

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java
android/sdl_android/src/main/java/com/smartdevicelink/util/AndroidTools.java

Fixes #1878 
N/A
1. Connect BT with a device with an SDL app installed
2. Allow the RS service to timeout for the connection
3. Open the app again and select "Find new apps"
4. Observe RS notification appears
1. Install another app with HelloSdl on device
2. Connect over BT with IVI
3. Redeploy HelloSdl
4. Observe the router service is taken down and SDL connection is lost
6. Wait a few seconds
7. Observe the router service starts back up and IVI connects to it (Might have to use Find New Apps)
1. Ensure no BT device is connected
2. Install HelloSdl
3. Observe the device listener is not started
Test should also include tests from #1384 and #1685 (except test Multiple apps, one installed after BT connection, non SDL device …

Remove only app logic for device listener start

---

android/sdl_android/src/main/java/com/smartdevicelink/transport/TransportBroker.java

Fixes #1881 
n/a
Test 1: (This is from our test plan using test suite and hello_sdl)
1. This test needs two apps (app1 is custom RS, hello_sdl)
2. Use test suite customRS flavor as an app1, start the app, then go to menu and click on "Start Custom RS"
3. Use hello_sdl with multi_sec_off flavor for the second app but do the following changes:
i.  Change the UUID in MultiplexBluetoothTransport.SERVER_UUID to any other UUID
ii. Modify the way MainActivity starts the SdlService to manually start the SdlService instead of calling queryForConnectedServices
4. Start hello_sdl and make sure it connects through the custom RS
Test 2: (This is the accidental test I ran when I found the NPE)
1. Run test 1 but have second app use …

Fix NPE in TransportBorker 
